Cargo.lock, Cargo.toml, packages/autofmt/src/component.rs, packages/autofmt/src/element.rs, packages/autofmt/src/expr.rs, packages/autofmt/src/lib.rs, packages/autofmt/src/prettier_please.rs, packages/autofmt/src/writer.rs, packages/autofmt/tests/samples.rs, packages/autofmt/tests/samples/many_exprs.rsx, packages/autofmt/tests/wrong.rs, packages/autofmt/tests/wrong/multiexpr-many.rsx, packages/autofmt/tests/wrong/multiexpr-many.wrong.rsx, packages/autofmt/tests/wrong/oneline-expand.rsx, packages/autofmt/tests/wrong/oneline-expand.wrong.rsx, packages/autofmt/tests/wrong/simple-combo-expr.rsx, packages/autofmt/tests/wrong/simple-combo-expr.wrong.rsx
Two issues in autofmt:
- Incorrectly using 1-indexing for columns when we should be doing 0-indexing
- Comments were being written for attributes even when those comments did not belong to those attributes. We now double check who owns the whitespace before writing it out
While doing this overhaul, I also finally ditched the prettier-please crate for the original prettyplease crate, meaning we have 1 fewer vendored crates to maintain (bringing that down the total down to 0!). This does lead to slightly less performance (since we can't make a `File` out of a borrowed `Expr`, but should be imperceptible in practice.
=> Fix #2104: fmt incorrectly using 1-indexing for columns

packages/cli/src/server/web/proxy.rs, packages/hot-reload/src/lib.rs, packages/web/src/eval.rs
Fixes the catchall route used by the proxy which was broken during the hyper upgrade.
Also prevents infinite loops when the api is set to the same port as the dev server.
=> Fix #2088 - rethink proxy logic

Cargo.lock, packages/autofmt/src/component.rs, packages/core-macro/src/props/mod.rs, packages/core/Cargo.toml, packages/core/src/events.rs, packages/core/src/generational_box.rs, packages/core/src/lib.rs, packages/generational-box/src/lib.rs, packages/generational-box/src/references.rs, packages/router/src/components/link.rs, packages/rsx/src/component.rs, packages/signals/src/copy_value.rs, packages/signals/src/global/memo.rs, packages/signals/src/global/signal.rs, packages/signals/src/impls.rs, packages/signals/src/map.rs, packages/signals/src/memo.rs, packages/signals/src/read_only_signal.rs, packages/signals/src/signal.rs
- Makes EventHandler Copy
- Removes the special `on` prefix for event handlers. Instead EventHandler just implements `From<impl FnMut>`
- Cleans up and exposes the `impl` macros for Readable and Writable types
Closes #2100
=> Make EventHandler copy

examples/simple_router.rs, packages/core/src/properties.rs
The docsite is not have a great time trying to onclick working since the changes in #2112 didn't add the additional optional marker.
=> Fix eventhandler optional

packages/fullstack/Cargo.toml, packages/fullstack/examples/axum-auth/src/main.rs, packages/fullstack/src/assets.rs, packages/fullstack/src/axum_adapter.rs, packages/fullstack/src/config.rs, packages/fullstack/src/lib.rs, packages/signals/src/reactive_context.rs
Our compression layer is breaking streaming server functions. This PR removes the default compression layer and instead only compresses static assets in release mode.
~It also adds a more compelling demo for server functions streaming a chat response for an LLM developed for the blog post.~ The demo is a bit dependency heavy for CI, pulled out into a separate repo
Closes #1947
=> Fix streaming server functions, and precompress assets in release mode

Cargo.lock, packages/cli/src/server/web/hot_reload.rs
Hot reload loop wasn't correctly handling the socket stream when closed.
Closes #2123
=> Fix: Hot Reload Blocking

Cargo.lock, packages/check/src/check.rs, packages/core-macro/src/props/mod.rs, packages/core-macro/tests/values_memoize_in_place.rs, packages/core/src/any_props.rs, packages/core/src/diff/component.rs, packages/core/src/properties.rs, packages/hooks/tests/memo.rs
This PR changes memorize to always update self in place. This lets us update some value in place like EventHandlers and ReadOnlySignals.
=> Fix early drop of eventhandlers

packages/core-macro/src/props/mod.rs, packages/core-macro/tests/values_memoize_in_place.rs
Follow up to #2126 to fix this test case:
```rust
let mut enabled = use_signal(|| false);
rsx!(
ScrollThumb {
clicking_scrollbar: enabled(),
onmousedown: move |_| enabled.toggle(),
}
)
}
#[allow(non_snake_case)]
#[component]
pub fn ScrollThumb(
clicking_scrollbar: bool,
onmousedown: EventHandler<MouseEvent>,
) -> Element {
rsx!(
rect {
onmousedown: move |e| {
onmousedown.call(e);
},
width: "100%",
height: "100%",
background: "black",
}
)
}
```
We were manually updating event handlers in place *and* moving over the event handlers from the old to new props. This PR only updates the event handlers in place which fixes the issue
=> Don't move over event handler fields when diffing props

flake.lock, flake.nix
This PR mainly updates `nixpkgs` so that we use the newer Rust compiler.
Without this, the devShell won't be able to build local crates, viz.:
```sh
❯ nix develop -c cargo build -p dioxus-cli
error: package `normpath v1.2.0` cannot be built because it requires rustc 1.74.0 or newer, while the currently active rustc version is 1.73.0
Either upgrade to rustc 1.74.0 or newer, or use
cargo update -p normpath@1.2.0 --precise ver
where `ver` is the latest version of `normpath` supporting rustc 1.73.0
```
=> Fix nix support, by upgrading Rust compiler version

packages/cli/src/cli/bundle.rs, packages/desktop/src/protocol.rs
This copies the asset in the dist directory when bundling applications with the CLI and adds code to dioxus desktop to look in the dist directory even when the application is run without cargo
Fixes https://github.com/DioxusLabs/dioxus/issues/2144
=> Fix asset bundling in the CLI

packages/cli/src/server/desktop/mod.rs, packages/desktop/Cargo.toml, packages/desktop/src/app.rs, packages/hot-reload/src/file_watcher.rs, packages/hot-reload/src/lib.rs
This switches to `@dioxusin` instead of a directory for windows hot reloading and fixes a race condition between the desktop build and the hot reloading server
Closes https://github.com/DioxusLabs/dioxus/issues/1914
=> Fix hot reload on windows

Cargo.lock, packages/check/src/issues.rs, packages/cli-config/src/config.rs, packages/cli/src/cli/build.rs, packages/cli/src/cli/serve.rs, packages/desktop/src/config.rs, packages/desktop/src/query.rs, packages/fullstack/src/server_fn/collection.rs, packages/html/src/eval.rs, packages/html/src/events/mounted.rs, packages/liveview/src/lib.rs, packages/liveview/src/query.rs, packages/router/src/routable.rs, packages/ssr/src/cache.rs, packages/ssr/src/incremental.rs, packages/web/src/rehydrate.rs
Make some error enums and other enums dioxus may want to change in a minor release exhaustive to avoid semvar breaking changes in 0.5.1
=> Make some enums non-exhaustive

packages/router-macro/Cargo.toml, packages/router-macro/src/lib.rs, packages/router/Cargo.toml, packages/router/examples/simple_routes.rs
In the web history if a field is not present in the URL, it will not be passed to the route (even without reloading the page). This PR adds a compiler error when the web feature is enabled and a field included in the router is not present in the URL.
=> Require every field in router variants to be present in the route in the web history

Cargo.lock, packages/dioxus/src/launch.rs
When just building with the mobile feature enabled, the dioxus crate fails to compile because `dioxus_desktop` is no longer a direct dependency. This PR fixes that issue by re-exporting `dioxus_mobile` (which re-exports `dioxus_desktop`) when the mobile feature is enabled instead
=> Fix the mobile feature on the dioxus crate

.gitignore, Cargo.lock, packages/ssr/src/cache.rs, packages/web/src/rehydrate.rs
This PR fixes hydration for static text nodes at the root of templates. Here is a small example that works on this branch, but is broken in the published version of dioxus:
```rust
fn main() {
launch(app);
}
let mut count = use_signal(|| 0);
rsx! {
h1 { "High-Five counter: {count}" }
button { onclick: move |_| count += 1, "Up high!" }
button { onclick: move |_| count -= 1, "Down low!" }
if count() > 10 {
"Big number!"
}
else {
"Small number!"
}
}
}
```
Fixes https://github.com/DioxusLabs/docsite/issues/234
=> Fix hydration for static text nodes at the root of the template

Cargo.lock, packages/router-macro/src/lib.rs
Followup to #2159
This PR fixes an error that happens when a child field is used with the web router in the docsite. It currently triggers an unused field error even though the `child` field is used
(NOTE: the child attribute is not currently a public API and is intentionally undocumented)
=> Fix child routers with the web history

README.md
The Dioxus example and Leptos example for iteration given in the README are currently different, both in end-user functionality and in mechanism.
I might be mistaken, but my assumption is that the Dioxus example shows a non-keyed list, i.e., removing the element at index 1 from a 10-element list causes all subsequent elements to update, even though only the text nodes need to diff. This has implications for the behavior of things like CSS elements that are [well described elsewhere](https://www.stefankrause.net/wp/?p=342). The Leptos example shown by comparison is a keyed list. 
Similarly, again unless I'm mistaken, updating the value of a counter in the Dioxus example does an O(n) diff of all the values of all rows, whereas the Leptos example shown by comparison updates a single nested …
=> Make Leptos iteration example equivalent of Dioxus iteration example

README.md
For leptos code, there is no need for Memorization here. As memorization of the values of the text nodes in the renderer already happens.
=> Fix for Counters sample code in Readme

packages/ssr/src/cache.rs, packages/ssr/src/fs_cache.rs, packages/ssr/src/incremental.rs, packages/ssr/src/renderer.rs
This PR fixes rendering aborted nodes in the SSR renderer by first converting nodes to VNodes and then rendering the VNode. It also cleans up a few unused items in the SSR renderer
Fixes #2190
=> Fix rendering aborted nodes in SSR

packages/core/src/global_context.rs, packages/core/src/scope_context.rs, packages/core/tests/task.rs
This PR fixes spawn forever by spawning the future in the root scope. This may result in unexpected behavior with global APIs which are now documented. It also adds a test to prevent future regressions
Fixes #2215
=> Fix and test spawn_forever

packages/core/src/nodes.rs
This PR changes the placeholder and empty nodes in core to reuse the same `Rc<NodeInner>` for every instance per thread. NodeInner is completely immutable, so using the same instance for every VNode will not effect behavior
=> Reuse placeholder nodes on each thread to reduce allocation

packages/html/Cargo.toml, packages/html/src/events.rs, packages/ssr/src/renderer.rs
This PR fixes hydration for non-bubbling events like the onmouseenter event in the hackernews guide. We were not correctly trimming the `on` prefix from events before checking if the event was bubbling in SSR which meant the default `true` value was always returned
=> Fix hydration for non-bubbling events

packages/core/src/virtual_dom.rs, packages/hooks/tests/memo.rs
Also fixes the memochain example by calling process_events in more places.
This code needs to be refactored/lightly rewritten since we've done a lot of work with suspense and memos recently. These are little bugs that should be easy to catch.
=> Fix: requeue events, process events 

Cargo.lock, packages/core/src/nodes.rs, packages/generational-box/src/lib.rs
We switched over to Copy types for EventHandlers on elements which is equivalent to calling Signal::new(). This is not necessary for elements, just for child components, and thus caused a memory leak for long-running components.
This PR adds a drop impl to VNode to manually drop listeners when the last VNodeInner is dropped. We can't add the drop impl anywhere else since VNode is the only struct in the chain that can't be destructured, making it semver compatible.
Fix: #2227
=> Fix: memory leak on listeners for elements

packages/cli/src/assets/autoreload.js, packages/fullstack/src/render.rs
This just copies the dioxus-cli's script back into fullstack inline. In the future, we should try to pull out the hot reloading code into a separate package that both the CLI and fullstack can use to serve the websocket
=> fix the relative paths issue in the fullstack crates.io build

packages/desktop/src/protocol.rs
Currently, it emits a `tracing::error` when assets not being preloaded if the dioxus CLI was not used to build the application. It should be a warning since `cargo` can also build the application successfully.
Fix [#2231](https://github.com/DioxusLabs/dioxus/issues/2231)
=> Use `tracing::warn!` instead of `error!` when assets not being preloaded

packages/cli-config/src/lib.rs
Currently, it emits a `tracing::error` when the dioxus CLI was not used to build the application. It should be a warning since `cargo` can also build the application successfully.
=> Use `tracing::warn!` instead of `error!` when the dioxus CLI is not used

packages/cli/src/cli/bundle.rs
Playing around with [Publishing](https://dioxuslabs.com/learn/0.5/cookbook/publishing), the docs recommended to use a feature to disable the console on Windows when bundling. That worked with `dx build` but not `dx bundle`.
This PR fixes that by passing features to `cargo` when using `dx bundle`, which is the same behaviour as `dx build`
=> Fix features not passed from dx bundle to cargo

packages/core/src/diff/node.rs
This PR fixes diffing volatile attributes. Any volatile attributes should always be written even if the value appears not to have changed because the browser may have changed the attribute. This fixes this example:
```rust
fn main() {
launch(app);
}
let mut count = use_signal(|| 0);
rsx! {
input {
value: count,
r#type: "number",
oninput: move |evt| {
if let Ok(value) = evt.value().parse::<i64>() {
if value < 0 {
count.set(0);
}
else {
count.set(value);
}
}
},
}
}
}
```
=> Fix volatile attributes

packages/core/src/dirty_scope.rs, packages/core/src/virtual_dom.rs
This changes the task queue for each scope from a Vec to a VecDeque to preserve the order we poll tasks in a single scope. This fixes effect ordering which uses futures internally
Fixes https://github.com/DioxusLabs/dioxus/issues/2262
=> Poll tasks in the same order they are queued

packages/desktop/src/protocol.rs
This PR fixes the path to the `__assets_head.html` file the CLI generates for manganis assets. 
In bundled applications the path is `$root/dist/__assets_head.html`, but in applications served by the CLI, the path is `$root/__assets_head.html`. We currently only check for the path that will be available in the bundled application. This PR fixes the issue by checking both paths
=> Fix the assets head path

packages/rsx/src/attribute.rs, packages/rsx/src/component.rs, packages/rsx/src/context.rs, packages/rsx/src/element.rs, packages/rsx/src/lib.rs, packages/rsx/src/node.rs, packages/rsx/src/renderer.rs, packages/web/src/hot_reload.rs
We expand empty rsx statements to `None` instead of an empty template so that there is a root node for the template for diffing. This PR expands that behavior to the body of if statements, for loops and children
Fixes #2270
=> Fix empty for loop, if statements and children

packages/autofmt/src/component.rs, packages/autofmt/src/writer.rs, packages/autofmt/tests/samples/complex.rsx
I guess we never printed keys on components! This fixes that.
Fix #2252
=> Fix: autofmt shouldn't eat keys

packages/core-macro/src/props/mod.rs
#2286 Event handlers used as component props may currently be dropped twice or not at all due to a bug in props.
This fixes the error for `Option<EventHandler>` by updating `looks_like_event_handler_type`
=> Fix event handler drops

packages/cli/src/builder.rs
Closes #2221 
**Cause**
https://github.com/console-rs/indicatif/issues/638
**Solution**
Switch the cog emoji to a similar one.
=> Fix: CLI Compilation Spam

packages/fullstack/examples/axum-desktop/src/client.rs
`set_server_url` is no longer directly under the [prelude](https://github.com/DioxusLabs/dioxus/blob/main/packages/fullstack/src/lib.rs#L40)
=> fix path of set_server_url

examples/custom_menu.rs, packages/desktop/src/hooks.rs, packages/desktop/src/lib.rs
This PR creates a new hook to listen for muda events. This makes it possible to respond to clicking on a menu item in dioxus. This data is also exposed in the `UserEvent` dioxus uses but that enum is currently private and contains some internal information including what futures have been polled
=> Create use_muda_event_handler hook

packages/router-macro/src/segment.rs
This PR fixes parsing for routes that have fields in the route string in a different order than they were defined in the enum variant
Fixes #2353
=> Fix out of order fields in route definitions

packages/core/src/diff/node.rs, packages/desktop/headless_tests/events.rs, packages/desktop/headless_tests/rendering.rs
Part of the code to reclaim ids for elements with dynamic attributes assumed that attr_paths would be in depth first order which may not be true if the template was hot reloaded
Fixes https://github.com/DioxusLabs/dioxus/issues/2238
=> Fix reclaim element when hot reloading

packages/signals/src/signal.rs
We have slightly wrong behavior when writing to a signal. If any subscriptions are added while marking a signal as dirty, they will currently be ignored. This PR changes behavior to add those subscriptions.
In practice, this edge case is very difficult to hit. You would need to read a signal in a memo then write to the signal and read the memo in the same render
Closes #2306
=> Extend the subscriber list instead of overriding it; fixes subscribers added in mark_dirty

packages/signals/src/reactive_context.rs, packages/signals/src/signal.rs
This adds two new warnings for signals:
Writing to a signal in the body of a component can cause an infinite loop.
For example this code:
```rust
let mut count = use_signal(|| 0);
count += 1;
rsx! {
h1 { "High-Five counter: {count}" }
button { onclick: move |_| count += 1, "Up high!" }
button { onclick: move |_| count -= 1, "Down low!" }
}
}
```
Now produces these warnings:
```
2024-04-08T17:28:04.697417Z  WARN dioxus_signals::signal: Write on signal at examples/readme.rs:17:5 happened while a component was running. Writing to signals during a render can cause infinite rerenders when you read the same signal in the component. Consider writing to the signal in an effect, future, or event handler if possible.
2024-04-08T17:28:04.697474Z  WARN dioxus_signals::signal: …
```
=> Warnings for signal writes that may cause infinite loops

packages/signals/src/copy_value.rs, packages/signals/src/memo.rs
This PR removes a once cell from the use_memo hook that was set but never used
=> Remove unused once-cell in memo

Cargo.lock, packages/fullstack/Cargo.toml, packages/server-macro/Cargo.toml
This PR fixes calling server functions on desktop applications. The feature flags were configured incorrectly for the server function macro on desktop which was causing desktop applications to use the request crate for web builds
Closes #2322
=> Fix calling server functions on desktop

packages/html/src/events/form.rs
This allows me to write a function that can accept both `Event<DragData>` and `Event<FormData>` as `Event<T: HasFileData>` -- without this PR, `DragData` [has `impl HasFileData`](https://github.com/DioxusLabs/dioxus/blob/a5b4ceed39e2aaa3e517c4f23f466fe2ff67d028/packages/html/src/events/drag.rs#L61) such that I can do `event.files()` but while `FormData` can do `event.files()` it is because that is [explicitly a part of `FormData`](https://github.com/DioxusLabs/dioxus/blob/a5b4ceed39e2aaa3e517c4f23f466fe2ff67d028/packages/html/src/events/form.rs#L109), not with an `impl HasFileData` so each event would need to be handled separately. Now they can be handled together.
I am tempted to remove the `impl FormData ... fn files()` (linked above) and let this new `impl HasFileData` take over, but I …
=> impl HasFileData for FormData

packages/core/src/error_boundary.rs, packages/core/src/fragment.rs
Memorize no longer just compares props. It also moves over props if they are different.
Fragment was not updated when `memorize` changed from comparing to comparing and reconciling props which caused diffing issues. This PR updates the manual prop implementation of Fragment and ErrorBoundary to fix those diffing issues
Fixes #2359
=> Fix memorization for the fragment component

packages/cli/src/builder.rs, packages/cli/src/server/web/mod.rs, packages/cli/src/server/web/server.rs, packages/desktop/headless_tests/eval.rs, packages/interpreter/src/lib.rs, packages/router/src/history/web.rs
This PR updates how the the axum router constructed for `dx serve`, the `--open` option, and the dioxus-router `WebHistory` interact with the Dioxus.toml `base_path` field.
Prior to this change, running `dx serve` with a `base_path` set always resulted in my browser displaying the "Outside of the base path: blah" message, even when I was navigating to routes that were very definitely inside of the base path.
Three major changes are included in this PR;
- Setting a `base_path` now causes the `dx serve` router to be nested under the base path, rather than treating the base path as a route that is handled with a `axum::routing::any_service`. 
- The `--open` flag now opens to `localhost:8080/<base_path>` rather than to `localhost:8080`.
- The dioxus router's default web history initializes to …
=> Improve the base_path story

packages/fullstack/src/hooks/server_future.rs
This PR changes use_server_future to accept FnMut which makes it possible to use `use_server_future` with `use_reactive`
=> Make use_server_future accept FnMut

packages/cli/src/cli/create.rs, packages/cli/src/cli/init.rs
Previously only `dx new` had this ability, now `dx init` has it, too.
=> feat(cli): init cmd can now skip user interaction

packages/html/src/web_sys_bind/events.rs
The scroll position was returned, when the `element.scrollWidth` and `element.scrollHeight` are expected.
=> The value returned by get_scroll_size method is invalid

packages/core-macro/src/props/mod.rs
Currently, it doesn't seem like you can pass the docs from a prop field to its method generated via the `Props` derive. The only way to achieve this is to duplicate the doc into a dedicated `#[props(doc = "My doc comment")]` attribute.
This, however, is both inconvenient and error-prone since users will need to handle the formatting manually and all in a single attribute.
Pass along all `#[doc]` attributes on a prop field to the respective function. This allows the documentation to be shared by that method and show up on hover when using the component.
Here's a before/after comparison in Rust Rover:
| Before | After |
| ------ | ----- |
| <img width="100%" alt="dioxus_prop_docs--before" src="https://github.com/DioxusLabs/dioxus/assets/49806985/6dd7ef19-6eb7-4c33-b7ae-1af5c177e42b"> | <img …
=> Make use of `#[doc]` field attributes in `Props` derive macro

Cargo.lock, packages/hooks/src/use_context.rs
`provide_context` already clones the context internally
=> fix: Avoid cloning a provided context unnecessarily

packages/generational-box/src/sync.rs
This pull request replaces the use of `RwLock::try_read` with `RwLock::read` in the `SyncStorage`. 
This change prioritizes potential deadlocks over panics. Unwrapping a failed `try_read` can lead to unexpected behavior and difficult-to-debug issues. Using `RwLock::read` ensures that the code will always block until a read lock is acquired, preventing potential panics but introducing the possibility of deadlocks.
This change is consistent with the current use of [RwLock::write](https://github.com/DioxusLabs/dioxus/blob/main/packages/generational-box/src/sync.rs#L146) for write operations.
**Changes:**
* Replaces `RwLock::try_read` with `RwLock::read` in `SyncStorage`.
**Rationale:**
* Prioritizes potential deadlocks over panics.
* Ensures consistent API with `RwLock::write` for write …
=> Replace `RwLock::try_read` with `RwLock::read` in `SyncStorage`

packages/router-macro/src/lib.rs
This resolves an edge-case that may arise if you (for some _weird_ reason) rename the dioxus dependency with the Cargo.toml `package = ...` key.
Consider a Cargo.toml with:
```
dioxus_but_named_wrong = { version = "0.5", features = ["web", "router"], package = "dioxus" }
```
And a main.rs with:
```
use dioxus_but_named_wrong::prelude::*;
```
If you then use the Routable derive macro, the compiler will error with:
```
error[E0433]: failed to resolve: could not find `dioxus` in the list of imported crates
--> src/main.rs:6:17
|
6 | #[derive(Clone, Routable, Debug, PartialEq)]
|                 ^^^^^^^^ could not find `dioxus` in the list of imported crates
|
= note: this error originates in the derive macro `Routable` (in Nightly builds, run with -Z macro-backtrace for more info)
```
By …
=> Switch from an absolute ::dioxus to the relative dioxus_core

Cargo.lock, packages/core-macro/Cargo.toml
Removes the `constcat` dependency from `core-macro`, as it is unused.
=> Remove unused dependency from core-macro

packages/interpreter/src/unified_bindings.rs
This changes the logic for `None` values for the `value` attribute. We were previously just resetting the value which causes issues if the attribute is actually an attribute instead of a property. This PR changes `None` to both remove the attribute and reset the property
Fixes #2478
=> Remove value attribute instead of resetting it

packages/hooks/src/use_resource.rs, packages/signals/src/memo.rs, packages/signals/src/signal.rs
This PR fixes the line numbers for tracing logs from the use_memo and use_resource hooks. Before this PR writes on signals that cause use_resource to rerun point to the use_resource hook instead of where that hook was created.
Old:
```
TRACE /dioxus/packages/signals/src/signal.rs:301 Subscribing to the reactive context ReactiveContext created at /dioxus/packages/hooks/src/use_resource.rs:79:29
```
New:
```
TRACE /dioxus/packages/signals/src/signal.rs:301 Subscribing to the reactive context ReactiveContext created at /myapp:line:col
```
=> Fix memo and resource line info

packages/router/src/router_cfg.rs, packages/router/tests/via_ssr/main.rs, packages/router/tests/via_ssr/without_index.rs
Fixes router enmus without an index (`/`) route. We were previously unconditionally parsing the route as an index route and then using the override route if the user provided one. This PR changes the router to only parse the default index route if no override was provided
Fixes https://github.com/DioxusLabs/dioxus/issues/2468
=> Fix routers without an index route

packages/core/src/arena.rs, packages/core/src/diff/node.rs, packages/core/src/nodes.rs, packages/core/src/virtual_dom.rs
Our event bubbling code within a template currently relies on dynamic attributes being in depth first order, but after a template is hot reloaded, its dynamic attributes may not be in depth first order. This PR changes the event bubbling code to sort the attributes before bubbling nodes if hot reloading is enabled
Fixes #2481
=> Fix event bubbling inside templates after a hot template reload

packages/cli/src/cli/bundle.rs, packages/desktop/src/protocol.rs
This PR changes dx bundle to copy individual assets instead of the whole dist directory to avoid recursively copying into itself
Fixes https://github.com/DioxusLabs/dioxus/issues/2239
=> Fix recursive copy while bundling

packages/core-macro/src/component.rs, packages/core/src/lib.rs, packages/core/src/properties.rs
This PR adds a runtime error for when components are called as functions. It will warn the user if they do something like this:
```rust
#[component]
fn MyComponent() {
rsx! { "hello world" }
}
fn app() {
rsx! { {MyComponent()} }
}
```
=> Detect components called as functions

Cargo.lock, Cargo.toml, packages/core/Cargo.toml, packages/core/src/runtime.rs, packages/core/src/tasks.rs
This is an alternate solution to #2440 that addresses the wider [ABA problem](https://en.wikipedia.org/wiki/ABA_problem) with tasks by introducing generationals to tasks.
This PR is non-breaking so it can be backported to 0.5. `ElementId` and `ScopeId` have similar problems, but they are intentionally not changed in this PR because the inner `usize` type is public, and too small for generations on wasm where `usize` is `u32`
=> switch from slab to slotmap for tasks to fix the ABA problem

packages/core-macro/src/props/mod.rs
This makes `#[props(into)]` on string properties a no-op. We already coerce any types that implement `Display` into a String without the attribute. It can be confusing that adding the `#[props(into)]` attribute makes the properties accept fewer types
Closes #2497
=> Ignore `#[props(into)]` on Strings

Cargo.lock, packages/cli-config/src/config.rs, packages/cli/Cargo.toml, packages/cli/src/assets/dioxus.toml, packages/cli/src/builder.rs, packages/cli/src/tools.rs
Adds wasm-opt support to the CLI without an external tool/CLI. This makes the default release wasm builds smaller and makes it possible to use the CLI for the smallest possible builds instead of trunk. A hello world binary with this version of the CLI is ~103kb or ~42kb with brotli compression.
wasm-opt shrinks most binaries between 4-6% depending on the opt-level. Not a huge difference, but nice to have built in
Closes https://github.com/DioxusLabs/dioxus/issues/1503
=> Integrate wasm-opt into the CLI

packages/html/src/file_data.rs, packages/html/src/native_bind/native_file_engine.rs, packages/web/src/file_engine.rs
This allows file sizes to be checked *before* loading the entire file into memory (e.g. with `read_file`) when it might be too big. (And without requesting the native file to do this check manually.)
=> add file size to FileEngine

.github/workflows/main.yml, Cargo.toml, Makefile.toml, packages/desktop/src/app.rs, packages/generational-box/tests/errors.rs
This adds an extra step that tests packages with debug assertions off (but without optimizations) to test the faster paths in core and other packages. This should prevent regressions like https://github.com/DioxusLabs/dioxus/commit/79e18c2d62166f388641cd6e20a82bef2506535a
=> Add CI step to test packages with debug assertions off

packages/desktop/src/config.rs, packages/desktop/src/webview.rs
This is a very simple PR, that is tested to work on my Fedora machine, although I'm unable to do any real testing on other OSs.
For some reason `wry` doesn't like using synchronous custom protocols, I'm sure you've experienced that since it appear's you're also using the asynchronous one, so I've added an extra config option that adds asynchronous ones.
this is gonna be a case of certified ISO 9000 - Works on my machine, as such I encourage others to test on their machines.
Also added a QoL fix that allows the passing of anything that implements `ToString` instead of a string, since it may be a safe assumption that most of the time, it'd be passed in as a string literal.
=> Update `dioxus_desktop::Config` to also allow for asynchronous custom protocol handlers

packages/desktop/src/launch.rs, packages/dioxus/src/launch.rs, packages/fullstack/src/launch.rs, packages/liveview/src/launch.rs, packages/web/src/launch.rs
This PR changes the function signature of `launch` to return `!`. This tells the compiler that it can never exit which provides warnings if you try to run code after the launch function like this code snippet:
=> Assert that launch never returns for better compiler errors

packages/html/src/attribute_groups.rs
`r#type` currently expands to the attribute `"r#type"` in the browser instead of `"type"`. This PR fixes that bug
=> Fix raw attribute names

packages/core-macro/docs/component.md, packages/core-macro/docs/props.md, packages/core-macro/docs/rsx.md, packages/core-macro/src/lib.rs, packages/core/src/global_context.rs, packages/core/src/scope_context.rs, packages/dioxus/src/lib.rs, packages/rsx/src/sub_templates.rs
This PR adds docs to the props and component macros with a bunch of examples that showcase what different `#[props]` attributes change
=> Document props and component macro

packages/config-macro/src/lib.rs, packages/core/src/events.rs, packages/hooks/src/use_callback.rs, packages/signals/src/read.rs
This PR pulls out the code to define each config macro into a macro rules and adds an extra block to the return value. This makes it possible to use the macro with multiple statements like:
```rust
server_only! {
let value = 0;
value
}
```
=> Simplify dioxus-config-macro

Cargo.toml, packages/cli-config/Cargo.toml, packages/cli/Cargo.toml, packages/core/Cargo.toml, packages/desktop/Cargo.toml, packages/desktop/src/launch.rs, packages/dioxus-lib/Cargo.toml, packages/dioxus/Cargo.toml, packages/fullstack/Cargo.toml, packages/hot-reload/Cargo.toml, packages/html/Cargo.toml, packages/interpreter/Cargo.toml, packages/liveview/Cargo.toml, packages/router/Cargo.toml, packages/router/src/history/web_scroll.rs, packages/router/src/router_cfg.rs, packages/rsx/Cargo.toml, packages/signals/Cargo.toml, packages/signals/src/copy_value.rs, packages/signals/src/read_only_signal.rs, packages/signals/src/signal.rs, packages/ssr/Cargo.toml, packages/static-generation/Cargo.toml, packages/web/Cargo.toml
Optional dependencies add implicit features to crates if they are never used with `dep:`. This PR switches all of our optional dependencies to use `dep:` to remove those useless features
Closes #2513
=> Remove implicit optional dependency features

Cargo.lock, packages/dioxus/Cargo.toml, packages/dioxus/src/launch.rs, packages/dioxus/src/lib.rs, packages/fullstack/Cargo.toml, packages/fullstack/examples/axum-auth/src/main.rs, packages/fullstack/examples/axum-desktop/src/server.rs, packages/fullstack/src/axum_adapter.rs, packages/fullstack/src/config.rs, packages/fullstack/src/launch.rs, packages/fullstack/src/lib.rs, packages/fullstack/src/server_context.rs
This PR changes the context function in the launch builder to provide context throughout the fullstack application including in server functions. You can now consume context in server functions with an extractor:
```rust
LaunchBuilder::new().with_context(1234567890u32).launch(app);
#[server]
async fn get_server_data() -> Result<String, ServerFnError> {
let FromContext(context): FromContext<u32> = extract().await?;
let text = reqwest::get("https://httpbin.org/ip").await?.text().await?;
Ok(format!("context {context} Your IP address is: {text} 🌎"))
}
```
Closes #2131
Closes #1688
=> Make it easier to provide context to fullstack

packages/fullstack/src/config.rs
Changes the default listen IP for fullstack from `127.0.0.1` to `0.0.0.0` so that external connections are allowed by default for a more "launch and go" experience with deployment.
=> Revision: Change Default Fullstack IP

flake.nix
A few packages were missing from flake.nix needed to build tests.
=> Add missing packages in flake.nix

packages/rsx/src/hot_reload/hot_reloading_file_map.rs
I found hot-reloading doesn't seem to be working for me on Windows because the initial output of `rsx` has template names like:
```
src/main.rs:9:5:0
```
while hot-reload updates have different names such as:
```
src\main.rs:9:5:0
```
This converts the template path to a UNIX-style path to be compatible with the `file!` macro. This seems to fix hot-reload on my machine but I'm not sure how robust this is just yet. I'd love some help testing!
=> Fix hot-reloading on Windows

packages/core/src/diff/node.rs, packages/core/src/error_boundary.rs, packages/core/src/virtual_dom.rs, packages/fullstack/src/axum_adapter.rs, packages/hooks/src/use_sorted.rs, packages/html/src/elements.rs, packages/router/src/routable.rs, packages/router/tests/site_map.rs, packages/server-macro/src/lib.rs, packages/signals/src/signal.rs
I like using todo!() as an indicator of code that hasn't been finished yet in a given PR but having them scattered throughout main breaks that workflow.
This simple tweak changes todo!() to unimplemented!() in the doctests which leaves us with zero todo!() left in the codebase.
I did this in #2258 but am splitting this out to a separate PR to shrink the diff on that PR.
=> Chore: move todo!() to unimplemented!()

packages/cli/README.md
Adds a section to the CLI readme that mentions the faster-to-build `cli-dev` profile.
=> Add Section To CLI `README.md` About `cli-dev` Profile

packages/autofmt/src/lib.rs, packages/cli/src/cli/translate.rs, packages/extension/src/lib.rs, packages/rsx-rosetta/examples/html.rs, packages/rsx-rosetta/tests/h-tags.rs, packages/rsx-rosetta/tests/raw.rs, packages/rsx-rosetta/tests/simple.rs, packages/rsx-rosetta/tests/web-component.rs
Trying to make the diff in #2258 smaller by extracting small changes out.
=> Switch to using refs instead of owned for autofmt write block out

packages/fullstack/src/axum_adapter.rs
Instead of unwrapping when we can't get the information we need out of the URI, this PR returns an error for the request
Closes #2576
=> Return error when unable to parse request uri

packages/desktop/src/app.rs
fixes regression of https://github.com/DioxusLabs/dioxus/pull/1588 mentioned in discord.
It looks like a [single line](https://github.com/DioxusLabs/dioxus/pull/1588/files#diff-b0579535f28f7caa593a8664352df35bb34350c47fe2c326d6f4af792bb3a439R16) was missed when translating to v5 which changed the builder setting for `set_visible` to false until after rendering
=> fix (desktop): hide window until the first render

packages/core/src/any_props.rs, packages/core/src/arena.rs, packages/core/src/diff/component.rs, packages/core/src/events.rs, packages/core/src/runtime.rs, packages/core/src/scope_arena.rs, packages/core/src/scope_context.rs, packages/core/src/suspense/component.rs, packages/core/src/suspense/mod.rs, packages/core/src/tasks.rs, packages/core/src/virtual_dom.rs, packages/fullstack/src/html_storage/serialize.rs, packages/fullstack/src/render.rs, packages/web/src/hydration/hydrate.rs
Fixes the panic in https://github.com/DioxusLabs/dioxus/issues/2570. This PR fixes warnings when trying to update nodes on the server in the resolved part of the tree. This can happen when an error boundary is above a suspense boundary and the suspense boundary throws an error up into the client controlled error boundary.
It also fixes `render_suspense_immediate` returning `ScopeId`s that were removed
=> Improve warnings when trying to update outside of pending suspense boundaries on the server

packages/core-macro/src/props/mod.rs, packages/core-macro/tests/generics.rs
If the struct is defined with a where clause we need to forward that clause to the version of the builder that owns the data. This PR forwards the clause and adds tests for prop generics to prevent regressions
Fixes #2663
=> Fix deriving props with a where clause and an owner

.github/workflows/main.yml, .gitignore, packages/cli/src/builder/cargo.rs, packages/cli/src/builder/fullstack.rs, packages/cli/src/builder/web.rs, packages/cli/src/cli/serve.rs, packages/cli/src/serve/mod.rs, packages/cli/src/serve/output.rs, packages/cli/src/serve/server.rs, packages/core-macro/tests/rsx/trailing-comma-0.stderr, packages/fullstack/src/serve_config.rs, packages/rsx/src/literal.rs, packages/rsx/src/template_body.rs
Fixes some CI but doesn't fix the playwright issues - these require more complex fixes now with the loading screen.
Notably:
- Moves index.html creation until after wasm creation so the webserver doesn't prematurely serve the page
- sets up nasm for windows builds (to be superseded by #2682)
- puts magnanis-cli-support in a blocking task to prevent threadlocking during sequential builds
- changes order of client/server builds such that the client is built before the server so the webserver doesn't prematurely serve invalid client code
- declobbers "serve" such that each project gets a different dir in the target folder
- uses nest_service instead of fallback so the router doesn't respond with fallback codes
- reincorporates doge's fix from #2544
=> Fix some CI (windows + nasm, core-macro error)

packages/core/src/nodes.rs, packages/generational-box/Cargo.toml, packages/generational-box/src/entry.rs, packages/generational-box/src/error.rs, packages/generational-box/src/lib.rs, packages/generational-box/src/references.rs, packages/generational-box/src/sync.rs, packages/generational-box/src/unsync.rs, packages/generational-box/tests/basic.rs, packages/generational-box/tests/errors.rs, packages/generational-box/tests/sync.rs, packages/signals/src/copy_value.rs, packages/signals/src/signal.rs
This PR fixes a race condition with generations in sync storage. It also removes the check generations flag to simplify the crate and removes configs from all public APIs
Fixes #2636
=> Fix generation race condition with sync storage

packages/rsx/src/attribute.rs
We parse attributes with no trailing comma, but because of the way we expand the completions module, it was generating a compile error. This PR fixes that issue
Fixes #2626
=> Allow no trailing comma after attributes

packages/rsx/src/rsx_block.rs
If we hit something like this:
```rust
div {
Com
}
```
This PR expands `Com` to a partial component instead of an attribute. For elements this should be non-breaking, but for component properties, this is technically breaking if anyone was using properties that start with a capital letter
=> Expand to a partial Component if a shorthand attribute starts with a capital letter

packages/cli/src/serve/output.rs
Logs weren't being removed after printing and would spam in the console in non-interactive mode.
=> Fix: CLI Drain Logs

packages/cli/src/serve/watcher.rs
Hot reload did not work on Windows. The problem was that the `notify` crate would return `ModifyKind::Any` instead of the `ModifyKind::Data`that we expected so we ignored it.
=> Fix: Windows Hot Reload

packages/cli/src/serve/watcher.rs
We were feeding the `ignore` crate the wrong data and it would build an empty ignore list. Fixing this greatly speeds up `serve` start times as we aren't checking every file in folders like `target`.
=> Fix: File Watcher Ignore List

Cargo.lock, packages/cli-config/Cargo.toml, packages/cli-config/build.rs, packages/cli-config/src/build_info.rs, packages/cli-config/src/lib.rs, packages/cli/src/builder/cargo.rs
Instead of complaining that the application isn't built with the CLI if serialization of the dioxus config fails. This PR tells the user that the versions might be mismatching and prints the versions for debugging
=> Improve error message when the CLI and dioxus versions don't match

packages/cli/src/cli/mod.rs
A few notes:
- consider updating `built`'s version
- consider using [`vergen`](https://crates.io/crates/vergen) [instead](https://discord.com/channels/899851952891002890/928812591126569000/1265731211100291072)
- maybe change the message when failed to get commit hash during built (no `.git` etc.)
- used [tinymist](https://github.com/Myriad-Dreamin/tinymist/blob/ff729623342c91576485c60e60fd9d48707ad1a7/crates/tinymist/src/args.rs#L52) as a reference
Closes #2693.
=> feat(cli): added git commit hash to version output

examples/rsx_usage.rs, packages/autofmt/src/rsx_block.rs, packages/autofmt/src/writer.rs, packages/core-macro/tests/rsx/trailing-comma-0.stderr, packages/rsx/src/attribute.rs, packages/rsx/src/element.rs, packages/rsx/src/ifchain.rs, packages/rsx/src/ifmt.rs, packages/rsx/src/scoring.rs
We were parsing `if {} else {}` as expressions which means any string values in the branches were not formatted correctly and we didn't allow merging the attribute because it was an expression
Fixes #2691
=> fix formatting and merging if chains in attributes

packages/core/src/tasks.rs
I added `#[cfg(feature = "debug_assertions")]` instead of `#[cfg(debug_assertions)]`, sorry I didn't notice the error until now
=> Fix `debug_assertions` in `core::tasks`

Cargo.lock, packages/generational-box/src/error.rs, packages/hooks/src/use_future.rs, packages/hooks/src/use_resource.rs, packages/signals/src/copy_value.rs, packages/signals/src/global/memo.rs, packages/signals/src/global/signal.rs, packages/signals/src/impls.rs, packages/signals/src/map.rs, packages/signals/src/memo.rs, packages/signals/src/read.rs, packages/signals/src/read_only_signal.rs, packages/signals/src/signal.rs
Our implementation for Readable was inconsistent.
We had a try_unchecked variant for read but not for peek.
This resolves that by making a breaking change to the
Readable interface.
Fix #2612
=> Fix #2612: adjust readable trait to allow try_peek

Cargo.lock, packages/cli-config/src/config.rs, packages/cli/src/cli/config.rs, packages/cli/src/cli/serve.rs, packages/cli/src/settings.rs, packages/desktop/src/config.rs
Adds a new CLI setting for configuring the always-on-top CLI setting for debug-mode Dioxus desktop.
Closes #2354
=> Feat: `always_on_top` CLI Setting

.github/workflows/main.yml, Cargo.lock, Cargo.toml, examples/tailwind/Cargo.toml, packages/cli/Cargo.toml, packages/dioxus-lib/Cargo.toml, packages/dioxus/Cargo.toml, packages/rsx/src/hotreload.rs, packages/signals/Cargo.toml
- Fix: bump msrv up to be valid for cli
- add binstall check to ci
- adjust msrv of tomls
Unfortunately due to a number of changes in our upstream and our own syntax uses, we have to move our msrv up to 1.79
It'd be nice to support lower versions
Fixes #2378
=> Fix #2378: CLI MSRV and add MSRV to CI

packages/autofmt/src/lib.rs, packages/autofmt/tests/wrong.rs, packages/autofmt/tests/wrong/syntax_error.rsx, packages/autofmt/tests/wrong/syntax_error.wrong.rsx
https://github.com/DioxusLabs/dioxus/issues/2723
In case we have a syntax error during parsing of rsx! we do the following:
- write out error msg to stderr unfortunately we are not able to provide info about the fiel which contains the error.
- stop parsing and returned the onmodified file
As this is done also in other cases (silent continue) these seems to be acceptable
=> This fixes issue https://github.com/DioxusLabs/dioxus/issues/2723

packages/desktop/src/app.rs
fixes [this](https://github.com/DioxusLabs/dioxus/issues/2729)
`app.handle_loop_destroyed` is called after the window is destroyed so it cannot be saved
added another save right before the last window is destroyed
=> desktop app saves window position fix

Cargo.lock, packages/cli/src/cli/config.rs, packages/cli/src/cli/serve.rs, packages/cli/src/serve/mod.rs, packages/cli/src/serve/watcher.rs, packages/cli/src/settings.rs
WSL has issues propagating file modification events to our CLI through the `notify` crate. We use notify's poll watcher to fix this when we detect a WSL host. Additionally, this PR adds a new CLI setting to specify the poll interval as it can consume resources for larger projects.
- WSL detection & Poll Watcher
- `wsl-file-poll-interval` CLI setting
- `--wsl-file-poll-interval=` serve argument
- Slight difference in `dx config set` command usage
- Fixes a bug in CLI settings where writing to `settings.toml` with a non-complete directory structure could fail.
Closes #1867
=> Fix WSL Hot Reload

packages/core/src/hotreload_utils.rs, packages/core/src/nodes.rs
follow-up to [this pull request](https://github.com/DioxusLabs/dioxus/pull/2725)
I'm sorry for bothering, but while looking at other stuff I found I've created a function that already existed. This PR makes use of the old one and deletes the new one. I'll be more careful next time
=> fix issue 1586 followup

.github/workflows/publish.yml, packages/cli/Cargo.toml, packages/cli/src/builder/web.rs
passes wasm-opt to our release action so at least the binstalls have the feature enabled
=> speed up incremental cli builds by making wasm-opt optional

Cargo.lock, packages/desktop/Cargo.toml, packages/html/Cargo.toml
Simply disable the async-std feature on rfd in favor of tokio. We already import tokio in our graph, so it's a free dependency.
RFD doesn't give you great options - either you need an async runtime or you need to use gtk3. We should consider refactoring their stuff to give you a req/res approach (similar to how wry gives us async protocols) such that an async runtime is not required.
Fix #2309
=> Fix #2309: rfd doesn't need async-std

packages/core-macro/src/props/mod.rs, packages/core/src/properties.rs, packages/core/src/root_wrapper.rs, packages/core/src/suspense/component.rs, packages/rsx/src/component.rs
This PR switches to using the actual name of the component function in the type system instead of the stringified version of the function we see in rsx
Fixes #2743 
Fixes #2624
=> Fix component names when they are re-exported

packages/rsx/src/element.rs, packages/rsx/tests/hotreload_pattern.rs
Spreads did not have an element name assigned which caused a panic in hot reloading if the project contained a spread
=> Fix hot reloading spreads

packages/cli/src/cli/autoformat.rs
Adds `dx fmt -p my_package` and `dx fmt --package my_package` to specify formatting a package in a Cargo workspace.
Fixes https://github.com/DioxusLabs/dioxus/issues/1547
This uses the new workspace logic in `DioxusCrate` to get the path to a specific package in a workspace. Maybe we should split up `DioxusCrate` into smaller parts here eventually instead of re-using it entirely?
=> Workspace support for `dx fmt`

packages/rsx/src/ifmt.rs, packages/rsx/src/node.rs, packages/rsx/src/text_node.rs
=> Fix: #1964: Use the correct to-static impl for sending escaped strings via hotreload

Cargo.lock, packages/html/src/events/animation.rs, packages/html/src/events/clipboard.rs, packages/html/src/events/drag.rs, packages/html/src/events/focus.rs, packages/html/src/events/form.rs, packages/html/src/events/keyboard.rs, packages/html/src/events/media.rs, packages/html/src/events/mounted.rs, packages/html/src/events/mouse.rs, packages/html/src/events/pointer.rs, packages/html/src/events/scroll.rs, packages/html/src/events/selection.rs, packages/html/src/events/toggle.rs, packages/html/src/events/touch.rs, packages/html/src/events/transition.rs, packages/html/src/events/wheel.rs, packages/web/src/event.rs
Creates `WebEventExt::try_as_web_event` and renames `WebEventExt::web_event` to `as_web_event` (totally open to the naming).
This allows users to downcast event types in a generic way without panics, and simplifies the error reporting in `event.rs`. The methods are also all marked as `#[inline(always)]` which I think is a reasonable tradeoff with such small methods
=> Refactor `WebEventExt`

packages/cli/src/assets.rs, packages/cli/src/builder/cargo.rs, packages/cli/src/serve/builder.rs, packages/cli/src/serve/server.rs
This is an alternative to https://github.com/DioxusLabs/dioxus/pull/2395 with absolute links
Both `/basepath` and `/basepath/` work
Closes https://github.com/DioxusLabs/dioxus/issues/2285
=> Fix the base path in the CLI

packages/core-macro/src/props/mod.rs, packages/core-macro/tests/rsx.rs
Allows automatic `into()` for the default value in props.
```rs
// E.g. instead of 
#[derive(Clone, PartialEq, Props)]
pub struct SomeCoolProps {
#[props(into, default = "abc".to_string())]
pub data: String,
#[props(into, default = true.into())]
pub other_data: u64,
#[props(into, default = true.into())]
pub other_other_data: u16,
}
// you can now do this
#[derive(Clone, PartialEq, Props)]
pub struct SomeCoolProps {
#[props(into, default = "abc")]
pub data: String,
#[props(into, default = true)]
pub other_data: u64,
#[props(into, default = true)]
pub other_other_data: u16,
}
```
Closes #2373
=> Feat: Auto Default Into

Cargo.lock, Cargo.toml, packages/rsx/Cargo.toml, packages/rsx/src/component.rs, packages/rsx/src/element.rs, packages/rsx/src/expr_node.rs, packages/rsx/src/ifmt.rs, packages/rsx/src/lib.rs, packages/rsx/src/literal.rs, packages/rsx/src/text_node.rs, packages/rsx/src/util.rs, packages/rsx/tests/parsing.rs
Move to the published version of prettier-please so we don't need to re-export it into our tests.
=> fix: use prettier-please just in tests - no custom wrapper

packages/html/src/document/eval.rs
Implements the `Error` trait for `EvalError`.
Closes #2766
=> Revision: Make `EvalError` impl `Error`

packages/core/src/scope_context.rs, packages/generational-box/src/lib.rs, packages/signals/docs/hoist/error.rs, packages/signals/docs/hoist/fixed_list.rs, packages/signals/src/copy_value.rs, packages/signals/src/global/signal.rs, packages/signals/src/lib.rs, packages/signals/src/signal.rs, packages/signals/src/warnings.rs
=> Add a warning when a copy value is used in a higher scope than it was created in

packages/desktop/src/hooks.rs, packages/hooks/src/use_callback.rs, packages/hooks/src/use_effect.rs, packages/hooks/src/use_future.rs, packages/hooks/src/use_memo.rs, packages/hooks/src/use_resource.rs
Adds a generic argument to the `use_callback` hook
Fixes #2371
```rs
let f = use_callback(|n| println!("{}", n));
f(0)
```
=> Add argument to `use_callback`

packages/cli/src/serve/output.rs
When there are multiple platforms, the CLI displays the build with the least progress. We were pretending internal logs were a build because it makes them slightly easier to display, but that breaks the progress bar because the internal logs build will never progress. This PR separates internal logs into it's own field
=> Fix fullstack cli progress

packages/core/src/runtime.rs, packages/core/src/suspense/component.rs, packages/core/src/suspense/mod.rs, packages/core/tests/suspense.rs, packages/web/src/lib.rs
Fixes https://github.com/DioxusLabs/dioxus/issues/2783
=> Fix suspense diffing

packages/rsx/src/template_body.rs
I'm not exactly sure why, but putting the release version of rsx first breaks autocomplete. Maybe the span being used in an inactive part of rsx first links autocomplete to that part the rsx?
=> Fix autocomplete in rsx

packages/core-macro/src/props/mod.rs
This PR fixes a regression in props where we don't recognize `Option<&'static str>` as an optional prop breaking this example:
```rust
#[derive(Props, Clone, PartialEq)]
pub struct IconProps {
pub icon: crate::icons::IconKind,
pub class: Option<&'static str>,
pub onclick: Option<EventHandler<MouseEvent>>,
}
```
=> Fix Option<T> with non path T types

packages/desktop/src/protocol.rs
This fixes the issue #2817
I've just added the Access-Control-Allow-Origin header to all assets returned by dioxus, the same way it is done for the index request. 
This removes the problem with Webview2 blocking some local assets due to CORS policy violation.
=> adding the Access-Control-Allow-Origin header to assets

packages/autofmt/src/prettier_please.rs, packages/autofmt/src/writer.rs, packages/autofmt/tests/samples.rs, packages/autofmt/tests/samples/asset.rsx, packages/autofmt/tests/samples/prop_rsx.rsx, packages/extension/package.json
Fix #2806 
We were only looking for brace macro replacements which doesn't work if you have non-brace delimiters for your macro.
Now we just transform all nested `rsx!()` calls to `rsx!{}`
=> Fix non-brace delimeters in nested macro formatting

packages/cli/src/serve/mod.rs, packages/cli/src/serve/server.rs, packages/cli/src/serve/watcher.rs
This PR restores some logic from the previous version of hot reloading that stores any hot reload changes since the last full rebuild and sends them when a new client connects
=> Apply any queued hot reload changes when the client connects

Cargo.lock, packages/core/src/hotreload_utils.rs, packages/hot-reload/Cargo.toml, packages/hot-reload/src/client.rs, packages/rsx/src/hot_reload/diff.rs, packages/rsx/tests/hotreload_pattern.rs
The hot reloading code was collecting hot reloading literals for component in the order of the sorted fields instead of the order of the original component. That caused this code snippet to fail because the values for the bool and string attributes are swapped and the types fail to match
```rust
fn main() {
dioxus_logger::init(tracing::Level::DEBUG).unwrap();
launch(app);
}
rsx!{
Router::<Route> {}
}
}
#[derive(Clone, PartialEq, Routable)]
pub enum Route {
#[route("/")]
Homepage,
#[route("/hello")]
Testing,
}
#[component]
fn Homepage() -> Element {
rsx!{
Link {
to: "https://google.com",
new_tab: true,
class: "block text-gray-400 hover:text-gray-500 dark:hover:text-gray-300",
"hello"
}
}
}
#[component]
fn Testing() -> Element {
rsx!{
"Testing" …
```
=> Fix hot reloading component properties out of order

Cargo.lock, Cargo.toml
Fix for Issue #2833. 
This adds a version number to the `[package]` section of the `Cargo.toml`, which resolves the issue.
Admittedly, not the best solution, given that the version number there and in the `[workspace]` section will have to be kept in sync. I looked around for a better one and couldn't find it, but I'm very open to suggestions.
=> Add version number to package section of Cargo.toml to fix issue #2833

packages/cli/src/serve/watcher.rs
The rust file may have failed to parse, but that is most likely because the user is in the middle of adding new code. Instead of rebuilding we should just ignore the error and let Rust analyzer warn about the problem
=> Don't rebuild when the code is in an invalid intermediate state

packages/autofmt/src/lib.rs, packages/autofmt/src/prettier_please.rs, packages/autofmt/src/writer.rs, packages/autofmt/tests/samples.rs, packages/autofmt/tests/samples/collapse.rsx
These two cases were annoying me but are now fixed.
Just random regressions that slipped through with the refactor/cleanup.
This was getting collapsed:
```rust
Fragment {
Fragment {
Fragment {
Fragment {
Fragment { 
div { "Finally have a real node!" } 
}
}
}
}
}
```
We were randomly injecting more spaces than we should have
```rust
return rsx!();
return rsx!(  );
```
There's still a few more issues I'm not addressing here:
```
// this is getting collapsed to one line when I'd rather it not - all closures should force a newline
FancyButton { 
onclick: move |event| println!("Clicked! {event:?}"), 
}
// we're just eating comments completely with empty
rsx! {
// please dont kill me :/
}
// we're also eating trailing comments, which I thought we fixed. Sometimes it saves them but with wrong …
```
=> fix collapsing of multiline components and rsx!{} calls

packages/cli/assets/toast.html
Makes the cli toasts fixed so they follow the page as the user scrolls and increases the z-index to a reasonable 10 so that it overlays on top of most content.
=> Fix: Make Toast Fixed & Increase Z-Index

examples/global.rs, packages/hooks/src/use_future.rs, packages/hooks/src/use_resource.rs, packages/rsx/src/template_body.rs, packages/signals/src/copy_value.rs, packages/signals/src/global/memo.rs, packages/signals/src/global/mod.rs, packages/signals/src/global/signal.rs, packages/signals/src/impls.rs, packages/signals/src/map.rs, packages/signals/src/memo.rs, packages/signals/src/read.rs, packages/signals/src/read_only_signal.rs, packages/signals/src/signal.rs
Instead of `GlobalSignal<T>` and `GlobalMemo<T>`, this PR switches to `GlobalLazy<T>`. This should make the explanation of moving around state a bit simpler and more unified in the new docs. I don't care too much about the name, but `Lazy` might be too generic because of once cell and tokio lazy
=> Move to a generic GlobalLazy<T>

packages/autofmt/src/lib.rs, packages/autofmt/src/writer.rs, packages/autofmt/tests/samples.rs, packages/autofmt/tests/srcless.rs, packages/autofmt/tests/srcless/basic_expr.rsx, packages/core/src/hotreload_utils.rs, packages/core/src/nodes.rs, packages/hot-reload/src/lib.rs, packages/hot-reload/src/ws_receiver.rs, packages/web/src/hot_reload.rs
Code generators don't always have a srcfile, and in many places, we were indexing the srcfile looking for whitespace.
This fixes that by properly guarding against empty src files in a number of places.
=> fix autofmt: don't panic when writing blocks out without a srcfile

packages/desktop/Cargo.toml
Hello,
On Linux (with `nightly-x86_64-unknown-linux-gnu` toolchain) desktop platform, it seems that the webview events are not deserialized properly by wry. For example, the following error is displayed each time I click on a button: `Error parsing user_event: Error("EOF while parsing a value", line: 1, column: 0)`
After investigating, wry doesn´t deserialize the body of the IPC requests if the `linux-body` feature flag is not set (cf. https://github.com/tauri-apps/wry/blob/wry-v0.41/src/webkitgtk/web_context.rs#L322).
the fix could to enable the `linux-body` feature flag for `linux` target os.
Then, the issue seems to cause `headless_tests` to crash on Linux:
```
cargo test --test check_events
warning: dioxus-cli-config@0.6.0-alpha.2: A library is trying to access the crate's …
```
=> Fix `Error parsing user_event: Error("EOF while parsing a value", line: 1, column: 0)`

packages/core/src/suspense/component.rs, packages/rsx/src/ifmt.rs, packages/rsx/src/literal.rs, packages/rsx/src/rsx_block.rs
=> Fix: clippy, dont throw error on commas

Cargo.lock, packages/interpreter/Cargo.toml, packages/interpreter/src/write_native_mutations.rs
This PR bumps sledgehammer to 0.6.0 which removes the LRU dependency from the tree. Sledgehammer already had a hand rolled LRU for const pointers, the new release just expands the LRU for more types
=> Bump sledgehammer

packages/router-macro/src/lib.rs, packages/router-macro/src/nest.rs, packages/router-macro/src/redirect.rs, packages/router-macro/src/route.rs, packages/router-macro/src/segment.rs
This removes some yellow squiggles present in workspaces/crates that build with
```
[workspace.lints.rust]
missing_docs = "warn"`
```
I don't feel that I'm familiar enough with the structure of these enums to suggest real doc comments, so I just tossed in placeholders. Would love to see some more descriptive text replace the TODOs.
Another option for resolving the warnings would be to replace all the placeholders with an `#[allow(missing_docs)]` attribute added above the two `quote!`d `pub enum`s on lib.rs:689 and segment.rs:300
=> Add placeholder doc comments to macro-generated enums

flake.lock, flake.nix
- #2547 introduced a change that broke the devShell on macOS
- Also update nixpkgs & rust-overlay so we get newer Rust compiler that is needed to compile `dioxus-cli`.
Tested using `nix develop -c cargo build -p dioxus-cli` which produces a functioning `target/debug/dx`
=> Restore Nix devShell support

README.md
Fixes the running examples section of the readme and adds a note about examples for the stable version of dioxus
Fixes #2814
=> Finish the running examples section of the readme

packages/rsx/src/assign_dyn_ids.rs, packages/rsx/src/attribute.rs, packages/rsx/src/component.rs, packages/rsx/src/element.rs, packages/rsx/src/hot_reload/diff.rs, packages/rsx/src/template_body.rs, packages/rsx/tests/hotreload_pattern.rs
We were adding `key`s from component to the component literal pool which caused indexing issues because keys don't show up as props
Fixes #2881
=> Fix hot reloading components with keys

packages/desktop/src/config.rs, packages/desktop/src/webview.rs
This example currently shows the default menu even though the menu is explicitly set to None:
```rust
use dioxus::{desktop::WindowBuilder, prelude::*};
fn main() {
let window = WindowBuilder::new()
.with_always_on_top(false)
.with_resizable(false)
.with_title("Marionette");
let config = dioxus::desktop::Config::new()
// The menu is set here
.with_menu(None)
// But then reset to the default here
.with_window(window);
let launcher = LaunchBuilder::new().with_cfg(config);
launcher.launch(app);
}
rsx! {
"hello world"
}
}
```
This PR fixes that issue
=> Fix ordering issues when with_menu(None) is called before setting the window builder

Cargo.lock, Cargo.toml, examples/backgrounded_futures.rs, examples/clock.rs, examples/control_focus.rs, examples/eval.rs, examples/future.rs, examples/signals.rs, examples/streams.rs
Proposal for https://github.com/DioxusLabs/dioxus/issues/2908 issue. Replacing tokio allows the following examples to run on wasm platforms:
- backgrounded_futures
- clock
- control_focus
- eval
- future
- signals
- streams
What about the documentation?
=> Use of `async_std::task::sleep` instead of `tokio::time::sleep` in examples

examples/clock.rs
Make the clock example work on the web platform (`tokio::time::sleep` doesn't work on `wasm32-unknown-unknown` platform).
=> Fix clock example (` tokio::time::sleep` -> `async_std::task::sleep`)

packages/fullstack/examples/router/src/main.rs, packages/router-macro/src/lib.rs, packages/router-macro/src/route_tree.rs, packages/router-macro/src/segment.rs, packages/router/tests/parsing.rs
The router currently accepts `/path/` if you try define the route `route("/path")`, but it doesn't accept `/path` if you define the route `route("/path/")`. This PR accepts both variants and adds more tests for parsing
=> Parse trailing route slash

packages/check/src/check.rs, packages/check/src/issues.rs, packages/check/src/metadata.rs, packages/core/src/scope_context.rs
Fixes `dx check` for this code snippet:
```rust
if use_signal(|| true) {
println!("123")
}
match use_signal(|| true) {
true => println!("false"),
false => println!("true")
}
```
And report errors for this code snippet:
```rust
use_hook(|| use_signal(|| 0));
spawn(async move { use_signal(|| 0) });
```
=> Allow hooks in the expression of a match statement and if statement

packages/dioxus/src/launch.rs
Fixes #2909 and adds an example to prevent regressions in the future
=> Fix custom launch builder with unsized context types

packages/html/src/elements.rs
[fieldset](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset#attributes) is supposed to have `disabled`, `form` and `name` attributes.
=> add `disabled`, `form` and `name` attributes to fieldset

.github/workflows/nix.yml
This will build all flake outputs (using [omnix](https://omnix.page/om/ci.html)). It will also run `cargo build` inside the Nix devShell to make sure that it works, since that seems to be our primary intended use case of Nix in this repo.
=> ci: Add workflow for building `flake.nix`

README.md
Dioxus now supports suspense with streaming, so this is no longer a useful point of comparison
https://github.com/DioxusLabs/dioxus/pull/2365
=> Remove mention of suspense/streaming in readme comparison

examples/todomvc.rs
* Removes the unused `id` field from `TodoItem` to reduce the total memory stored in the `HashMap`
* Removes derived traits from `TodoItem`
=> Simplify TodoMVC example

packages/cli/src/cli/bundle.rs
This PR fixes two panics that are currently causing `dx bundle` to fail:
1) the bundle command uses `package` twice
2) the bundle command uses resources and resources_map which causes a panic in tauri bundler
Fixes https://github.com/DioxusLabs/dioxus/issues/2941
=> Fix dx bundle command and resources panic

examples/errors.rs, packages/core/src/error_boundary.rs, packages/core/src/events.rs, packages/core/src/fragment.rs, packages/core/src/global_context.rs, packages/core/src/runtime.rs, packages/core/src/scope_context.rs, packages/core/src/virtual_dom.rs, packages/fullstack/src/hooks/server_cached.rs, packages/fullstack/src/hooks/server_future.rs, packages/hooks/src/use_collection.rs, packages/hooks/src/use_coroutine.rs, packages/router/examples/simple_routes.rs, packages/router/tests/parsing.rs, packages/rsx/src/lib.rs, packages/rsx/tests/hotreload_pattern.rs, packages/rsx/tests/parsing.rs, packages/signals/src/write.rs, packages/web/examples/hydrate.rs, packages/web/tests/hydrate.rs
Switch from `rsx!{` to `rsx! {` in a number of places.
`dx fmt` re-formats this, so I just wanted to cut it out of #2779 to try and shrink that diff a bit.
=> small style tweak: make spacing cosnsistent for uses of `rsx! {`, switch `todo!()` to `unimplemented!()`

.github/workflows/nix.yml
Skips running the new Nix CI for draft and other minimal PRs (using the same config as the main CI).
My fault I might've merged that Nix PR too soon, I forgot GitHub doesn't skip drafts and other minor changes by default.
=> Skip running Nix CI for draft PRs

packages/web/src/cfg.rs, packages/web/src/dom.rs, packages/web/src/hydration/hydrate.rs
Can mount the Dioxus component into every node.
As `Element` and `ShadowRoot` are `Node` we can
now mount a Dioxus component into a shadow root.
Implements #3011
=> feat(web): using `None` instead of `Element`

examples/README.md, packages/desktop/build.rs
Since the File Explorer example moved from `examples` to `example-projects`, I think these lines should be removed?
=> File explorer example was moved from `examples` to `example-projects`. Update related files. 

packages/router-macro/src/lib.rs
=> Use the absolute path for result in the router macro

packages/core/src/global_context.rs
Partially(or fully?) addressing https://github.com/DioxusLabs/dioxus/issues/3002
Basically added the important info about use_drop to the doc.
Preview
=> improve `use_drop` documentation

examples/popup.rs, packages/hooks/src/use_coroutine.rs, packages/hooks/src/use_future.rs
This PR changes `use_coroutine` to re-use the stale closure and restart logic from `use_future`. `use_coroutine` is now just a version of `use_future` that creates a channel for you and adds itself through the context API
Fixes #3004
=> Fix restarting coroutines

Cargo.lock, packages/rsx-rosetta/Cargo.toml, packages/rsx-rosetta/src/lib.rs, packages/rsx-rosetta/tests/escape.rs
Fixes https://github.com/DioxusLabs/dioxus/issues/3037
=> Escape HTML entities in rsx rosetta

Cargo.lock, packages/cli/Cargo.toml, packages/cli/src/cli/translate.rs
It is no longer maintained and has been replaced by functionality in the
stdlib (std::io::IsTerminal).
Removes two warnings from cargo-audit for being unmaintained and being
[potentially unsound](https://rustsec.org/advisories/RUSTSEC-2021-0145.html).
=> Remove dependency on atty

.github/ISSUE_TEMPLATE/bug_report.md
The current bug report formatting conflicts slightly with GitHub's integration for task lists:
This replaces the checkboxes with lines commented-out and instructions.
=> Update bug report format

Cargo.lock, Cargo.toml
This bumps manganis pre-release to it's alpha.2 release, which is needed for us to release the next pre-release
=> Bump manganis prerelease to alpha.2

packages/fullstack/README.md
fix https://github.com/DioxusLabs/dioxus/issues/3070
=> fix fullstack doc

packages/desktop/src/hooks.rs
Captures the current scope during  `use_muda_event_handler` and later enters it with `Runtime::on_scope` to allow for functions like `dioxus::spawn` in the event handler.
Fixes https://github.com/DioxusLabs/dioxus/issues/3119
=> Capture current scope ID in `use_muda_event_handler`

packages/cli/src/builder/build.rs
Fixes the conflict of CLI providing `--release` and `--profile something` to Cargo, which isn't allowed. This fix makes `--release` have priority.
Re-implements functionality of #3078 since it was accidentally overwritten.
=> Fix: CLI Release & Profile Conflict

packages/web/src/lib.rs
in web/src/lib there is a line that says "Starting up" to the browser console. This is leaking information about server file structure. 
Related: https://github.com/DioxusLabs/dioxus/issues/3117
=> fix: :lock: removed the line that exposes file structure of web server

packages/cli/Dioxus.toml, packages/cli/README.md, packages/cli/src/config/app.rs, packages/cli/src/config/dioxus_config.rs
Removes the `default_platform` field in `Dioxus.toml` in favor of using default `Cargo.toml` features.
=> Remove: `default_platform` in `Dioxus.toml`

packages/cli/src/builder/build.rs
If you have a default platform in your `default` feature and want to specify a different platform with the `--platform` flag, the original feature would still be enabled.
=> Fix: CLI Not Applying `no-default-features` When Specifying Platform

packages/cli/src/serve/runner.rs
Fixes: https://github.com/DioxusLabs/dioxus/issues/3141
I think this is because some editors might use `.bk` files but I'm not exactly sure why a file wouldn't show up.
I can't replicate this locally on my mac.
=> fix: don't panic while reading file in hotreload

packages/dioxus/src/launch.rs, packages/liveview/src/launch.rs
The liveview launch function was still using the old launch API. This PR fixes that issue
=> Fix liveview launch

packages/desktop/src/protocol.rs
Remove debug printlns
Changes made:
- Removed leftover debug `println` statements from `protocol.rs` module.
- These are unsuitable for production environments.
=> Remove debug printlns

packages/core/src/nodes.rs
It is quite annoying to have some number types implemented [IntoAttributeValue](https://docs.rs/dioxus/0.6.0-alpha.4/dioxus/prelude/trait.IntoAttributeValue.html) while some didn't.
=> complete implementation of IntoAttributeValue for number types

packages/web/src/events/animation.rs, packages/web/src/events/clipboard.rs, packages/web/src/events/composition.rs, packages/web/src/events/drag.rs, packages/web/src/events/focus.rs, packages/web/src/events/keyboard.rs, packages/web/src/events/media.rs, packages/web/src/events/mounted.rs, packages/web/src/events/mouse.rs, packages/web/src/events/pointer.rs, packages/web/src/events/resize.rs, packages/web/src/events/selection.rs, packages/web/src/events/toggle.rs, packages/web/src/events/touch.rs, packages/web/src/events/wheel.rs
https://github.com/DioxusLabs/dioxus/pull/3137 made as_any return the inner event directly instead of the synthetic event, but the as_web_event implementation of many events were still trying to downcast to the synthetic version of the event. This PR changes the as_web_event implementation for all events to always downcast to the web-sys version of the event directly
Fixes https://github.com/DioxusLabs/dioxus/issues/3177
=> Fix as web event

packages/cli/src/builder/bundle.rs
CLI did not add `.exe` extension to the `server` file copied to the target-dist folder.
=> Fix: CLI Fullstack Executable File Extension

packages/cli/src/build/request.rs, packages/cli/src/build/verify.rs, packages/cli/src/dioxus_crate.rs
No longer hardcodes the internal android linker and instead uses the system's installation if available.
=> fix: autodetect android install

packages/core/src/runtime.rs, packages/core/src/scheduler.rs
Fixes #3196 by removing effects queued for the scope as the scope itself is removed
=> Don't run effects from dead recycled scopes

packages/desktop/src/app.rs, packages/desktop/src/config.rs, packages/desktop/src/launch.rs
I was trying to write an application that has a combination of Dioxus & OpenGL windows but that was made impossible by the fact that the only way to create multiple windows is by creating windows with WebViews.
Having the ability to manually provide an event loop should allow user to create as many windows as they want before the dioxus window start, and allow more flexibility.
Custom event handlers were implemented to allow the handling of events generated by the manually created windows.
=> Add support for user-provided event loops & event handlers

example-projects/ecommerce-site/src/components/loading.rs, example-projects/ecommerce-site/src/main.rs, example-projects/file-explorer/src/main.rs, example-projects/fullstack-hackernews/src/main.rs, examples/calculator_mutable.rs, examples/crm.rs, examples/read_size.rs, examples/resize.rs, packages/document/src/elements/link.rs, packages/document/src/elements/script.rs, packages/manganis/manganis-core/src/asset.rs, packages/manganis/manganis-macro/src/asset.rs, packages/manganis/manganis/src/builder.rs
We currently don't support relative asset paths ie `asset!("./assets/blah.css")` but previously we instructed users to use that syntax since the "relative" portion is relative to the crate root.
However, in practice, we can only allow "absolute" paths like `/assets/blah.css` since, when publishing the crates.io, we need to force all assets to live under the `assets` folder *within the crate*.
We made this change in the last alpha, but did not deprecate the old syntax.
In the future we plan to properly support relative paths (ie relative to the current file) so the old syntax will conflict.
This cleans up errors with missing assets as well as adds a new_relative method to asset that the macro now uses to signal the deprecation warning.
=> Deprecate relative asset paths, better warnings for asset!()

packages/cli/src/build/bundle.rs, packages/cli/src/cli/run.rs
We weren't giving SSG enough time to complete which made some pages not finish before we killed the server.
In the future we should have some better signaling system that doesn't necessarily require us to set up ssg.
Perhaps a server function itself could internally drive the router and only respond success if the site generates successfully?
Anyways, fixes that and also has better logging for web apps when launching from `dx run`
=> fixes: light qol fixes for ssg and logging on `dx run`

packages/cli/src/build/bundle.rs, packages/cli/src/build/request.rs, packages/cli/src/build/verify.rs, packages/cli/src/cli/build.rs, packages/cli/src/cli/bundle.rs, packages/cli/src/cli/run.rs, packages/cli/src/cli/serve.rs, packages/cli/src/cli/target.rs, packages/cli/src/dioxus_crate.rs, packages/cli/src/serve/mod.rs
Adds support for specifying an Android target arch with the `--arch` flag. If no `--arch` flag is included, the CLI will attempt to automatically detect the arch using `adb` and if that fails, the arch defaults to Arm64.
=> Feat: Android Dynamic Arch Support

packages/cli/src/build/bundle.rs, packages/cli/src/cli/build.rs, packages/fullstack/src/render.rs
Instead of always purging debug symbols unless the dioxus.toml is set, expose a flag that allows you to disable symbols.
Also change the format of ssg to be Vec<String> for the static routes instead of String to make it easier to teach the static_routes server function.
=> feat: add keep-symbols flag, change ssg format to Vec<String>

packages/manganis/manganis-macro/src/asset.rs
Windows has different behavior for the `path.is_relative()` method than unix. This switches out that method for `path.starts_with("/")`
=> Fix: Asset Warnings On Windows

packages/web/src/events/form.rs
Demo app to prove this change:
```rust
use dioxus_logger::tracing::{info, Level};
use dioxus::web::WebEventExt;
fn main() {
dioxus_logger::init(Level::INFO).expect("failed to init logger");
info!("starting app");
launch(App);
}
#[component]
fn App() -> Element {
rsx! {
input {
type: "file",
onchange: move |evt| {
info!("onchange");
if let Some(evt) = evt.try_as_web_event() {
info!("web event");
}
},
}
}
}
```
Before my change, selecting a file would only log "onchange". After my change you get both "onchange" and "web event" as you would expect.
I suspect this is a parallel problem to https://github.com/DioxusLabs/dioxus/pull/3137 and possibly needs to be updated in more places as well.
=> fix the downcast for formdata try_as_web_event

packages/cli/src/assets.rs, packages/cli/src/build/request.rs, packages/cli/src/cli/link.rs
it came to me in a dream...
instead of intercepting the linker, simply traverse the `deps` and `incremental` directories for their artifacts.
This drastically speeds up asset bundling times and is much nicer when used with LTO since we are basically forced to compile twice with LTO.
This is also generally better for folks who run `cargo check` with our profiles wrt cache thrashing.
Fixes: #3148
=> feat: traverse the target directory instead of intercepting the linker to collect assets

packages/dioxus/src/launch.rs
set the endpoint url to 10.0.2.2 to follow loopback config for android emulator
=> fix android serverfns

packages/cli/src/serve/mod.rs, packages/cli/src/serve/runner.rs
The CLI fails to write the new executable on Windows because the old one is still running during rebuilds.
This PR introduces a `kill_all()` method on the `AppRunner`. Ideally, the app would be killed right before the bundler starts, but I wasn't sure how to best get a handle down to the bundler. Instead, I opted for this simpler, but perhaps slightly less DX solution (since the app is closed during rebuilds and the dev can't admire their desktop app or interact with serverfns).
=> Fix: CLI Windows Write `exe` Errors

packages/interpreter/src/unified_bindings.rs, packages/web/src/dom.rs, packages/web/src/lib.rs
Fixes #2926
I fixed the issue by removing Interpreter::mount_to_root because its implementation either does nothing or throws the type error, effectively making it dead code.
`mount_to_root` had passed `Node` instead of `NodeId` to `appendChildren(id: NodeId, many: number)`.
=> Fix hydration race condition

packages/rsx-hotreload/src/diff.rs
Hot reloading diffing counted any event handlers with identical tokens as identical, but that is not true if they are used on different events. The event function influences the type of the event handler closure, so we cannot hot reload moving an event handler closure from one event to another
Fixes https://github.com/DioxusLabs/dioxus/issues/3268
=> Fix hot reloading identical event handler closures

packages/cli/src/assets/file.rs
The CLI asset handling uses the `PathBuf::extension` method to determine if an asset is a folder. The problem is that this method works off of the `.` in file/folder names and would evaluate the extension is `52` for the folder name `monaco-editor-0.52`, treating it as a singular file.
=> Fix: Legacy Folder Assets With `.` In Name

packages/core/src/error_boundary.rs, packages/core/src/events.rs, packages/core/src/nodes.rs, packages/core/src/scope_arena.rs, packages/core/src/suspense/mod.rs
This PR fixes diffing after hot reloading the rsx inside of the resource in the dog app example. The resource was returning a cloned version of the rsx from the previous run which was mounted. We should never have mounted VNodes in components so that cloning VNodes works as expected. This PR fixes the issue by performing a deep clone of the VNode before diffing so the version of the vnode that lives in diffing/core doesn't share the same `Cell<Mount>` as the version of the vnode that lives in the component.
=> Fix diffing cloned rsx nodes by deep cloning nodes before mounting them

Makefile.toml, examples/router.rs, packages/fullstack/README.md, packages/fullstack/docs/request_origin.md, packages/fullstack/src/serve_config.rs, packages/fullstack/src/server/mod.rs, packages/fullstack/src/server_context.rs, packages/manganis/manganis-core/src/images.rs
A few fullstack examples were not being tested and had become out of date with the current version of fullstack. This PR fixes that issue and tests them in CI
=> Fix fullstack axum integration docs

Cargo.lock, packages/cli/Cargo.toml, packages/cli/src/build/bundle.rs, packages/cli/src/config/web.rs
wasm-bindgen now moved reference types to a -C flag which can be set via rustflags, so we no longer need to manually support it.
=> drop reference types due to deprecation, pin browserlist (fix ci)

packages/dx-wire-format/src/lib.rs
This allows consumers of `dioxus-dx-wire-format` to use the same types, avoiding any version mismatches.
=> Feat: Re-Export `cargo_metadata` In `dioxus-dx-wire-format`

example-projects/fullstack-hackernews/src/main.rs, packages/fullstack/src/render.rs, packages/fullstack/src/serve_config.rs, packages/playwright-tests/fullstack/src/main.rs, packages/playwright-tests/nested-suspense/src/main.rs, packages/playwright-tests/suspense-carousel/src/main.rs
This PR makes the out of order streaming option optional to allow fullstack sites to support content loading without javascript. All of the playwright tests are still running with out of order streaming mode enabled because that is the more difficult case to get right
Closes https://github.com/DioxusLabs/dioxus/issues/3276
=> Expose streaming options to choose between full prerendering and out of order streaming

Cargo.lock, packages/cli-opt/Cargo.toml, packages/cli-opt/src/css.rs, packages/cli-opt/src/file.rs, packages/manganis/manganis/src/macro_helpers.rs
Adds basic SCSS/SASS support to Manganis.
=> Feat: Manganis SCSS Support

packages/cli/src/build/builder.rs
Using `dx build`, when Cargo fails, it early returns and doesn't process any remaining `BuildUpdate`s in the channel. This change flushes any `BuildUpdate::CompilerMessage` in the `BuildFailed` handler so that logs are outputted correctly.
=> Fix: Flush Cargo Logs on Build Failure

packages/autofmt/src/writer.rs, packages/autofmt/tests/samples/attributes.rsx, packages/autofmt/tests/srcless.rs, packages/autofmt/tests/srcless/asset.rsx, packages/autofmt/tests/srcless/basic_expr.rsx
Autofmt was returning the same expression every time when being used for codegen (IE on the docsite) and some documentation was just wrong.
Apparently our "spanless" test was actually generating spans and thus we weren't catching it.
If the span is unreliable (in this case, row=1, col=0), then we shouldn't cache it at all.
This fixes that, fixing some docs.
=> fix: never cache spanless expressions in autofmt

packages/cli/src/build/bundle.rs, packages/cli/src/build/progress.rs, packages/cli/src/cli/create.rs, packages/cli/src/dioxus_crate.rs, packages/cli/src/logging.rs, packages/cli/src/serve/output.rs, packages/desktop/src/app.rs, packages/dx-wire-format/src/lib.rs
- Add gradle status message
- Use cargo.toml for profiles, not .config/cargo.toml
- hide `dx_src` from logs when not running `--verbose` for build/bundle etc
- don't float desktop windows by default
=> feat: some simple UI tweaks to CLI

packages/fullstack/src/serve_config.rs, packages/manganis/manganis-macro/src/lib.rs
Fixes a typo in the enable_out_of_order_streaming documentation and removes the remote example from the manganis macro documentation
Closes #3316
=> Fix enable_out_of_order_streaming doc example and manganis macro remote example

packages/cli/src/serve/handle.rs
Manganis' asset manifest uses canonicalized assets and Windows may use the long-form path instead of regular `C:\`
=> Fix: Windows Manganis Asset Hot Reload

packages/cli/src/serve/handle.rs, packages/cli/src/serve/mod.rs, packages/cli/src/serve/runner.rs, packages/desktop/src/protocol.rs
This fixes android asset hot-reloading. We were running into permissions issues earlier that I realized don't exist with the `tmp` directory.
https://github.com/user-attachments/assets/1c945758-422b-4d4f-937e-a0f6484b594a
=> feat: android asset hotreloading

packages/web/src/devtools.rs, packages/web/src/lib.rs
The websocket handler for the devtools uses `eval` to run javascript that creates the toast without entering explicitly entering the runtime. This sometimes worked if the scheduler happened to already be in the runtime, but it can panic randomly if that is not the case
=> Always run toast eval inside the runtime

packages/cli/src/build/progress.rs, packages/cli/src/build/request.rs, packages/cli/src/serve/output.rs
I noticed in https://github.com/DioxusLabs/dioxus/issues/3298 that many users are running into opaque cargo issues because we're swallowing cargo's output in some scenarios.
Apparently most build errors aren't covered by any of the cargo metadata variants:
https://github.com/oli-obk/cargo_metadata/issues/168
This implements some basic heuristics to discover when cargo is emitting TextLine messages that are actually errors and ensures those make it to the user.
=> fix: print `error: ` messages and their contents from cargo

packages/liveview/src/adapters/axum_adapter.rs, packages/liveview/src/history.rs
This PR fixes the prevent default behavior of Links in liveview. Without this change, every link requires a full page reload.
=> Fix client side liveview links

Cargo.lock, Cargo.toml, packages/cli/Cargo.toml, packages/cli/src/build/bundle.rs, packages/cli/src/build/request.rs, packages/cli/src/cli/bundle.rs
- Removes walrus from our deps since we don't need it anymore
- Changes .unwrap() to let-else 
- Annotates some final `.unwrap()` calls as `.expect`
=> Fix: unwraps while ignoring log lines

packages/cli/src/serve/output.rs
I built a test setup for the viewport in a different repo - and then found the actual issue (an additional clamp we didn't need).
Not going to integrate the test suite here since it's a bit useless once you have the math figured out.
https://github.com/jkelleyrtp/viewport-frame-size
=> Fix space remaining (again)

examples/custom_assets.rs, packages/manganis/manganis-macro/src/asset.rs
While working on the docsite I found that if you passed `asset!("")` on accident, then we'd end up copying the entire current directory over. This is not good. It also causes new `dx serve` to hang infinitely since we get stuck on clearing the assets dir.
This fixes that by throwing an error if the path is empty and ensuring the final path is a child of the crate.
=> fix: throw error when asset is empty

packages/cli/src/build/request.rs, packages/fullstack/src/hooks/server_future.rs
If `cargo build` ends in a weird state, we were previously swallowing logs (which has been fixed).
However, we should still point people to enabling trace mode in these cases since there might be useful information.
This also removes a latent `info!()` log that isn't helpful.
=> add helpful message for obscure cargo failures

packages/signals/src/read.rs
this PR aligns what the code snippet does with what the comment says it should do (peek and log the *event source*, not the *count value*). It also ensures `count += 1` is done for both buttons, because otherwise only the double button causes a log message.
=> fix peek() example

packages/core/src/diff/node.rs, packages/desktop/headless_tests/events.rs, packages/playwright-tests/fullstack.spec.js, packages/playwright-tests/fullstack/src/main.rs, packages/playwright-tests/liveview.spec.js, packages/playwright-tests/liveview/src/main.rs, packages/playwright-tests/web.spec.js, packages/playwright-tests/web/src/main.rs
Fixes #3343 
The `PartialEq` implementation of Closure was changed from `true` to comparing the closures by pointer and origin in #3271. This was causing the attribute value to be written every time the vnode was diffed with a different closure. However, we don't actually care about the value of the closure when diffing since we reference them by the element they are attached to and the event name. This PR skips diffing event handlers when diffing
It also adds playwright tests for each platform onmounted. Hydration has special logic for onmounted so it is important to test both web and fullstack
=> Fix onmounted event triggering many times

packages/signals/src/warnings.rs
The second example in the help section for reading and writing the same signal in a reactive scope contains the line `count.write(count());` which sets the signal to itself and doesn't make sense for any real app. This PR just sets the signal to a constant instead
=> Improve the second example in the read write same scope warning

packages/web/src/dom.rs
We were using the `Closure<dyn FnMut>` type for the event handling closure. Events can be invoked recursively sometimes which is not allowed with `Closure<dyn FnMut>`. Switching to `Closure<dyn Fn>` fixes the issue
Fixes #2882
=> Fix event closure invoked recursively

packages/isrg/src/memory_cache.rs
=> Don't panic if the duration is negative in try_get_or_insert

packages/cli/src/build/bundle.rs
before this PR:
(note the six `(0/6)`)
```
15.509s  INFO Bundling app...
15.536s  INFO Running wasm-bindgen...
15.790s  INFO Copying asset (0/6): C:\Users\liigo\tmp\hidx06\Bare-Bones\assets\header.svg
15.791s  INFO Copying asset (0/6): \\?\C:\Users\liigo\tmp\hidx06\Bare-Bones\assets\main.css
15.792s  INFO Copying asset (0/6): C:\Users\liigo\tmp\hidx06\Bare-Bones\assets\favicon.ico
15.794s  INFO Copying asset (0/6): \\?\C:\Users\liigo\tmp\hidx06\Bare-Bones\assets\favicon.ico
15.795s  INFO Copying asset (0/6): \\?\C:\Users\liigo\tmp\hidx06\Bare-Bones\assets\header.svg
15.797s  INFO Copying asset (0/6): C:\Users\liigo\tmp\hidx06\Bare-Bones\assets\main.css
19.87s  INFO Copying app to output directory...
```
after this PR:
```
1258.16s  INFO Bundling app...
1258.18s  INFO Running …
```
=> fix copy assets progress by moving fetch_add out of trace!().

Cargo.lock, packages/core/src/effect.rs, packages/core/src/runtime.rs, packages/core/src/tasks.rs, packages/core/src/virtual_dom.rs, packages/playwright-tests/web.spec.js, packages/playwright-tests/web/Cargo.toml, packages/playwright-tests/web/src/main.rs
We currently assume everything except tasks, events, and effects happens while the vdom is rendering. This causes issues with external callbacks in the dom like a scroll handler attached to the window. The rendering flag is used both for warnings and to determine if signals should subscribe to components
This PR fixes those issues by only setting the rendering boolean while rendering and assuming everything else happens when the vdom is not rendering. It also adds a playwright test to check this behavior
Closes #3399
=> Assume the virtual dom is not rendering while not diffing components

packages/cli/src/platform.rs
A user in the discord tried to compile the cli on FreeBSD, but it failed due to nothing being returned inside autodetect_on_cargo_feature due to freebsd not being covered. As they wanted just to compile for web, returning None might work, but maybe an additional check for freebsd and returning Linux might be needed?
=> Return None in autodetect_on_cargo_feature on other platforms

packages/web/src/devtools.rs
=> Keep rebuilding toast alive longer

packages/router-macro/src/lib.rs
Makes the `Routable` derive macro hygienic by wrapping the output in an anonymous scope.
This allows multiple routers to be defined in the same scope if necessary (e.g. for testing purposes, macro generation, etc.).
=> Make `Routable` derive macro hygienic

packages/desktop/src/protocol.rs
In the dynamic path example
```rust
use_asset_handler("logos", |request, response| {
// We get the original path - make sure you handle that!
if request.uri().path() != "/logos/logo.png" {
return;
}
response.respond(Response::new(include_bytes!("./assets/logo.png").to_vec()));
});
rsx! {
document::Link { rel: "stylesheet", href: STYLE }
h1 { "Dynamic Assets" }
img { src: "/logos/logo.png" }
}
}
```
The expected behavior is that because `/logos/logo.png` has first  path segment "logos" that it would match the use asset handler with the name argument of "logos"
except this code
```rust
// todo: we want to move the custom assets onto a different protocol or something
if let Some(name) = request.uri().path().split('/').next() {
if asset_handlers.has_handler(name) {
let …
```
=> Fixed asset path resolver to use the second segment instead of first.

.github/workflows/main.yml
The [cargo-msrv](https://crates.io/crates/cargo-msrv) crate released a new version which does not compile on Rust > 1.81 which breaks our msrv (1.79). This pins cargo-msrv to a fixed version keeping its msrv down.
=> fix: pin cargo-msrv to older version

Cargo.lock, Cargo.toml
Version 0.30.3 of tao includes the fix for the window resize issue on Wayland.
Fixes #3314
=> remove version pin on tao

packages/cli/src/cli/bundle.rs
`hotdog.exe` instead of `hotdog` in directory `target\dx\hotdog\bundle\windows\`
this is one of the steps to fix https://github.com/DioxusLabs/dioxus/issues/3233 ( anothe one is to update dioxus-template, adding bundle.identifier to Dioxus.toml, https://github.com/DioxusLabs/dioxus-template/pull/58 )
=> the main exe to be bundled should have '.exe' extension on windows

Cargo.lock, packages/core/Cargo.toml, packages/core/tests/memory_leak.rs, packages/html/src/events/mod.rs
The event handler into implementation uses the current owner which defaults to the current scope. That causes a memory leak when repeatedly creating new event handlers on the same scope. This PR fixes the issue by overriding the owner to the closure
Fixes #3421
=> Fix the event handler memory leak

packages/cli/src/serve/handle.rs
As described in #3436, not having `adb` in the path (or having other problems with `adb`) fails silently.
The problem here is that the two `adb` commands for installing and starting the app are done on a new tokio background task without logging the result. Errors are propagated to the tasks handle, but the handle is detached and therefore never checked.
I wasn't sure what the best way to handle detached errors in the CLI is, so I went with simply logging errors instead of propagating them. Some open questions remain:
- Should we explicitly add `adb` as requirement in the docs for the [mobile docs](https://dioxuslabs.com/learn/0.6/guides/mobile/)?
- Should we check for system dependencies beforehand for clearer error messages?
Fixes #3436
=> fix(cli): Log errors when `adb` command fails

Cargo.lock, Cargo.toml, example-projects/wifi-scanner/Cargo.toml, examples/fullstack-auth/Cargo.toml, packages/cli-opt/Cargo.toml, packages/cli/Cargo.toml, packages/liveview/Cargo.toml, packages/liveview/examples/axum.rs, packages/liveview/examples/axum_stress.rs
Fixes https://github.com/DioxusLabs/dioxus/issues/3053 by bumping our `futures-*` crates.
Also does some light cleanup on version hosting and uses `dioxus::logger::initialize_default()` instead of pretty_env_logger for the liveview examples
=> fix: bump futures-channel to prevent locked versions from conflicting

packages/web/Cargo.toml
Running `dx serve --fullstack` in fullstack-auth returns several compiler errors:
```
[cargo] error[E0432]: unresolved import `web_sys::DomRectReadOnly`
--> packages/web/src/events/visible.rs:11:28
|
11 | use web_sys::{CustomEvent, DomRectReadOnly, Event, IntersectionObserverEntry};
|                            ^^^^^^^^^^^^^^^ no `DomRectReadOnly` in the root
```
This feature activation of web-sys should resolve the issue.
=> Fix compiler error in examples/fullstack-auth

examples/fullstack-auth/Cargo.toml, examples/fullstack-auth/src/main.rs
Fixes #3363.
The example is served to a hardcoded port 3000, while the cli expects to connect to 8080 by default. Using `dioxus_cli_config::fullstack_address_or_localhost`,  the proper address can be used by the server. This is consistent with the documentation for [dioxus-fullstack](https://github.com/DioxusLabs/dioxus/tree/main/packages/fullstack#axum-integration).
Note that because of the issue fixed in #3359, what works is `dx serve --client-features dioxus-web/mounted --open`, where the `mounted` feature enables the web-sys feature `DomRect`, which enables `DomRectReadOnly`.
=> Get server address from cli in fullstack-auth example. 

packages/cli/src/build/bundle.rs
[I have been experimenting with Dioxus SSG recently](https://github.com/opensass/opensass/pull/22) and noticed that the port number and IP address are hardcoded. The port is set to `9999` instead of retrieving the values from the configuration.
With these changes, the port is now set to the env var value at compile time (defaults to 8080):
```sh
PORT=3000 dx serve --ssg 
```
=> fix(cli): get ip addr & port number from config

Cargo.lock, packages/dioxus-lib/Cargo.toml, packages/dioxus-lib/src/lib.rs, packages/dioxus/Cargo.toml, packages/dioxus/src/lib.rs, packages/signals/src/warnings.rs
feat: Reexport the `Warning` trait in dioxus-signals to allow the use of `::allow()` without pulling the warnings crate
fixes: #3513
=> feat: Reexport the `Warning` trait in dioxus-signals

packages/router/src/routable.rs, packages/router/tests/parent.rs
The `parent` and `is_child_of` methods are currently broken if the route has query or hash segments. This was causing an infinite loop in the docsite with hash fragments in https://github.com/DioxusLabs/docsite/pull/365.
This PR ignores hash segments and query segments when determining the parent/child relationship of routes. It also adds tests for the parent and is_child_of methods
=> Fix Routable::parent with hash segments and query params

Cargo.lock, Cargo.toml, packages/playwright-tests/fullstack-mounted.spec.js, packages/playwright-tests/fullstack-mounted/Cargo.toml, packages/playwright-tests/fullstack-mounted/src/main.rs, packages/playwright-tests/playwright.config.js, packages/web/src/lib.rs, packages/web/src/mutations.rs
The mounted event was not being triggered after hydration when no other edits were queued. This PR fixes that issue and adds a playwright test to prevent regressions
=> Fix mounted event after initial hydration

packages/cli/src/cli/bundle.rs, packages/cli/src/dioxus_crate.rs
This PR expands the error messages when `dx serve` is called at the root of a workspace or library package with suggested fixes
=> Improve error message when dx is called on a virtual or library package

packages/cli/src/cli/bundle.rs
Fix the bug that `dx bundle` fails when no assets are copied report by [#3504](https://github.com/DioxusLabs/dioxus/issues/3504)
=> Fix dx bundle fails when no assets are copied

packages/desktop/src/webview.rs
The `android_runtime_lock` function helps paper over an issue in wry where event handlers are allowed to be ran concurrently across multiple threads even though the API takes single-threaded structures.
We need to lock the mutex when we call "wait_for_work" since that operation might poll async tasks still stuck in the queue.
Fixes #3464
I would like to get tests here at some point but that will require a proper android test harness
=> fix: add additional lock when calling wait_for_work on android

examples/fullstack-streaming/src/main.rs
The fullstack streaming server function example spawns a task that sends values into the channel, but it doesn't quit when the channel closes. This caused the future to keep running even after the client disconnected.
=> Fix the test_stream function running after the stream is closed

Cargo.lock, Cargo.toml, packages/cli/Cargo.toml, packages/cli/src/build/bundle.rs, packages/cli/src/serve/handle.rs, packages/desktop/Cargo.toml, packages/manganis/manganis-macro/Cargo.toml, packages/manganis/manganis-macro/src/asset.rs
**Problem**
Due to Windows' long-form path variants, cached assets were being deleted causing long rebuilds for apps with lots of assets e.g. docsite.
The asset status would jump around a lot in terms of progress.
**Fixes**
We use the `dunce` crate to canonicalize assets in a few places, replacing `fs::canonicalize`. The changes work well on Windows, but it would be good to test other platforms. There may be other places we should canonicalize.
The asset status now tracks the completed assets instead of the current asset.
=> Fix: Asset Cache On Windows & Asset Status

packages/html/src/attribute_groups.rs, packages/html/src/elements.rs, packages/rsx-rosetta/src/lib.rs, packages/rsx-rosetta/tests/svgs.rs
We were accidentally stringifying the attribute literal names for the matching code. This caused us to match `"viewBox"` against `"\"viewBox\""` which caused us to fallback onto "viewBox".
Also strips off namespaces in attributes since HTML-5 generally doesn't include those.
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href
This fixes that and adds a test for it. 
Fixes #3204
Fixes #3212
=> fix: viewBox translation by not accidentally stringifying literals

packages/cli/src/serve/handle.rs, packages/cli/src/serve/runner.rs
Fixes #3295 and Fixes #3477 which was caused by the CLI opening a new instance of the server every time the open shortcut is used
Fixes #3296 which was caused by the CLI trying to close the `Server` platform instead of the platform the server is launched under (generally `Web` or `Desktop`)
=> Fix opening fullstack and server crash logging in the CLI

packages/const-serialize/src/lib.rs
The new edition of rust includes extra checks for [pointer providence](https://rust-lang.github.io/rfcs/3559-rust-has-provenance.html#summary) that caught a bug in const serialize. When serializing an enum with zero sized type variants that still have an alignment of one, const serialize adds the alignment to the pointer before discarding the pointer. This PR fixes the issue by using `wrapping_byte_add` instead which allows the pointer to temporarily point to invalid memory as long as it is never read.
Note while the new release of miri catches this bug, I haven't seen it anywhere in production and if it were to appear it would likely be caught at compile time because const serialize is used in const code
=> Fix pointer provenance in const serialize with zero sized type enum variants

Cargo.lock, packages/cli-opt/Cargo.toml, packages/cli-opt/src/js.rs
Sets the `keep_fn_names` to true in the mangle configuration to unblock the Dioxus Playground.
=> Fix: Enable `keep_fn_names` In SWC Mangling

packages/core-macro/docs/component.md, packages/core-macro/docs/props.md
This PR improves the docs on extending props a bit.
Before it was unclear to me, how one can extend both the global attributes and an element's extension attributes.
The statement `you can use any attribute that would normally appear on the button element` was also a bit misleading, given that the example only extends the global attributes. So I generalized original example to use a div instead of a button.
=> docs: demonstrate extending both global and element attributes

packages/cli/src/dioxus_crate.rs
Resolves https://github.com/DioxusLabs/dioxus/issues/3546
Now, if `bin` param not specified for dx it firstly fallback `default-run` target, secondly to single bin target thirdly to package name.
`default-run` case:
single bin case:
=> fix: cli pakage name search

packages/fullstack/src/render.rs
While this was done correctly in the streaming case, non-streaming suspense resolution didn't recieve the server context.  This meant that anything that required the context after the point of suspension would find it missing.
This resolves #3500
=> Add server context to suspense resolution

packages/rsx/src/expr_node.rs, packages/rsx/src/template_body.rs
We were expanding dynamic nodes and attributes in both the debug and release blocks of the macro. That caused rust analyzer to get confused and not autocomplete expressions. This PR pulls out those items into a shared scope
Fixes #3558
=> Fix rsx expression autocomplete

packages/cli/src/wasm_bindgen.rs
We were accidentally generating typescript files with wasm-bindgen which we don't need to be doing.
Seems to be the only flag we're missing?
```
Usage: wasm-bindgen [OPTIONS] <INPUT>
Arguments:
<INPUT>  
Options:
--nodejs                    Deprecated, use `--target nodejs`
--browser                   Hint that JS should only be compatible with a browser
--web                       Deprecated, use `--target web`
--no-modules                Deprecated, use `--target no-modules`
--typescript                Output a TypeScript definition file (on by default)
--no-typescript             Don't emit a *.d.ts file
--omit-imports              Don't emit imports in generated JavaScript
--out-dir <DIR>             Output directory
--out-name <VAR>            Set a custom output filename (Without …
```
=> fix: don't accidentally generate .d.ts files with wasm-bindgen

Cargo.lock, packages/cli/Cargo.toml, packages/cli/src/build/web.rs, packages/cli/src/cli/bundle.rs, packages/cli/src/config/app.rs, packages/cli/src/config/dioxus_config.rs, packages/cli/src/dioxus_crate.rs, packages/cli/src/fastfs.rs, packages/cli/src/serve/handle.rs
Fix [#3564](https://github.com/DioxusLabs/dioxus/issues/3564)
=> Fix outdir not work when run dx bundle --platform web --outdir mydir

packages/cli/src/cli/run.rs, packages/cli/src/serve/mod.rs, packages/cli/src/serve/runner.rs
In the big CLI rewrite I accidentally removed the code for doing soft-kills on the desktop window.
This fixes that, fixing window state preservation.
Fixes #3355
=> fix: window state preservation by soft-killing the process

packages/desktop/src/app.rs, packages/desktop/src/launch.rs
When resizing a window, Dioxus previously accidentally resized every single webview to the dimensions of the window that just got resized. This fixes it so only the webview that is associated with the window is resized.
https://github.com/user-attachments/assets/515aaeb5-aa9c-4ab0-9d95-559689312e53
=> Fix: Only Resize WebView Associated With Window

example-projects/fullstack-hackernews/src/main.rs
The example says to hover over a story, but you need to click the story title
=> Fix fullstack hackernews example instructions

packages/cli/src/serve/watcher.rs
This simplifies our watch logic to not check the hot-reloaded files coming out of the watcher against the gitignore.
This fixes the instance where updates to files like `tailwind.css` in users' gitignores were getting ignored.
This PR simply removes the ignore checking logic since we already apply the gitignore logic when initializing the watcher.
=> fix: don't gitignore manganis assets during hot-reload

packages/cli/src/build/builder.rs, packages/cli/src/serve/mod.rs
Fixes https://github.com/DioxusLabs/dioxus/issues/3361 by not sending hot-reloads to the devserver if the app is currently building.
Note that we still populate the internal hot-reload map since these changes might need to be applied once the server connects.
=> fix: don't send hot-reload if app is building

packages/cli-config/src/lib.rs, packages/cli/src/build/bundle.rs, packages/cli/src/cli/bundle.rs, packages/cli/src/cli/run.rs, packages/cli/src/cli/target.rs, packages/cli/src/dioxus_crate.rs, packages/cli/src/error.rs, packages/cli/src/serve/handle.rs, packages/cli/src/serve/mod.rs, packages/cli/src/serve/runner.rs, packages/desktop/src/app.rs
Implements `dx bundle` for android to generate `.aab` files for uploading to the playstore.
You can de-compose a `.aab` to get a raw `.apk` in the event you want to manually sign it yourself instead of uploading to the play store.
Closes #3548
---
Also adds a bit of entropy to exe names so we can have multiple, concurrent versions of the same app making the iteration process a bit nicer.
Takes a similar strategy to #3323 but is more general for all platforms.
---
Implements a session cache since the entropy features breaks the way we do window state restoration
=> feat: android bundling, red/blue exe names, session cache

packages/cli/src/serve/handle.rs, packages/desktop/src/app.rs
Fixes #3376 and also removes a number of panics in the desktop source code.
=> fix: dont unwrap as much in desktop

packages/rsx-hotreload/src/diff.rs, packages/rsx-hotreload/tests/hotreload_pattern.rs, packages/rsx/src/template_body.rs
Fixes hot reloading empty rsx nodes. When we see an empty rsx node, we replaced it with `rsx!{{()}}` in the `ToTokens` implementation, but not during hot reloading. Removing the last node is not hot reloadable because placeholder it creates is a dynamic node.
Fixes #3562
=> Fix hot reload diffing to empty rsx

examples/README.md
Most of the todo list items were already added to the examples folder. For the items that haven't been added, it might be easier to track them in issues. These are the remaining items:
- Shared state example: This is covered in the [state essentials guide](https://dioxuslabs.com/learn/0.6/essentials/state/#passing-context) and the [guide](https://dioxuslabs.com/learn/0.6/guide/state#global-state-with-context), but we don't have any examples in the folder (#3612)
- Custom elements example (#3611)
- Testing and Debugging: This seems like a better topic for a guide on the docsite (https://github.com/DioxusLabs/docsite/issues/374)
=> Remove the todo list from the examples readme

packages/cli/src/serve/output.rs
This fixes an issue with the frame width calculations that always reserved extra space to the max_term_width even if we didn't need that space, causing extra lines to bleed over:
This is now fixed:
We didn't need that `.max()` at all since we never print empty lines anyways.
=> fix: too much padding for small frames

packages/desktop/src/document.rs, packages/desktop/src/element.rs, packages/desktop/src/query.rs
This fix removes any cycles in desktop context within Elements and Queries which should hopefully fix any issues with windows not properly closing.
=> fix: don't have Rc cycles in DioxusElement or Queries

packages/cli/Cargo.toml
When running `dx serve`, the following error happens since axum-server version 0.7 and rustls version 0.23.13.
```
thread 'tokio-runtime-worker' panicked at /home/vgobbo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustls-0.23.21/src/crypto/mod.rs:249:14:
no process-level CryptoProvider available -- call CryptoProvider::install_default() before this point
stack backtrace:
0: rust_begin_unwind
1: core::panicking::panic_fmt
2: core::option::expect_failed
3: rustls::server::server_conn::ServerConfig::builder_with_protocol_versions
4: rustls::server::server_conn::ServerConfig::builder
5: axum_server::tls_rustls::config_from_der
6: axum_server::tls_rustls::config_from_pem
7: dx::serve::server::devserver_mainloop::{{closure}}
8: tokio::runtime::task::core::Core<T,S>::poll
9: …
```
=> CryptoProvider error.

Cargo.lock, packages/cli-config/src/lib.rs, packages/cli/src/serve/handle.rs, packages/cli/src/serve/server.rs, packages/desktop/src/protocol.rs, packages/mobile/Cargo.toml, packages/mobile/src/lib.rs
As noticed in https://github.com/DioxusLabs/dioxus/issues/3444#issuecomment-2606077174 the current android hot-reload actually doesn't work properly since the host env var is not passed off to the child android app.
This PR implements a `.env` file in the android session cache that holds all the env vars passed to android during dev so we can freely use `std::env::var` in the android app.
=> fix: pass off env vars to android apps

examples/fullstack-auth/src/main.rs
The fullstack auth example uses the raw web launch function which doesn't include all of the hydration logic for head elements. It doesn't cause any issues in that example, but it can cause issues when people start modifying the example like #3636. This PR switches to the launchbuilder which calls into the fullstack version if fullstack is enabled
=> Use the launch builder instead of web launch in the fullstack auth example

packages/signals/src/memo.rs
Memos lazily recompute if they are read before async tasks are run in a component. Writing to the memos internal signal while rendering will cause the possible infinite rerender warning, but it is fine in this case because the write only happens conditionally
=> Ignore write while rendering warning in memo lazy recompute

packages/router-macro/src/hash.rs, packages/router/tests/via_ssr/link.rs
The docsite is emitting extra `#` for empty hash fragments which we shouldn't do.
Fixes #3658
=> fix: don't emit hash fragment for internal links if hash is empty

packages/cli-config/src/lib.rs, packages/cli/src/serve/handle.rs, packages/cli/src/serve/server.rs, packages/dioxus/src/launch.rs
This is a complimentary fix for #3444 to allow effortlessly connecting and using the hot-reloading stuff etc. when there are some network setup limitations that prevent the current implementation from working.
As a QoL feature, I can highlight the fact that you don't have to explicitly open a local port on your host if you have an active firewall set up. As a result, you don't have to use `sudo` and write your password and then no need to remember to close that port again. And also starting developing would be just faster. 🚀
[Read more](https://github.com/DioxusLabs/dioxus/issues/3444#issuecomment-2610973993).
Fixes #3444.
=> Allow to connect to the dev server from a physical Android device

packages/document/src/elements/link.rs, packages/document/src/elements/meta.rs, packages/document/src/elements/mod.rs, packages/document/src/elements/script.rs, packages/document/src/elements/style.rs, packages/fullstack/src/document/server.rs, packages/playwright-tests/fullstack.spec.js, packages/playwright-tests/fullstack/src/main.rs, packages/playwright-tests/web.spec.js, packages/playwright-tests/web/src/main.rs
Additional attributes on the head elements were only being applied in ssr in dioxus-fullstack. This PR applies them in desktop and web as well and adds a playwright test for fullstack and web to test for regressions.
Fixes #3623
=> Fix additional attributes for js renderers

packages/dioxus/src/launch.rs
Related to #3530
Add examples for `with_cfg`, `with_context`, and `with_context_provider` methods in the `LaunchBuilder` documentation.
* **with_context_provider**: Add an example demonstrating how to inject state into the root component's context created on the thread that the app is launched on.
* **with_context**: Add an example demonstrating how to inject state into the root component's context.
* **with_cfg**: Add an example demonstrating how to provide a platform-specific config to the builder.
=> Add examples for LaunchBuilder methods

examples/README.md, examples/assets/context_api.css, examples/context_api.rs
Resolves #3612  
Adds a comprehensive example demonstrating Context API with:
- Cross-component state sharing via `use_context_provider`/`use_context`
- Reactive theme switching using Signals
- Error handling for missing context providers
- External CSS styling patterns
- Platform-agnostic implementation
```diff
+ examples/context_api.rs
+ examples/assets/context_api.css
+ examples/README.md (documentation update)
=> feat(examples): add Context API state management example 

examples/fullstack-desktop/src/main.rs, packages/dioxus/src/launch.rs
The CLI was pointing the desktop application to the fullstack backend server url instead of the url the devserver proxied the backend on. This PR use the CLI proxy address instead
Fixes #3674
=> Fix serving desktop+fullstack apps that have not set a server url

packages/html/src/events/image.rs
regression error induced by 299b123 where serde default got removed from `load_error` attribute of `ImageData`.
```diff
pub struct ImageData {
-     #[cfg_attr(feature = "serialize", serde(default))]
-     pub load_error: bool,
+     inner: Box<dyn HasImageData>,
}
// ...
+ struct SerializedImageData {
+     load_error: bool,
+ }
```
Also, it seems like neither the `load` nor the `error` events are used in [`serializeEvent`](https://github.com/DioxusLabs/dioxus/blob/36353eb90b72668f0b4173d7f083d0ad67caf416/packages/interpreter/src/ts/serialize.ts#L13). This could be an issue when an `error` event goes unnoticed and the `load_error` attribute is still set to `false` as it is the default value for `bool`.
Something like this could do the trick but it might be out of scope for this PR.
```ts …
```
=> fix onload and onerror parsing error

packages/cli/src/cli/bundle.rs
fixes msi & nsis bundles having `.exe.exe` extension in installer created shortcuts [as mentioned here](https://github.com/DioxusLabs/dioxus/issues/3233#issuecomment-2637001313).
Haven't tested on other platforms.
=> use main exe name without extension for bundler on windows

packages/core-macro/src/component.rs, translations/pt-br/README.md
Adds `#[allow(missing_docs)]` for the auto-generated props struct. We could also generate the docs but I'm not sure what we would generate.
Fixes #3690
=> Allow Missing Prop Docs

packages/cli/src/cli/bundle.rs
I tested what I needed to get tauri-bundler to stop failing without specifying an error and determined that all that was needed was the `publisher` and `identifier` configurations. I added checks for both with a helpful error message.
=> Fix: Stop Failing Silently When Bundling Windows

packages/desktop/src/config.rs, packages/desktop/src/webview.rs
If the file drop handler isn't provided, files cannot be dropped. Unfortunately, this causes HTML drag-n-drop events to no longer fire on Windows. This is an upstream issue with Window's webview2. 
The solution for now is to allow disabling the drop handler to fit the dev's required use-case. 
Related Issue (\*does not fully solve\*): #2167
=> Feat: Ability To Disable File Drop Handler

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_requst.md
The "Please add the corresponding labels to the issue." line started the chain reaction (issue OP can't add labels), and now I just overall polished the current templates.
From [the docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), the non-YAML templates are considered legacy templates, but the documentation for them is [still up](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository). I'm not user if we should switch. But Typst uses them and I didn't have any problems with them.
=> docs: improved issue templates

packages/cli/src/cli/bundle.rs
Now all files are passed to tauri_builder instead of a mix of files and directories.
Closes: #3688
=> fix: wix assets path

packages/cli/src/cli/run.rs, packages/cli/src/serve/handle.rs, packages/cli/src/serve/mod.rs, packages/cli/src/serve/runner.rs
=> Revision: Open Browser With Localhost

packages/cli/src/build/request.rs, packages/cli/src/cli/target.rs
=> Fix --target flag not passed to cargo when Platform == Server

packages/cli/src/serve/handle.rs
When opening a browser (firefox in my case) though pressing `o` and there wasn't an instance of firefox running yet. `dx serve` would hang until the instance was closed again. 
This wasn't the case when a firefox instance was already running and was only opening a new tab.
Opening the browser detached solves the issue.
=> Fix opened browser blocking `dx serve`

packages/autofmt/src/indent.rs
Typo checking CI has been failing for a couple PRs because a function accepts `typ`. This PR changes it to `ty` which we use elsewhere to mean type and doesn't trigger CI failure
=> Fix the typo checking CI

packages/rsx/src/component.rs, packages/rsx/src/ifmt.rs, packages/rsx/src/template_body.rs
We were not forwarding the span of the litstr when parsing ifmt from a macro call which causes the error messages to blame the whole call span. This PR fixes that issue
=> Fix span locations in ifmt and components

packages/router/src/components/router.rs, packages/router/src/contexts/outlet.rs, packages/router/src/lib.rs
AI Description
Here are the key reasons for exposing `OutletContext`:
- **Custom Route Rendering**
- Implement custom outlet rendering logic
- Control how nested routes are displayed
- Override default outlet behavior when needed
- **Advanced Use Cases**
- Build middleware that needs route depth information
- Implement route-based caching strategies
- Create nested loading states with different behaviors
- **Component Libraries**
- Build reusable navigation components
- Create layout systems that adapt to route depth
- Implement smart containers that respond to routing context
These use cases justify exposing `OutletContext` as part of the public API, allowing developers to build more sophisticated routing-aware features.
My Description:
Outlet is handling nested routing and levels, and …
=> Expose Outlet Context

packages/router/src/contexts/router.rs, packages/router/src/lib.rs
`RouterConfig` accepts a `on_default` callback. To be able to create types for this callback, you need access to `GenericRouterContext`. This PR just makes that type pub. 
Here is the customer use case:
```rust
/// requires type 
pub fn on_update_route<R>(state: GenericRouterContext<R>) -> Option<NavigationTarget<R>>
where
R: Routable,
{
None
}
rsx! {
Router::<router::Route> {
config: || {
RouterConfig::default().on_update(on_update_route)
}
}
}
```
=> Make GenericRouterContext pub

Cargo.lock, Cargo.toml, packages/desktop/Cargo.toml
Depending on multiple versions of the `muda` crate - one directly and one via a transitive dependency in the tray-icon crate - leads to the following error when attempting to initialize a tray icon on the desktop platform, specifically on MacOS:
```
6.858s  INFO Build completed successfully in 2882ms, launching app! 💫   7.871s  INFO [macos]: 2025-01-10 00:16:01.736 dimsum[19111:45581742] +[IMKClient subclass]: chose IMKClient_Modern
7.876s  INFO [macos]:   7.876s  INFO [macos]: thread 'main' panicked at /Users/philippherzog/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/muda-0.15.3/src/platform_impl/macos/mod.rs:934:1:
7.876s  INFO [macos]: could not create new class MudaMenuItem. Perhaps a class with that name already exists?
```
Without any prior knowledge on how the `muda` crate …
=> Fix initialising tray icons on the macos desktop platform

packages/fullstack/src/render.rs
Move suspense handling to the correct position in the SSR renderer to ensure proper rendering when streaming is disabled.
- `Meta` tag does not be rendered after suspense.
- It can improve `SEO` by suspense `Meta`
- Server returned HTML with `Meta`s before suspense.
- Server returns HTML with `Meta`s after resolving suspense
=> fix(fullstack): Resolve suspense before the head chunk when streaming is disabled

packages/desktop/src/event_handlers.rs
Fixes #3907.
The issue is caused by a simple logic error: instead of aborting the entire loop when we find a window that doesn't match our id, we should just skip the current iteration.
=> Fix later-attached wry event handlers not getting called

packages/hooks/src/use_resource.rs
This PR fixes the bug when future is restarted, the state remains ready instead of pending
Fixes #2812
=> fixed the bug when future restarts the state goes to ready instead of pending

.github/workflows/main.yml, .github/workflows/setup-dev-drive.ps1
This just disables the vfs logic in windows CI. This will make the CI slower, but it does fix the caching issue. [matrix_test (x86_64-apple-darwin, macos-13, 1.84.0, false, test, --all --tests)](https://github.com/DioxusLabs/dioxus/actions/runs/14091293751/job/39468383837#logs) runs at a similar speed so the overall slowdown is only ~2m. The underlying issue might be related to https://github.com/rust-lang/rustup/issues/2417 which could be fixed by clearing the rustup cache, but I can't find the cache for windows CI in `gh cache list`
I tried copying uv's CI setup as closely as I could, but that also does not fix the issue
=> Fix windows CI by removing virtual file system cache

packages/core/src/global_context.rs
Fixes typo, clearly the function returns the task.
=> doc: Fix spawn doc

packages/document/docs/head.md
Document: https://github.com/DioxusLabs/dioxus/issues/3756
I chose not to leak the implementation information here and rather advise users to not depend on ordering. Otherwise users depending on ordering may have negative downstream effects - changes to the implementation may case downstream code to break without users knowing why (which may happen between non-breaking semver versions), this can easily become out of date, ordering is already not guaranteed with async and changing components.
=> doc: Add head ordering doc part

packages/rsx/src/template_body.rs, packages/rsx/tests/parsing.rs
We some logic that should check that the key is always a formatted string, but it was only called before the nodes were set on an empty template. This PR fixes that issue and adds tests
Fixes https://github.com/DioxusLabs/dioxus/issues/3864
=> Fix key validation logic

packages/core-macro/src/component.rs, packages/core-macro/tests/generics.rs
fixes https://github.com/DioxusLabs/dioxus/issues/3963
=> fix: more accurate derive `Clone, PartialEq` for generic components

examples/overlay.rs, examples/shortcut.rs, packages/desktop/src/desktop_context.rs, packages/desktop/src/hooks.rs, packages/desktop/src/lib.rs, packages/desktop/src/mobile_shortcut.rs, packages/desktop/src/shortcut.rs
This state is now provided as an argument to the event handler, such that the user can decide whether to react to the global shortcut being released or not.
=> Provide `HotkeyState` on Global Shortcut Events 

packages/rsx/src/element.rs, packages/rsx/src/ifmt.rs
When attributes are merged in `Element::merge_attributes`, `out`'s `source` is not updated (I don't know if it should) and even if the segments are trivial, since `source` is empty we cannot consider it as a "simple expression" by `is_simple_expr`.
This would result in an issue when merging the following classes with me output being empty:
```rust
div {
class: "foo",
class: "{bar}",
}
```
I also modified the `merges_attributes` test splitting it into different cases:
- `merge_trivial_attributes`: merge between two literals
- `merge_formatted_attributes`: merge between a literal and a formatted
- `merge_conditional_attributes`: merge between a literal and two conditionals
- `merge_all_attributes`: merge between all of the above
=> fix(rsx): formatted attribute merging

examples/login_form.rs
This fix is for issue: https://github.com/DioxusLabs/dioxus/issues/3783
The login form example was trying to directly use FormValue in reqwest's form method, which doesn't implement Serialize. This change extracts the actual string values using as_value() before sending them to the server.
=> fix: Use as_value() to properly serialize form values in login example

packages/cli-opt/src/js.rs
Swc's errors panic if you try to drop them which means our error reporting for JS bundling fails. We were also not properly handling the fallback of copying the asset directly if JS bundling fails. This PR fixes both issues
Fixes #3909
Fixes #3917
=> Fix javascript asset bundling errors and fallback

packages/fullstack/src/serve_config.rs
This was annoying me. I don't think the default is always sensible.
I ran the tests and they passed, but haven't yet tried running the code.
=> fix(fullstack): Allow configuration of the public_path

packages/cli/src/cli/autoformat.rs
This just adds a little more detail to the `--file` flag to let devs know they can pass "-" as the file path to the `fmt` command and pass the file in via stdin (functionality added in #1529)
```
Automatically format RSX
Usage: dx fmt [OPTIONS]
Options:
--all-code               Format rust code before the formatting the rsx macros
-c, --check                  Run in 'check' mode. Exits with 0 if input is formatted correctly. Exits with 1 and prints a diff if formatting is required
-r, --raw <RAW>              Input rsx (selection)
-f, --file <FILE>            Input file at path (set to "-" to read file from stdin, and output formatted file to stdout)
-s, --split-line-attributes  Split attributes in lines or not
-p, --package <PACKAGE>      The package to build
--verbose                Use …
```
=> Add some CLI docs for stdin file input to fmt command

flake.lock
before
cargo 2024
after
[srghma@machine:~/projects/dioxus]$ cargo version
cargo 1.86.0 (adf9b6ad1 2025-02-28)
=> feat: update flake.lock

packages/cli/assets/web/toast.html
Very briefly, whenever a debug web app is opened, the toast template will flash the image and text. This PR fixes that.
=> Fix: Toast Flash of Unstyled Content

packages/desktop/src/assets.rs
=> Add android sync lock to asset handler to avoid already borrowed errors on android

packages/devtools/src/lib.rs, packages/hooks/src/use_reactive.rs, packages/signals/src/memo.rs, packages/signals/src/read_only_signal.rs, packages/signals/src/signal.rs
These warnings have been too noisy in the past and we don't have a good way of improving reliability (detecting infinite loops) in the general case
=> Remove signal write warnings

packages/cli/src/cli/autoformat.rs, packages/cli/src/cli/check.rs, packages/cli/src/metadata.rs
this should fix #3751. basically does what @ealmloff suggested, using the same function to collect `.rs` files for both `dx check` and `dx fmt`
=> fix: dx check now respects files to ignore (e.g. .gitignore)

packages/cli/src/build/web.rs
Fix #3831 
Applying change documented by @paul-hansen at https://github.com/DioxusLabs/dioxus/issues/3831#issuecomment-2741258327
Rebuild the CLI (`packages/cli`):
```shell
cargo install --path .
```
Rebuild any Dioxus web project:
```shell
dx serve
```
=> JS deprecation warning gone
=> Fix JS deprecation warning in wasm init

examples/router.rs
Fixes typo in `examples/router.rs`.
=> Fix typo in router example

packages/rsx/src/raw_expr.rs, packages/rsx/tests/parsing.rs
This is an attempt at solving issue [https://github.com/DioxusLabs/dioxus/issues/3945](https://github.com/DioxusLabs/dioxus/issues/3945) when parsing attributes.
I added code that checks if there is a TokenTree::Group followed by a dot.  If it finds it, it parses the whole attribute as an expression. It stops if it finds a comma, signaling the end of the attribute.
I added the example in the original issue to the "complex_kitchen_sink" test, and everything passed.
=> Fix parsing of braced expressions followed by a method

Cargo.lock, packages/cli/src/serve/runner.rs, packages/devtools/src/lib.rs, packages/signals/src/global/mod.rs
This fixes an issue with the hotpatch engine where it and the old hot reload engine weren't working together properly. 
I was super confused during testing as to what was happening and then had a shower thought this morning and realized we weren't clearing the old template map on hotpatches. This fixes that and also fixes asset hotreloading when hot patch is enabled.
With both engines enabled, our hot-reload is so damn 🔥🔥🔥 blazingly  fast 🔥🔥🔥
https://github.com/user-attachments/assets/65657afd-0d30-4163-92b4-5466890aba20
=> fix: interaction between both hot-reload engines

packages/html/src/elements.rs
While adding support for Dioxus in [`image-rs`](https://github.com/opensass/image-rs), i noticed some of the `img` tag attrs are missing. So, i added them.
Also, I have a question: how can we attach a node reference to a tag? I don't see any tags that accept the `ref` attr. Why tho?
=> fix: add missing `img` attrs

packages/cli/src/serve/output.rs
fix #3847 
Update "Platform", "App features" and "Serving at" paragraphs by removing wrapping.
ratatui's Wrap system causes text to disappear into an invisible 2nd line when paragraph content exceeds available space, which might confuse new users when terminal width is small. This PR removes wrapping entirely, using ratatui default behavior (truncation) instead, which is not optimal either (i.e. URL gets truncated) but possibly less confusing.
```
╭────────────────────────────────────────────────────────────────────────── /:more ╮
│  App:     ━━━━━━━━━━━━━━━━━━━━━━━━━━  🎉 0.4s      Platform: Web                 │
│  Bundle:  ━━━━━━━━━━━━━━━━━━━━━━━━━━  🎉 3.7s      App features: ["web"]         │
│  Status:  Serving [_project_name_] 🚀 4.1s         Serving at:                   │ …
```
=> Update dx serve output: remove wrap in right-side paragraphs

Cargo.toml
Allows examples to be run with `dioxus-native`
=> Add "native" feature flag to examples

packages/core-macro/src/props/mod.rs, packages/core-macro/tests/rsx.rs
This PR updates the generated props `build()` to use SuperInto and the props Owner for defaults of props that are child owned types (ReadOnlySignal/Callback), matching the behavior when the prop is set explicitly with its builder method.
Compile-time tests were added to assert that both existing default assignments and less-verbose defaults work.
Closes [3920](https://github.com/DioxusLabs/dioxus/issues/3920)
=> Use SuperInto and correct Owner for props defaults

packages/cli/src/build/builder.rs, packages/cli/src/build/request.rs, packages/cli/src/config/app.rs, packages/cli/src/config/dioxus_config.rs, packages/cli/src/main.rs, packages/cli/src/serve/mod.rs, packages/cli/src/serve/runner.rs, packages/cli/src/settings.rs, packages/cli/src/tailwind.rs, packages/cli/src/wasm_bindgen.rs, packages/cli/src/workspace.rs
This PR adds support for inline tailwind css, drastically simplifying how dioxus users interact with tailwind.
See the tailwind blogpost talking about tailwind standalone:
https://tailwindcss.com/blog/standalone-cli
We'll be able to detect the tailwind.css file and then automatically hot-reload it for you when the CLI is serving.
The tailwind binaries are quite large (70-100mb) but that shouldn't be a huge problem in practice.
We could also look at depending on encre directly https://gitlab.com/encre-org/encre-css
=> Inline the TailwindCLI into dx and run it during serve

.github/workflows/main.yml
The `DeterminateSystems/magic-nix-cache-action` action has been [deprecated](https://determinate.systems/posts/magic-nix-cache-free-tier-eol/) and no longer works. This PR replaces it with the `nix-community/cache-nix-action` action, which is actively maintained. It also replaces the `DeterminateSystems/nix-installer-action` action with the `nixbuild/nix-quick-install-action` action, which is required for the cache action to work. The cache has been configured to restore based on the runner's OS and architecture, so it should work on any runner.
=> Replace magic-nix-cache-action

Cargo.lock, Cargo.toml, examples/fullstack-websockets/.gitignore, examples/fullstack-websockets/Cargo.toml, examples/fullstack-websockets/src/main.rs, packages/playwright-tests/fullstack.spec.js, packages/playwright-tests/fullstack/Cargo.toml, packages/playwright-tests/fullstack/src/main.rs, packages/server/Cargo.toml, packages/server/src/context.rs
The new logic to override different parts of the server function response broke the websocket server function protocol because it always set the response status to 200 by default. This PR fixes the issue by tracking what parts of the response have been written to and only writing those back to the final response
Fixes #4100 
TODO:
=> Fix websocket server functions and add an example

Cargo.lock, Cargo.toml, packages/playwright-tests/playwright.config.js, packages/playwright-tests/web-routing.spec.js, packages/playwright-tests/web-routing/.gitignore, packages/playwright-tests/web-routing/Cargo.toml, packages/playwright-tests/web-routing/src/main.rs, packages/router/src/contexts/router.rs
The web router was not writing back the route if it changed from what was parsed in the URL which causes redirects to fail. This PR fixes #4093 and adds a playwright regression test
=> Fix web redirect routes

packages/cli/src/build/request.rs
This fix uses response files on windows to write linker args to a response file, fixing issues where we have too many arguments.
https://github.com/DioxusLabs/dioxus/issues/4102#issuecomment-2883973473
=> fix: use response files (@args) on windows

packages/cli/src/build/request.rs
Hi!
When playing with the bleeding edge of Dioxus, I noticed that in the release mode, the JS file and the WASM file were imported in wrong places on accident (WASM file was imported instead of JS and vice versa). This rendered the app unusable in the web build.
This simple pull request fixes this mistake.
=> fix: fixed wasm and js paths in release mode

examples/fullstack-auth/Cargo.toml
The auth example never enabled the server feature of the dioxus crate which caused the endpoints to fail. This PR fixes that issue
Fixes #4135
=> Fix authentication example

packages/signals/src/write.rs
I found this while debugging https://github.com/marc2332/freya/issues/1173
=> fix: Make `Writable::toggle` use peek to avoid subscribing as `Readable::Cloned` uses `Readable::read`

packages/cli/src/build/patch.rs, packages/subsecond/subsecond/src/lib.rs
=> fix: symbol mismatch  in object file

packages/cli/src/build/request.rs
In my windows `Administrator: ARM64 Native Tools Command Prompt for VS 2022 (2)` command prompt, the various sysroots seem to be set fine when doing compiles/linking.
However, it seems that the default command prompt does *not* set these variables, and that rustc figures out the sysroot for windows manually and adds stuff like `ntdll.dll` to the path. This PR just steals the environment set by the rust compiler and replicates it for the linking commands, preserving the behavior of a typical rust compile.
=> fix: use the rustc env for linking too, hopefully fixing windows

packages/cli/src/cli/link.rs
This PR fixes a case that during multi-platform builds (e.g., when simultaneously targeting Windows and Android), Windows-specific .lib files from dependencies like `embed_resource` are incorrectly included in Android linker arguments, despite proper `#[cfg(windows)]` guards in both `build.rs` and `Cargo.toml`
=> fix(cli): filter out .lib files when targeting Android

Cargo.lock, Cargo.toml, packages/cli/Cargo.toml, packages/cli/src/build/builder.rs, packages/cli/src/build/patch.rs, packages/cli/src/build/request.rs, packages/cli/src/cli/link.rs, packages/cli/src/devcfg.rs, packages/cli/src/rustcwrapper.rs, packages/cli/src/serve/output.rs, packages/cli/src/serve/proxy.rs, packages/cli/src/serve/runner.rs, packages/cli/src/workspace.rs, packages/desktop/src/launch.rs, packages/devtools/src/lib.rs, packages/dioxus/src/launch.rs, packages/mobile/src/lib.rs, packages/server/src/config.rs, packages/subsecond/subsecond-tests/cross-tls-crate-dylib/Cargo.toml, packages/subsecond/subsecond-tests/cross-tls-crate-dylib/src/lib.rs, packages/subsecond/subsecond-tests/cross-tls-crate/Cargo.toml, packages/subsecond/subsecond-tests/cross-tls-crate/src/lib.rs, packages/subsecond/subsecond-tests/cross-tls-test/Cargo.toml, packages/subsecond/subsecond-tests/cross-tls-test/README.md, packages/subsecond/subsecond-tests/cross-tls-test/src/main.rs, packages/subsecond/subsecond/src/lib.rs
Fixes https://github.com/DioxusLabs/dioxus/issues/4154 by implementing framework linking in our bundle setup.
Fixes https://github.com/DioxusLabs/dioxus/issues/4146
Fixes https://github.com/DioxusLabs/dioxus/issues/4149
Fixes https://github.com/DioxusLabs/dioxus/issues/4159
Fixes https://github.com/DioxusLabs/dioxus/issues/4165
Fixes long paths?
Fixes aarch64-unknown-linux subsecond
Previously we assumed all apps were statically linked into the bundle, but projects like bevy rely on dynamic linking of code, which breaks that assumption. This fix is not just for subsecond, but rather any rust crate that compiles as a dylib, since we weren't distributing those dylibs at all.
This kicks in for both `.so` files and `.dylibs`, but I'm unsure how we should handle windows, so I simply left it as …
=> feat: copy frameworks to Frameworks folder, detect linkers, custom target dirs

packages/server/src/server.rs
Motivation
Currently, WASM servers cannot use `serve_dioxus_application` because it's trait extension only has an implementation for non-WASM targets. If users try to manually implement this functionality, they encounter difficulty accessing the private `context_providers` field in the `ServeConfig`, and have to rewrite a lot of the core logic for SSR which has a maintenance burden.
This PR adds conditional compilation for the `serve_static_assets` method:
- For non-WASM targets: maintains the existing implementation that serves static assets from the public directory
- For WASM targets: provides a simple implementation that just returns `self` (no-op)
This allows WASM servers to use the same `serve_dioxus_application` API as non-WASM servers, simplifying code that needs to work across …
=> Enable serve_dioxus_application for WASM targets

Cargo.lock, Cargo.toml, packages/ssr/src/renderer.rs, packages/ssr/tests/escape.rs, packages/ssr/tests/simple.rs
[`askama_escape`] v0.13 uses codepoints instead of named entities for HTML escaping: `&lt;` → `&#60;`.
Only tests in `packages/ssr` were executed. Running `run_local_tests.sh` had errors unrelated to my changes; some docker images could not be downloaded. Could be that something is misconfigured on my system, though.
[`askama_escape`]: <https://crates.io/crates/askama_escape>
=> chore(ssr): update `askama_escape` dependency

packages/cli/src/build/request.rs, packages/cli/src/cli/bundle.rs
Dx bundle and release web builds currently always panic on fresh builds. This PR fixes both issues. The bundle command is consuming the release flag in two different places. Release web builds, remove the wasm assets before bundling them
=> Fix dx bundle and release web builds

packages/document/src/elements/link.rs
This adds a quick fix for this issue that could be applied immediately.
The issue I came across was that the code below would only show the preload link but not the stylesheet below:
```rs
const FAVICON: Asset = asset!("/assets/favicon.ico");
const MAIN_CSS: Asset = asset!("/assets/css/main.css");
const FONTAWESOME_CSS: Asset = asset!("/assets/fontawesome/css/fontawesome.min.css");
const FONTAWESOME_SOLID_CSS: Asset = asset!("/assets/fontawesome/css/solid.min.css");
const TAILWIND_CSS: Asset = asset!("/assets/tailwind.css");
fn main() {
core::start_app(app);
}
rsx!(
// Global app resources
document::Link { rel: "icon", href: FAVICON }
document::Link { rel: "preload", href: MAIN_CSS, as: "style" }
document::Link { rel: "preload", href: FONTAWESOME_CSS, as: "style" } …
```
=> Fix bug where preloading and using a stylesheet deduplicates the link

packages/playwright-tests/package-lock.json, packages/playwright-tests/package.json
This PR updates Playwright to the latest version (1.52.0).
To apply the update, I ran:
```bash
npm install -D @playwright/test@latest
```
=> Update Playwright to version 1.52.0

packages/cli/src/build/builder.rs, packages/cli/src/build/request.rs, packages/cli/src/cli/target.rs, packages/cli/src/serve/server.rs
Adds a new CLI argument that overrides the base path. This makes the preview deploy action a lot nicer
=> Allow changing the base path from a cli arg

.github/workflows/main.yml, .github/workflows/publish.yml, packages/cli/Cargo.toml, packages/cli/src/build/request.rs, packages/cli/src/wasm_opt.rs, packages/playwright-tests/playwright.config.js
`dx serve --platform web --release` is currently broken when dx is built with the optimizations feature flag enabled. Wasm opt itself works with our current flags when installed from source, but the rust wrapper library we are using is broken. This PR switches to just installing the binary directly instead of using the bindings. This also means we don't need to maintain two different code paths for the local and bundled versions of wasm-opt
=> Always download wasm opt from the binary

Cargo.lock, Cargo.toml, examples/wgpu-texture/Cargo.toml, examples/wgpu-texture/src/demo_renderer.rs, examples/wgpu-texture/src/main.rs, examples/wgpu-texture/src/shader.wgsl, examples/wgpu-texture/src/styles.css, packages/native/Cargo.toml, packages/native/src/dioxus_application.rs, packages/native/src/dioxus_renderer.rs, packages/native/src/lib.rs
- Upgrades Blitz to `0.1.0-alpha.3`
- Adds an example of integrating custom wgpu rendering with the native backend
=> Upgrade Blitz to `0.1.0-alpha.3` and add wgpu-texture example

Cargo.lock, Cargo.toml, packages/cli/src/build/request.rs, packages/desktop/Cargo.toml, packages/desktop/src/app.rs, packages/desktop/src/webview.rs
Added an option to the WebViewBuilder navigation handler to open links starting with "mailto:".
```rust
webview = webview
.with_web_context(&mut web_context)
.with_bounds(wry::Rect {
position: wry::dpi::Position::Logical(wry::dpi::LogicalPosition::new(0.0, 0.0)),
size: wry::dpi::Size::Physical(wry::dpi::PhysicalSize::new(
window.inner_size().width,
window.inner_size().height,
)),
})
.with_transparent(cfg.window.window.transparent)
.with_url("dioxus://index.html/")
.with_ipc_handler(ipc_handler)
.with_navigation_handler(|var| {
// We don't want to allow any navigation
// We only want to serve the index file and assets
if var.starts_with("dioxus://") || var.starts_with("http://dioxus.") {
true
} else {
if var.starts_with("http://") || var.starts_with("https://") {
_ = …
```
=> Allows desktop apps to open mailto links

Cargo.lock, packages/dioxus/src/launch.rs, packages/fullstack-hooks/Cargo.toml, packages/fullstack-hooks/src/history.rs, packages/fullstack-hooks/src/lib.rs, packages/fullstack/src/lib.rs, packages/playwright-tests/fullstack-routing/src/main.rs, packages/router/src/components/router.rs, packages/server/src/render.rs, packages/web/src/lib.rs
This PR serializes the initial server router state for the client to fix some hydration issues. This helps with some client-side only navigator properties like can_go_back and fixes 404 routes in SSG where the server rendered URL and client url are different
Fixes #4047 
Fixes #3644
=> Fix router hydration

packages/cli/src/build/request.rs
Fixes: https://github.com/DioxusLabs/dioxus/issues/4238
Fixes: https://github.com/DioxusLabs/dioxus/issues/4296
Tested:
- merging of rustflags
- using .cargo/config
- using RUSTFLAGS env var
- hotpatching enabled and hotpatching disabled
```rust
// main.rs
fn main() {
dioxus::launch(app);
}
let mut buf = [0u8; 120];
getrandom::fill(&mut buf).unwrap();
rsx! {
div {
h1 { "Hello, Dioxus!" }
p { "This is a simple Dioxus application." }
pre { "Random bytes: {buf:?}" }
}
}
}
```
```toml
[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']
```
=> properly respect rustflags, fix x86-sim issue

packages/rsx/src/template_body.rs
The follwing code compiles did not compile in release mode before this PR but did in debug:
```rust
fn app(arg: String) -> Element {
rsx! {
div {
key: "{arg}",
for arg in Vec::from(arg) {}
}
}
}
```
This does not work in release as the macro only assembles the key at the end but the example moves the key into the children therefore not compiling. But in a debug build it works as the key is handled differently because of hot-reloading magic I guess.
I should probably include a test but I am not sure where as the rsx crate only includes macro parsing tests it seems.
=> Allow a borrowed key to move into children

examples/fullstack-auth/src/auth.rs, examples/fullstack-auth/src/main.rs, examples/fullstack-desktop/src/main.rs, examples/fullstack-hello-world/src/main.rs, examples/fullstack-router/src/main.rs, examples/fullstack-streaming/src/main.rs, examples/fullstack-websockets/src/main.rs, packages/fullstack/README.md, packages/fullstack/docs/request_origin.md, packages/fullstack/src/error.rs, packages/fullstack/src/lib.rs, packages/playwright-tests/default-features-disabled/src/main.rs, packages/playwright-tests/fullstack/src/main.rs, packages/playwright-tests/nested-suspense/src/lib.rs, packages/playwright-tests/nested-suspense/src/ssg.rs, packages/server-macro/src/lib.rs, packages/server/docs/request_origin.md, packages/server/src/config.rs, packages/server/src/context.rs, packages/server/src/lib.rs
Now that the server function crate has support for custom error types, we can use a type that is easier to convert into the dioxus error type. This PR switches to our own implementation of a server error type which can be converted into the dioxus captured error type with `?`.
The `CapturedError` type is a boxed Error without the `Send` requirement. We need the error type to implement `Send` for our axum integration. Serializing the `CapturedError` type also has some odd interactions. If you serialize the type and then try to downcast it, the downcast will fail because the serialization and deserialization looses the type information
This and the new server function custom error type support close https://github.com/DioxusLabs/dioxus/issues/3243. We now use json serialization for the …
=> Implement Into<CaptureError> for the default server function error type

.github/workflows/main.yml, .github/workflows/merge.yml, .github/workflows/publish.yml, packages/cli/src/cli/run.rs, packages/cli/src/wasm_opt.rs, packages/playwright-tests/playwright.config.js
Right now, our CI swallows errors during builds, leading to playwright running for hours if it fails. This switches our playwright to use `dx run` which is just a version of `dx serve` that disables hot-reloading.
To make it useful for CI, we also need to adjust `dx run` to properly fail if it encounters an error, which we should've been doing the whole time.
=> use `dx run` for playwright tests, properly abort if error occurs, don't ddos github releases, split apt-cache by os/target in matrix

Cargo.lock, examples/wgpu-texture/Cargo.toml, examples/wgpu-texture/src/main.rs, examples/wgpu-texture/src/styles.css, packages/native/Cargo.toml, packages/native/src/mutation_writer.rs
- Upgrade version
- Use exact `=` version specifier to prevent new Blitz alpha releases from breaking `dioxus-native` alpha (`alpha.1` is broken)
- Use `asset!` in wgpu-texture example
- Use `src` rather than `data` for canvas source id
=> Upgrade to Blitz `0.1.0-alpha.4`

packages/cli/src/build/request.rs, packages/cli/src/cli/link.rs
Otherwise errors like
```
/usr/bin/ld: /home/moritz/Documents/tucant/target/aarch64-linux-android/android-dev/deps/android_keyring-acc2f2a0e5f90c9e.android_keyring.88a7041dc86cc013-cgu.0.rcgu.o: error adding symbols: file in wrong format
```
occurred
=> Pass android linker to cargo

packages/cli/src/build/builder.rs
Apparently the mobile codesign folder changed in xcode 16, breaking the old version of this. Didn't realize it.
Fixed it and some other bugs related to `--device` and now `dx serve --platform ios --device` works!
Fixes https://github.com/DioxusLabs/dioxus/issues/3858
https://github.com/dotnet/macios/issues/20771
=> fix ios codesign on device

packages/router-macro/src/lib.rs
link to issue: https://github.com/DioxusLabs/dioxus/issues/4331
what happens:
in route_macro/lib.rs, there is a core::convert method call, in user's case, he/she has a self `core` module
fix:
clarify `core::convert` to `::core::convert`
=> fix issue: Routable doesn't work with component in a core module. #4331

Cargo.lock, examples/wgpu-texture/Cargo.toml, examples/wgpu-texture/src/main.rs, packages/native/src/lib.rs
Allows for things like setting the initial window size.
=> Native: Accept `winit::WindowAttributes` as a config value

packages/cli/src/config/bundle.rs
This PR adds `#[serde(default)]` to various fields in bundle config structs to prevent deserialization errors when those fields are omitted from Dioxus.toml.
- MacOsSettings: `files`, `hardened_runtime`
- DebianSettings: `files`
- WindowsSettings: `tsp`, `allow_downgrades`
- NsisSettings: `display_language_selector`
Default values for more [bundle] settings #3785
=> fix(bundle): add serde defaults to prevent deserialization errors

examples/file_upload.rs
When dropping js or txt files, the browser would still do its default behavior of showing the contents of the file (either in a new tab or navigating away from the current Dioxus app page, depending on the browser/user preferences). The docs for prevent_default say, "Note: This must be called synchronously when handling the event. Calling it after the event has been handled will have no effect."
This makes the `ondrop` handler synchronous and uses `spawn` to handle the file reading.
I'm not an expert on Dioxus or Rust so there might be something wrong/bad with this solution.
=> prevent_default must be called synchronously or it will have no effect

packages/autofmt/src/lib.rs, packages/autofmt/src/writer.rs, packages/autofmt/tests/samples/comments.rsx, packages/rsx/src/rsx_call.rs
Fixes rsx autofmt eating comments in even more situations.
The comment test is quite comprehensive now, so you should see wayyyy less issues with rsx autofmt. 
Also tries to roll in the fixes from https://github.com/DioxusLabs/dioxus/pull/4410
=> fix: don't eat comments in more situations

packages/cli-opt/src/file.rs, packages/cli-opt/src/hash.rs, packages/cli-opt/src/lib.rs, packages/cli/src/build/builder.rs, packages/cli/src/build/request.rs, packages/cli/src/cli/build_assets.rs
This fixes two bugs with the asset system:
1) Assets with multiple extensions like `foo.tar.gz` lost the hash because the second extension  with the hash (`tar-hash`) was replaced instead of pushing a the final extension
2) If the asset system includes two files with an identical content hash, but different source paths they were not deduplicated and one of the threads will fail to write the duplicate asset to the output path
Fixes #4432
=> Fix assets with odd extensions and race condition with the same asset at different paths

Cargo.lock, Cargo.toml, examples/native-headless-in-bevy/Cargo.toml, examples/native-headless-in-bevy/README.md, examples/native-headless-in-bevy/src/bevy_scene_plugin.rs, examples/native-headless-in-bevy/src/dioxus_in_bevy_plugin.rs, examples/native-headless-in-bevy/src/main.rs, examples/native-headless-in-bevy/src/ui.css, examples/native-headless-in-bevy/src/ui.rs
Created in answer to https://github.com/DioxusLabs/dioxus/discussions/4362, and following https://github.com/DioxusLabs/dioxus/pull/4365
This example demonstrates rendering a Dioxus application onto a texture within a Bevy application:
- Render a headless Dioxus-native app to a texture.
- Share and display the texture on a quad in the Bevy app.
- Transmit mouse and keyboard events from Bevy to Dioxus.
- Events are captured when hovering over elements with the `catch-events` class, ensuring only Dioxus receives them.
- Manage application state through channel messages between Dioxus and Bevy.
Notes:
- I did not setup a `NetProvider` for the `DioxusDocument`, as I was not sure how to do it without the event loop proxy.
- As a result I could not move the CSS to an asset.
- The inputs of type …
=> Example of rendering a dioxus-native app to a texture in a Bevy application

packages/cli/src/config/bundle.rs
- Adds #[serde(default)] for all fields of all bundle settings structs where the types impl Default
- WindowsSettings: derive Default since all types impl Default
Default values for more [bundle] settings #3785
=> fix(bundle): add serde default for all fields that impl Default

packages/native-dom/src/dioxus_document.rs
We have `<title>` tag support in Blitz now. Just need to create the element correctly in `dioxus-native`.
=> Fix title example on native

packages/cli/src/build/assets.rs, packages/cli/src/build/builder.rs, packages/cli/src/build/request.rs, packages/cli/src/cli/doctor.rs, packages/cli/src/workspace.rs
In the Bevy discord, nix users were running into issues because we call out to a variety of tools from PATH, but they purposefully unset their PATH and thus the tools were failing.
This PR adds better logging in a few critical places, pointing people to add the tools to their path.
It also updates our `dx doctor` command to provide `which` locations for these tools and lets users run `dx doctor` from anywhere on their machine, not just from within projects.
The original issue where this occurred:
https://github.com/DioxusLabs/dioxus/issues/4372
=> better logs, don't run codesign if no assets are found

packages/asset-resolver/src/lib.rs, packages/cli-config/src/lib.rs, packages/cli/src/build/request.rs
Linux appimage and dep bundles store the binary in `/bin/binary` and the assets in `/lib/$product_name` directory. This PR changes the resolver to use the correct path.
I have tested this branch with normal release builds and release bundles with appimage and dep on `Ubuntu 22.04.5 LTS` with this project: https://github.com/ealmloff/linux-bundle-dioxus
Addresses (but doesn't totally fix) https://github.com/DioxusLabs/dioxus/issues/4161
=> Fix asset location for linux bundles

packages/cli/src/cli/target.rs, packages/cli/src/cli/update.rs
Currently, some CLI flags that default to true cannot be disabled. This change allows users to opt-out with `--install=false` or `--install false`.
=> Allow user to specify =false for default true flags

Cargo.lock, Cargo.toml, examples/rsx_usage.rs, packages/native-dom/src/mutation_writer.rs, packages/native/Cargo.toml, packages/native/src/lib.rs
- Bump Blitz to 0.1.0-rc.3 (includes named grid lines and areas)
- Implement `dangerous_inner_html` for dioxus-native
- Implement style namespace attributes for dioxus-native
- Fixes DioxusLabs/blitz#240
The style namespace support doesn't attempt to do anything fancy in the case that the user specifies both style-namespace attributes and a `style` attributes on the same element. They will simply clash. Users should be advised not to do this.
=> Bump Blitz to 0.1.0-rc.3 (+dangerous_inner_html + style ns attrs)

packages/cli/src/logging.rs
=> Don't output escape codes for the cursor when the tui isn't active

packages/stores-macro/src/derive.rs, packages/stores/tests/marco.rs
Some of the bounds were not being forwarded or being forwarded in the wrong way for generic structs that derive store. This PR fixes that issue and adds tests
Fixes https://github.com/DioxusLabs/dioxus/issues/4566
=> Fix store macro with struct bounds

packages/hooks/src/use_resource.rs
`use_resource` does not need `must_use` since it can run reactive async effects
=> Remove must_use from Resource

.zed/settings.json
Added the `.zed` configuration folder to enable Zed development. `.zed/settings.json` is a mirror of the `.vscode/settings.json`.
=> Add '.zed' folder for Zed-related development

Cargo.lock, Cargo.toml, packages/logger/Cargo.toml, packages/logger/src/lib.rs, packages/web/src/cfg.rs, packages/web/src/devtools.rs, packages/web/src/lib.rs
When apps panic in the browser, we now show a toast with the stack trace and the panic info.
This should help people diagnose crashing WASM apps better.
=> show panics in the toast in wasm

packages/cli/src/build/request.rs
This PR bumps the android_min_sdk fallback up to 28.
This unlocks crates like cpal to compile normally, fixing https://github.com/DioxusLabs/dioxus/issues/4443
Note that sdk 28 was released in 2018 while 24 was released in 2016.
=> bump android min-sdk up to 28

packages/cli/src/build/patch.rs, packages/core-macro/src/component.rs, packages/core-macro/src/props/mod.rs, packages/core/src/effect.rs, packages/core/src/error_boundary.rs, packages/core/src/scheduler.rs, packages/core/src/scope_context.rs, packages/core/src/suspense/mod.rs, packages/desktop/src/ipc.rs, packages/manganis/manganis-core/src/asset.rs, packages/router-macro/src/lib.rs, packages/router-macro/src/query.rs, packages/router-macro/src/route.rs, packages/signals/src/read.rs, packages/wasm-split/wasm-split-cli/src/lib.rs, packages/web/src/history.rs
This fixes a number of clippy lints that were introduced in rust 1.89
We'll still keep the msrv in CI to be 1.85, but this at least makes us modern.
Fixes https://github.com/DioxusLabs/dioxus/issues/4562
=> fix lints on rust 1.89

Cargo.lock, packages/devtools/Cargo.toml, packages/devtools/src/lib.rs
This PR adds a `dioxus_devtools::subsecond_serve` which makes it easier to run the subsecond hot-reload engine outside of dioxus.
This should handle cases like TUIs, Axum, Burn, and other hot-reload systems that want a "hot" async integration.
For example, an axum app that gets hot-reload looks like so:
```rust
#[tokio::main]
async fn main() {
dioxus_devtools::serve_subsecond(router_main).await;
}
async fn router_main() {
use axum::{Router, routing::get};
let app = Router::new().route("/", get(test_route));
let listener = tokio::net::TcpListener::bind("0.0.0.0:3000").await.unwrap();
println!("Server running on http://localhost:3000");
axum::serve(listener, app.clone()).await.unwrap()
}
async fn test_route() -> axum::response::Html<&'static str> {
"axum works!!!!!".into()
}
```
=> feat: add subsecond serve

packages/manganis/manganis/src/macro_helpers.rs
You will run into this message if you try to build dioxus with a mismatched version of dx. The current error message mentions something about the linker, but doesn't provide any debugging steps. This PR adds some help information to resolve the issue
=> Improve placeholder hash error message

Cargo.lock, Cargo.toml, packages/native-dom/src/dioxus_document.rs
Fixes https://github.com/DioxusLabs/dioxus/issues/4616 and a few other bugs
=> Upgrade Blitz to v0.1.0

examples/assets/todomvc.css
Because Blitz doesn't implement transitions/animations yet, the presence of these styles causes the `color` style to not apply at all. Obviously we need to fix this in Blitz eventually, but for now let's just forgo the transition.
=> Remove transitions from todomvc stylesheet

packages/server/src/launch.rs
This is an attempt to fix magic number/word error when in fullstack mode and hot patching is active:
```
13:39:49 [web] panicked at /home/sebba/.cargo/git/checkouts/dioxus-d8abd2ecf6e8b5b4/a519fba/packages/subsecond/subsecond/src/lib.rs:647:10:
called `Result::unwrap()` on an `Err` value: JsValue(CompileError: wasm validation error: at offset 4: failed to match magic number)
```
**Why this happens?**
This bug is present only in fullstack mode, the cause is axum router that serves static assets needs to be rebuilt to serve newly added file, and rebuild was only triggered if incoming hot-reload message included a server patch jumptable. 
This meant if client didn't generate wasm patch file before server patch was ready, router would respond with a 404 even if the file was present in the …
=> Rebuild router on every hot reload message

packages/native/src/assets.rs, packages/native/src/dioxus_application.rs, packages/native/src/lib.rs
=> fix: feature gate tokio and tracing

packages/dioxus/src/lib.rs
GlobalSignal is in the prelude, but GlobalStore is missing. This PR re-exports the global store in the prelude
=> Add GlobalStore to the prelude

packages/router/src/components/link.rs
When a link has the `new_tab` argument set to true, we need to fall back to the default link behavior instead of our client side routing to open the link in a new tab
Fixes #4657
=> Fix opening in new tab with internal links

packages/cli/src/build/request.rs
This allows using `dx` for web workers.
=> Don't rely on `window`

packages/core/tests/conditional_formatted_attributes.rs, packages/rsx/src/attribute.rs
The logic for finding expressions in if statement branches was wrong causing type inference to fail with this snippet:
```rust
input {
type: if true { "one" } else if true { "two" } else { "three" },
}
```
This PR fixes that issue.
Fixes https://github.com/DioxusLabs/dioxus/issues/4720
=> Fix chained attribute if statements with static strings

Cargo.lock, Cargo.toml, packages/core/src/diff/node.rs, packages/fullstack-protocol/src/lib.rs, packages/playwright-tests/fullstack-spread.spec.js, packages/playwright-tests/fullstack-spread/Cargo.toml, packages/playwright-tests/fullstack-spread/src/main.rs, packages/playwright-tests/playwright.config.js, packages/web/src/hydration/hydrate.rs
When we switched from having a single attribute per mount slot to many per mount slot, the hydration logic wasn't changed. We currently only hydrate nodes that have any real attributes attached to them which causes issues with empty spread attributes. They have a slot we need to keep track of where attributes could be inserted in the future, but don't have any attributes today. This PR fixes that issue and adds a regression test
After this, #4640, and #4600 the component library works out of the box with hydration
Fixes #4646
=> Fix hydration with empty spread attributes

packages/autofmt/src/prettier_please.rs
https://github.com/DioxusLabs/dioxus/issues/4504
=> Fix #4504 where `dx fmt` fails on eval of JS that contains empty line.

packages/fullstack/src/payloads/sse.rs
Not sure since when, but axum's Sse::keep_alive now returns a different type so we can't re-assign `let mut sse` to its result.
(Also not sure how CI didn't catch this?)
=> Fix Sse keepalive build error

packages/cli/src/serve/server.rs
This PR fixes #3815 because `rustls` requires installation of a `CryptoProvider` before `axum` (or any server) can use it.
Said installation is accomplished by calling:
```rust
rustls::crypto::CryptoProvider::install_default(
rustls::crypto::aws_lc_rs::default_provider()
)
```
before calling `axum_server::from_tcp_rustls().serve()`.
`install_default` can fail, but I think it is safe to call `bail!` on failure here because:
- it should only fail if a `CryptoProvider` is not already installed;
- `start` and `devserver_mainloop` are not public API.
By submitting this PR, I agree that my contributions become part of the `dioxus` project as per the MIT and Apache licenses.
=> FIX: web.https configuration - error: no process-level CryptoProvider available

packages/signals/src/boxed.rs
When updating dioxus, I noticed ReadOnlySignal failed to compile. We have the alias, but the storage default wasn't set which makes it more difficult to migrate to the new version
=> Fix ReadOnlySignal alias without storage
