packages/desktop/src/lib.rs
This PR fixes builds for windows desktop. For whatever reason, the windows WebView library navigates to the wrong URL, so we need to catch those too.
=> fix: windows desktop

docs/reference/src/web/index.md
What was there was an abomination that would not behave at all properly. The changes I’ve made are extremely conservative. Myself, I’d get rid of the `<html>`, `<head>`, `</head>`, `<body>`, `</body>` and `</html>` lines as superfluous, and remove the space inside the div, which I certainly hope isn’t load-bearing.
=> Fix errors in the suggested index.html template

packages/desktop/src/index.js, packages/desktop/src/lib.rs
When the webview was loaded, the eventloop would go into an idle state. This PR prevents the event loop from going idle by sending en event into the EventLoop once the webview has been loaded using some internal JS
=> fix: windows and gtk startup lag

examples/calculator.rs
The Example `calculator` cannot be use, so I have to fixed the bug, now it's can be run to calculate data.
Some details have yet to be refined.
=> fix: calculator example

Cargo.toml, README.md
cc #55 
This turns on the desktop, router, and ssr features by default for examples.
@nilsmartel can you make sure this functions the way you expect it to?
```
git pull
git checkout jk/simplify-example-run
cargo run --example readme
```
=> examples: simplfy running them by enabling features automatically

examples/framework_benchmark.rs, examples/pattern_model.rs, packages/core-macro/src/rsx/component.rs, packages/core/src/nodes.rs, packages/core/src/scopes.rs, packages/hooks/src/useref.rs, packages/html/src/events.rs
Fixes #77 #88
The docs were "ahead of the times" and were describing a feature that did not yet exist!
This has been remedied in this PR.
=> Fix/Feat: Don't force the &dyn Fn syntax for passing through event handlers

examples/disabled.rs, packages/desktop/src/index.js, packages/web/src/dom.rs
I have add all `bool_attrs` into white_list, if the attr is a bool attr, then will check `true` and `false`, else normal set attribute.
```
"allowfullscreen",
"allowpaymentrequest",
"async",
"autofocus",
"autoplay",
"checked",
"controls",
"default",
"defer",
"disabled",
"formnovalidate",
"hidden",
"ismap",
"itemscope",
"loop",
"multiple",
"muted",
"nomodule",
"novalidate",
"open",
"playsinline",
"readonly",
"required",
"reversed",
"selected",
"truespeed",
```
=> Boolattrs limit type

.github/workflows/main.yml, packages/core-macro/src/ifmt.rs, packages/core-macro/src/props/mod.rs, packages/core-macro/src/rsx/component.rs, packages/core/src/scopes.rs, packages/desktop/src/cfg.rs, packages/hooks/src/use_shared_state.rs, packages/hooks/src/usecoroutine.rs, packages/hooks/src/useref.rs, packages/hooks/src/usesuspense.rs, packages/router/src/components/link.rs, packages/router/src/components/route.rs, packages/router/src/lib.rs, packages/ssr/src/lib.rs
This PR enables clippy and applies a few fixes to make it lint successfully. See additional comments below.
=> CI: Enable clippy

packages/ssr/src/lib.rs
When bool attribute exclusion was added, we did not update the SSR crate. This fixes that.
=> fix: ssr respects bool attrs

examples/optional_props.rs, packages/core-macro/src/props/mod.rs, packages/router/src/components/link.rs, packages/router/src/components/router.rs
This PR flattens the attributes provided to us by https://github.com/idanarye/rust-typed-builder
So instead of `#[props(setter(strip_option)]`, it would just be `#[props(strip_option)]`.
cc @autarch
=> Flatten optional prop attributes

examples/core_reference/children.rs
It needs lifetime parameters If you want to build it so I have added lifetime parameters.
=> docs: allow build core_reference/children example

docs/guide/src/setup.md
This breaks the page currently; https://dioxuslabs.com/guide/setup.html
=> Fix typo in docs

examples/optional_props.rs, packages/core-macro/src/props/mod.rs
Adds the flag "optional" to props that combines default and strip_option
=> feat: add "optional" flag for props

packages/core/src/nodes.rs
Fixes #125 
Also allows handlers to properly clean up their memory (an oversight)
=> fix: allow eventhandler to derive default

packages/html/src/global_attributes.rs
`gap` is quite useful now that it's supported in flex layouts by all major browsers.
=> Add gap and row_gap to style_trait_methods

packages/web/Cargo.toml, packages/web/src/lib.rs
Most users who want to build a Dioxus app *also* want stacktraces on panics. This PR just adds that by default, improving the onboarding DX for users so they can actually see *why* their app panicked.
=> Feat: add console_error_panic_hook by default for wasm

packages/router/src/hooks/use_route.rs, packages/router/src/service.rs
This PR makes it so the `use_route` command subscribes the component to changes to the URL.
=> fix: use_route should subscribe to changes to the route

packages/router/src/components/link.rs
All the other routing-related messages are at the trace level. Leaving this at
debug was an oversight on my part.
=> Make log message in Link component trace level, not debug

packages/web/src/dom.rs
this commit fixes an issue where we used the event target to prevent default even if the target element wasn't an event handler.
fixes #157
=> fix: dioxus web prevents default in nested targets

.gitignore, examples/borderless.rs, packages/desktop/src/desktop_context.rs, packages/desktop/src/lib.rs
`DesktopContext` provide some api to control window, like `drag_window` `minimized` `maximized`.
=> `DesktopContext` Wrap & Inject

examples/svg.rs, packages/html/src/elements.rs, packages/html/src/global_attributes.rs
This PR adds prevent_default (and a few other style attributes) onto the svg namespace to solve #197
=> fix: allow prevent_default on svg

.docker/Dockerfile_pre_test, .docker/run_local_tests.sh, .github/workflows/main.yml, Makefile.toml, packages/router/Makefile.toml
I modified the Makefile a bit so that it doesn't compile on every crate. Instead, it builds first then runs the tests (eventually build what is required for the tests). With this in place, tests in CI take much less time to proceed.
Added also a separate test in the Makefile will test with proper configuration for runtime tests.
=> Improve test speed in the CI

packages/interpreter/src/bindings.rs, packages/web/Cargo.toml, packages/web/src/dom.rs
This PR uses the crate suggested by @t1m0t to use a different flavor of converting strings to JsValues. On my machine, this results in a performance improvement of about 20% and a size reduction of 10%.
=> feat: use serde-wasm-bindgen crate for speedup

docs/guide/src/README.md, notes/README/ZH_CN.md
The sample in the guide and the sample in READE.md were outdated APIs, so we fixed them.
=> fix: update the sample

packages/interpreter/src/interpreter.js
Fixes #215 .
TSC was generating too modern of code that carried over into the current version. This PR removes class attributes to adhere to es6 (the latest spec we adhere to).
=> fix: class attributes don't adhere to es6 spec

packages/interpreter/src/interpreter.js
We had a regression in a recent commit that removed prevent default in all desktop cases.
This PR fixes that, re-enabling out-linking.
=> fix: always prevent default on `A` tags in desktop

.docker/Dockerfile_base_test_image, .docker/Dockerfile_code_coverage, .docker/Dockerfile_pre_test, .docker/Dockerfile_test, .docker/run_local_tests.sh, .github/workflows/main.yml, .gitignore
Setting up code coverage locally with tarpaulin and adapt ci workflow
=> Code coverage setup

packages/desktop/src/lib.rs
Hi,
Small contribution here. When creating a transparent Window, shouldn't it also set the `WevView` to be transparent automatically ? This is what this PR is about.
Unfortunately, I am wondering if someone somewhere would need the window to be transparent, but not the `WevView`. If that's the case, then this solution won't do...but really, why would someone need that kind of feature ?
Have a nice day!
=> Transparent window means transparent WebView

packages/desktop/src/index.html
Initially I wanted to delete only the duplicated `<html>` opening tag, but then decided to make it a fully valid HTML document.
Passes https://validator.w3.org/nu/#textarea check.
=> Clean up desktop's index.html

docs/guide/src/interactivity/hooks.md
The example showed the closure accepting a single argument, but it accepts none.
=> Fix closure signature for use_ref example in interactivity docs

packages/web/Cargo.toml, packages/web/src/dom.rs, packages/web/src/lib.rs, packages/web/src/ric_raf.rs
This PR re-uses the dioxus-core futures-channel dependency instead of pulling in the async-channel dependency.
=> Use futures-channel instead of async-channel in rIC/rAF code

Cargo.toml, packages/desktop/Cargo.toml, packages/desktop/src/cfg.rs, packages/desktop/src/controller.rs, packages/desktop/src/desktop_context.rs, packages/desktop/src/events.rs, packages/desktop/src/lib.rs, packages/desktop/src/protocol.rs, packages/desktop/src/user_window_events.rs, packages/interpreter/src/interpreter.js, packages/interpreter/src/lib.rs
First of all: Thank you for this amazing project!
I had already slightly more fun with this than with tauri itself, even though it stands on the shoulders of it (wry, tao).
I know it's a lot at once, but the wry 0.13 upgrade led me down a rabbit hole.
What changes:
- general dependency updates as much as possible (not only wry)
- switch from RPC to IPC handler, fix message (de)serialization
- modularize some code pieces
- adjust module/function/struct/enum visibility where it made sense (not all need to be pub)
- general cleanups
If something is not to your liking or you want something split up differently, I can try to cut separate PRs.
Note: I tested it with some examples and a local project, all on a Win10 machine.
=> Update to wry 0.13; support IPC, devtool, and feature flags

packages/core/Cargo.toml
If they aren't the same then Cargo cannot resolve a working version for some reason.
=> Make all packages which require futures-channel ask for the same version

packages/router/src/components/router.rs
This PR removes the `div` element that was wrapped around children of the router. This could confuse people and throw css styles off.
=> fix unnecessary div

examples/login_form.rs, packages/html/src/elements.rs
Creating a login form example to demonstrate a common example using a form to login and make an async call to an external api.
A couple of caveats:
Only works on web, but to keep it consistent as router changes are added in left it as dioxus::desktop.
This works on the current version of the router on web, but is bound to change as the router is updated.
I can add something quick to the guide as well, it looks like a lots changed in there. Any suggestions on where to add it?
=> Login Form Example

packages/desktop/src/index.html, packages/desktop/src/lib.rs
Webview will never get custom context menus (the thing when you right click), so it's up to app authors to implement their own context menus. A library for making that easier will be very helpful to the Dioxus ecosystem.
Anyways, this PR adds an initialization script in release mode that disables the context menu altogether, since having a right click menu that *just* shows reload is probably not super helpful to most users.
=> Disable reload context menu in production

examples/heavy_compute.rs, packages/desktop/src/controller.rs, packages/desktop/src/lib.rs, packages/desktop/src/user_window_events.rs
Fix #266 
We weren't pinging the window to wake up after the initial rebuild - which we do after every *new* edit is generated.
=> fix: ping window after virtualdom is ready

docs/guide/src/hello_world.md
Fixing this warning when I try to compile
warning: function `App` should have a snake case name
--> src/main.rs:7:4
|
7 | fn App(cx: Scope) -> Element {
|    ^^^ help: convert the identifier to snake case: `app`
|
= note: `#[warn(non_snake_case)]` on by default
Also changing edition from 2018 to 2021
=> fixing build warnings in hello world example

packages/desktop/Cargo.toml, packages/desktop/src/cfg.rs, packages/desktop/src/lib.rs, packages/desktop/src/protocol.rs
This PR adds the right relative pathing for assets when bundled through cargo-bundle.
It's never been this easy to include an image in your Rust `.app`! :)
I don't have any other machine than a mac box so I can't test alternate implementations.
https://crates.io/crates/directories
These targets do not provide a straightforward way of bundling assets. I've opted to make it the asset dir configurable instead.
=> feat: canoncialize assets for macOS, Windows, and Linux

packages/core/src/diff.rs, packages/core/tests/diffing.rs
I guess this bit of code got lost in the refactor from iterative to recursive. 😅
Derp derp derp
=> fix: actually remove nodes in keyed_diff_middle

examples/calculator.rs, examples/crm.rs, examples/disabled.rs, examples/dog_app.rs, examples/framework_benchmark.rs, examples/hydration.rs, examples/pattern_reducer.rs, examples/readme.rs, examples/rsx_compile_fail.rs, examples/svg.rs, examples/tasks.rs, examples/textarea.rs, examples/todomvc.rs, examples/window_event.rs, examples/xss_safety.rs, packages/hooks/src/usestate.rs
This PR is a middle ground between the original UseState and the new react UseState. It doesn't implement copy (so you can call clone for async) but it *is* a single value - which should be clearer.
It does introduce some more indirection (double asterisk or .get() when trying to access the underlying value).
I think we lose some ergonomics but we can some consistency and clarity.
=> Make use_state a single value again

packages/router/src/components/link.rs
There should be a global way of setting the active class as well but I don't know how to properly do that. Please let me know what I can do.
=> Added active class to router link

.gitignore, packages/router/src/cfg.rs, packages/router/src/components/link.rs, packages/router/src/components/router.rs, packages/router/src/hooks/use_route.rs, packages/router/tests/web_router.rs, packages/router/usage.md
In order to not have to modify the `active_class` on every link there is now a prop with the same name on `Router`.
Useful when you're using a CSS framework like Bulma where the active nav links are expected to have the class `"is-active"`.
Also: `use_route` can now also be used outside of `Route` components.
=> active_class prop for Router

docs/guide/src/components/propsmacro.md, examples/optional_props.rs, packages/core-macro/src/props/mod.rs, packages/router/src/components/redirect.rs, packages/router/src/components/router.rs
Please see the added documentation for a good explanation.
=> Option<...> props are optional by default.

examples/form.rs, packages/web/src/dom.rs
Solution implemented is to return an optional value from the target element, which for all cases except radio buttons is a Some.  For radios, only the checked element will return a Some.  This prevents the last radio in the group from always overwriting the group value.
=> Capture correct radio button value in a form input event

packages/interpreter/src/bindings.rs, packages/interpreter/src/interpreter.js, packages/web/.vscode/settings.json, packages/web/Cargo.toml, packages/web/src/rehydrate.rs, packages/web/tests/hydrate.rs
This PR fixes hydration by re-adding the SetNode method back in after some changes accidentally removed it.
Our wasm tests are still flaky though, and definitely need to be improved, since we are essentially flying blind.
=> fix: setnode method for rehydration code

packages/tui/Cargo.toml, packages/tui/src/attributes.rs, packages/tui/src/hooks.rs, packages/tui/src/layout.rs, packages/tui/src/lib.rs
- Fix ctrl c not quitting (new crossterm version interprets ctrl + key as ctrl + capital key)
- adds margin for borders
- adds all keys
- add text property elements: b, strong, u, ins, del, i, em, and mark
=> tui bugfixes and text modifier elements

examples/order.rs, packages/desktop/src/controller.rs
This fixes #306 .
Instead of implementing a VecDeque as shown in #326 , we just use a regular push/drain approach which fixes all the ordering bugs.
=> fix: instantly resolving futures should not use popping

packages/core/src/diff.rs, tests/diffing.rs
Fixes  #332
When adding children to a element which previously had none, the mutations did not add the PushRoot instruction before adding children.
This PR adds the instruction.
=> fix: diff_lazynodes bug adding children

packages/core-macro/src/inlineprops.rs
=> fix: inline props should look for attributes

packages/router/src/hooks/use_route.rs
The router was silently throwing away queries not prefixed with an extra `?`.
The documentation for `url::Url::query` indicates that it will not include the `?` delimiter ahead of the URL-encoded form string, and `strip_prefix` returns `None` if the prefix doesn't match.
=> Fix query parsing

packages/desktop/src/lib.rs
This PR removes the JavaScript alerts shown when the user makes a right click but they are disabled (by default, they are disabled on release).
Is the `alert` on purpose or was it just forgotten ? Since alerts are *kinda* considered bad practice, I think they should be removed. Feel free to close this PR if I'm mistaken.
=> Removed alerts when right click is disabled.

packages/html/src/elements.rs, packages/liveview/Cargo.toml, packages/liveview/examples/axum.rs, packages/liveview/examples/warp.rs, packages/liveview/src/adapters/axum_adapter.rs, packages/liveview/src/adapters/warp_adapter.rs
I like Axum, and wanted to try to make a Liveview toy app. I have implemented a connector in the same style as the warp connector (it is pretty much copy paste).
I have also changed the examples to suppress VScode IDE errors when having dioxus open in the same workspace as a seperate application (I moved the cfg statement inside the main function so that VScode wouldn't complain that there was no main function).
I have also added the menu element to Dioxus html
=> Liveview Axum Integration + Example updates

packages/fermi/src/hooks/atom_ref.rs
Quick fix for Fermi crate to avoid re-render in silent write.
=> fix: unmarking component as dirty in silent write

packages/hooks/src/lib.rs
A quick fix to export  ``use_effect`` function from hooks modules
=> fix: export useeffect in hooks module

src/lib.rs
In the src/lib.rs file, there were `cfg` conditional compilation flags around the imports of `use_eval` which were written as
```rs
#[cfg(all(target = "wasm", feature = "web"))]
```
which were meant to only enable the following code on the wasm target, but these were setup incorrect. The correct way to check if on wasm is the following:
```rs
#[cfg(all(target_arch = "wasm32", feature = "web"))]
```
=> Fix cfg conditions for wasm

docs/reference/src/platforms/tui.md, packages/tui/src/config.rs
The default config has ctrl_c_quit enabled, but the method with_ctrl_c_quit sets it to enabled again. It should disable it instead.
=> change with_ctrl_c_quit to without_ctrl_c_quit for tui config

packages/core/src/arbitrary_value.rs, packages/core/src/lib.rs, packages/core/src/mutations.rs, packages/core/src/nodes.rs, packages/ssr/src/lib.rs, packages/web/Cargo.toml, packages/web/src/dom.rs
Allow attributes to be any value. It does take more space (24 bytes instead of 16), but allows us to get static dispatch on most types with a fallback to `AnyAttributeValue`. If you have a type that is not 'static, you can find a way to transmute pointers to stuff it into AnyAttributeValue.
```rust
// trying to keep values at 3 bytes
#[cfg_attr(feature = "serialize", derive(serde::Serialize, serde::Deserialize))]
#[derive(Clone, Debug, PartialEq)]
pub enum AttributeValue<'a> {
Text(&'a str),
Float32(f32),
Float64(f64),
Int32(i32),
Int64(i64),
Uint32(u32),
Uint64(u64),
Bool(bool),
ColorRGB(u8, u8, u8),
ColorRGBA(u8, u8, u8, u8),
ColorHex(u32),
ColorHexAlpha(u32, u8),
Vec3Float(f32, f32, f32),
Vec3Int(i32, i32, i32),
Vec3Uint(u32, u32, u32),
Vec4Float(f32, f32, f32, f32),
Vec4Int(i32, i32, …
```
=> Arbitrary Attribute Values

docs/guide/src/elements/lists.md
Fixes minor spelling typo in documentation
=> Fix typo [skip ci]

.github/workflows/main.yml, packages/core/src/arbitrary_value.rs, packages/core/src/lib.rs, packages/native-core-macro/tests/update_state.rs
Fixes:
- String attributes incorrectly rendered as `[Object object]`
- Couple of failing tests
- Missing dependency in Github CI
With the new `AttributeValue`, attributes were serialized with values like `{Text: "value"}`, resulting in `[Object object]` when the interpreter applied them.
This simple fix restores the original behavior at least for Text values, by serializing them without the tag (just `"value"`).
I am not sure if this is a correct/complete approach, and I don't even know what the expected behavior would be for more complex variants such as `Vec3Float`. But at least the simple Text case is working again now.
=> Fix: AttributeValue bug; tests; CI

docs/guide/src/interactivity/index.md
I was reading the guide and I crossed upon a pair of examples that were not valid. So I updated them.
=> Fix outdated guide section (React-like foo, set_foo)

packages/desktop/Cargo.toml, packages/desktop/src/desktop_context.rs
https://github.com/tauri-apps/wry/blob/454bf18084cd5f8879f2982d1c107719aa25a9d9/src/webview/mod.rs#L474-L477
open_devtools requires feature `devtools` or debug build
which this line of code used. so we need add this feature
https://github.com/DioxusLabs/dioxus/blob/fe1279a1c591a9ba57feb82a5162e076c940817b/packages/desktop/src/desktop_context.rs#L215
=> fix(desktop): makes release build working

packages/web/src/dom.rs
Fixes bug where using the `focusin` event on the web caused a panic.
This issue was discussed in #416 (but does not fix use of `onfocus`). Tested on the web, `focusin` now works.
=> Fix web missing event types

examples/svg_basic.rs
only test in Firefox, screenshot:
=> Example: SVG Basic shapes from https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Basic_Shapes

packages/native-core/Cargo.toml, packages/native-core/src/layout_attributes.rs, packages/tui/Cargo.toml, packages/tui/src/hooks.rs, packages/tui/src/layout.rs, packages/tui/src/lib.rs, packages/tui/src/render.rs, packages/tui/src/style_attributes.rs, packages/tui/tests/margin.rs
Switch to taffy where future development will take place.
Major changes:
- it outputs relative layout instead of absolute layout
- it doesn't pretend to support direction
- it doesn't pretend to support overflow
=> Use Taffy instead of stretch2 for tui and native core

packages/tui/src/hooks.rs
Layout switched from absolute to relative to its parent in #438, but the code that checks collision with the mouse in the event code was not changed to account for that. This PR resolves the absolute position before checking for collision.
=> fix mouse events for tui

packages/rsx_interpreter/src/lib.rs, packages/rsx_interpreter/tests/render.rs
The path to the file in hot reloading currently produces a different result on unix and windows because they have different path separators, but when building for wasm it fails to detect the os.
Solution: Keep the crate and file path separate
=> fix path separator for hot reloading

packages/desktop/src/controller.rs, packages/rsx_interpreter/src/captuered_context.rs, packages/rsx_interpreter/src/error.rs, packages/rsx_interpreter/src/interperter.rs, packages/rsx_interpreter/src/lib.rs, packages/web/src/lib.rs
Issue: If a application has the hot-reload feature enabled, but did not run through dioxus serve, the application will silently fail on errors.
Solution: When an error is produced warn the user the websocket was not connected and note that they should use hot reloading through dioxus serve --hot-reload, and panic with the error message.
=> panic on errors in hot-reload if no error handler socket is connected

packages/rsx_interpreter/src/captuered_context.rs, packages/rsx_interpreter/src/error.rs, packages/rsx_interpreter/src/interperter.rs, packages/rsx_interpreter/tests/render.rs
Hot reloading currently only supports attributes from the html crate. This adds support for custom attributes.
```
div {
"customAttr": "whatev",
"customAttr": 0,
}
```
closes #479
=> allow custom attributes to be captured for hot reloading

examples/tui_colorpicker.rs, packages/tui/src/layout.rs, packages/tui/src/lib.rs, packages/tui/src/query.rs
Some elements need to know the size of the current element. For example the slider element in the input element needs to know how wide the object is to handle mouse input.
=> add query context (tui)

.github/workflows/docs.yml
Remove nightly build of `reference` (now removed)
=> Remove reference from docs CI

.github/workflows/main.yml, Makefile.toml
I looked a bit into why our CI test are taking so long (~30m in some cases) and it appears that the benchmarks are at fault. The `tui_update` benchmark in particular is taking very long (18 minutes on my machine).
I propose removing the benchmarks from the tests we perform in CI. This will make it faster to check that a PR doesn't break anything, improving the workflow.
I don't think they add much value to PR testing anyway – it's not like anyone is checking them for performance regressions during PRs. We *could* have a separate CI thingy that benchmarks `master` every time it updates and makes the HTML reports show up somewhere. That would be cool, but also probably more trouble than its worth.
```
$ time cargo test --bench tui_update
Finished test [unoptimized + debuginfo] target(s) in …
```
=> Exclude benchmarks from testing

examples/borrowed.rs, packages/core/src/scopes.rs, packages/desktop/src/desktop_context.rs, packages/dioxus/tests/borrowedstate.rs, packages/dioxus/tests/earlyabort.rs, packages/dioxus/tests/lifecycle.rs, packages/dioxus/tests/miri_stress.rs, packages/dioxus/tests/sharedstate.rs, packages/fermi/src/hooks/atom_ref.rs, packages/fermi/src/hooks/atom_root.rs, packages/fermi/src/hooks/init_atom_root.rs, packages/fermi/src/hooks/read.rs, packages/fermi/src/hooks/set.rs, packages/fermi/src/hooks/state.rs, packages/hooks/src/use_shared_state.rs, packages/hooks/src/usecoroutine.rs, packages/hooks/src/useeffect.rs, packages/hooks/src/usefuture.rs, packages/hooks/src/usemodel.rs, packages/hooks/src/useref.rs, packages/hooks/src/usestate.rs, packages/hooks/src/usesuspense.rs, packages/router/src/components/link.rs, packages/router/src/components/redirect.rs, packages/router/src/components/route.rs, packages/router/src/components/router.rs, packages/router/src/hooks/use_route.rs, packages/router/src/hooks/use_router.rs, packages/web/src/util.rs
This is a breaking change.
---
Alternative: we *could* make `use_hook` take a trait `impl UseHookFn`, and implement it for both `()->T` and `(usize)->T`, and deprecate the latter, but breaking it seems better:
- There is no valid use case for the argument
- It's an easy change (find + replace)
- Neat function signature -> docs quick to understand
- There wouldn't be a good mechanism to make this deprecation show up as a warning
=> Remove argument from `use_hook` closure

packages/tui/src/render.rs, packages/tui/src/style_attributes.rs
Fixes tui layout. The native-core layout was changed to use dimension directly. This updates tui with those changes.
=> update tui to use taffy dimention directly

packages/fermi/src/hooks/state.rs, packages/hooks/src/usestate.rs
Introduced in a8952a9ee8d8831fa911cef4e7035293c3a9f88b and 4518b6bc8cfbe246d0844b2a32f11f437115d00d by @jkelleyrtp  
Spotted while reading the docs. I don't know how this happened (twice!), perhaps some find-and-replace or editor macro trickery. I was pretty easy to deduce correct text though.
=> Fix weird docs typo/copy-paste error

packages/rsx/src/component.rs
fixes #502 
The current method of parsing components checks if the attribute has a trailing comma before checking for formatting. This PR allows the last attribute to not have a trailing comma, but still contain formatted segments.
=> allow the last attribute in a component to contain formatting

packages/core-macro/tests/ifmt.rs, packages/rsx/src/ifmt.rs
currently this fails to compile:
```rust
let x = 0;
rsx!{
"{x} {x}"
}
```
This is because the format_args_f macro transforms it into
...
format_args!("{x} {x}", x = x x = x)
...
which contains duplicates that are not allowed in format_args.
This PR deduplicates the assignments.
=> allow duplicate variables in format_args_f

packages/core/src/arbitrary_value.rs
I am not yet familiarized with the core codebase so I am not sure why this is needed, but looks like I need it, otherwise it would just panic.
Context: I am working on my own renderer and I am implementing an image element with an attribute that receives the content of the image in form of bytes.
I tried it with these changes and it worked :)
=> feat: Support Bytes type in AttributeValue

packages/html/src/global_attributes.rs
Adds the remaining global attributes from the [MDN global attributes docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes) to the global attribute namespace.
fixes #534
=> add missing global attributes

examples/rsx_usage.rs, examples/todomvc.rs, packages/dioxus/tests/miri_stress.rs, packages/rsx/src/node.rs, packages/web/examples/hydrate.rs
This implementation had the unfortunate side-effect of colliding with regular function calls leading to a sore point. This gets rid of that implementation and only allows lowercase components if they use the path syntax.
This is implemented to make room for #550 and regular helper functions being more common.
=> Remove lower case components that use the paran syntax

packages/fermi/src/atoms/atom.rs, packages/fermi/src/atoms/atomfamily.rs, packages/fermi/src/atoms/atomref.rs, packages/fermi/src/root.rs
The previous implementation of AtomIds for Fermi could lead to downcast errors if Rust merged two statics together.
Now, we only downcast a type if the TypeId is verified to match by adding its TypeId into its AtomId.
This prevents the particular issue but doesn't help with Rust merging statics together.
In apps that actually use their atoms, this won't be an issue (hopefully).
Fixes #536
=> fix: use typeid of atoms for their unique ID to prevent down casting panics

packages/desktop/Cargo.toml, packages/desktop/src/lib.rs, packages/desktop/src/protocol.rs
Infer is more robust that mime-guess for loading assets from the file system.
=> feat: use infer instead of outdated mime-guess, bump wry

docs/guide/src/en/__unused/advanced-guides/11-arena-memo.md, docs/guide/src/en/__unused/advanced-guides/12-signals.md, docs/reference/src/guide/rsx_in_depth.md, docs/reference/src/guide/rsx_in_depth_pt-br.md, examples/file_explorer.rs, examples/svg.rs, notes/README.md, packages/core-macro/src/lib.rs, packages/core/README.md, packages/core/src/events.rs, packages/core/src/scopes.rs, packages/core/src/virtual_dom.rs, packages/dioxus/benches/jsframework.rs, packages/dioxus/src/lib.rs, packages/dioxus/tests/diffing.rs, packages/dioxus/tests/earlyabort.rs, packages/dioxus/tests/miri_stress.rs, packages/dioxus/tests/passthru.rs, packages/dioxus/tests/vdom_rebuild.rs, packages/native-core-macro/tests/called_minimally_on_build.rs, packages/native-core-macro/tests/change_nodes.rs, packages/native-core-macro/tests/initial_build.rs, packages/native-core-macro/tests/peristant_iterator.rs, packages/native-core-macro/tests/update_state.rs, packages/rsx/src/lib.rs, packages/rsx_interpreter/src/captuered_context.rs, packages/rsx_interpreter/tests/render.rs, packages/web/src/lib.rs
Addresses #256 
For most use cases, your Scope object is called `cx`. This PR adds an unhygienic macro that assumes `cx` is already in scope and calls `cx.render`. 
now, all you need is `render`.
```rust
let mut count = use_state(&cx, || 0);
render!(
h1 { "High-Five counter: {count}" }
button { onclick: move |_| count += 1, "Up high!" }
button { onclick: move |_| count -= 1, "Down low!" }
)
}
```
TODO:
- Add the ability to use custom cx names
- Wire up `render` name into auto formatting and hot reloading
=> feat: add an unhygenic render macro

packages/core/src/arbitrary_value.rs, packages/core/src/lib.rs
- Implemented `Display` for `AttributeValue::Any`
- Made `ArbitraryAttributeValue` public outside the `core` crate
Note about the first change: 
Just like https://github.com/DioxusLabs/dioxus/pull/543, I went using `{:?}`, but if you think necessary it can be changed to simply:
```rust
AttributeValue::Any(_) => write!(f, ""),
```
This way it won't actually write anything in the buffer... but that's okay? It works fine both ways, I still don't know why `AttributeValue` needs to implement `Display`.
Thoughts?
=> Feat: Make AttributeValue::Any usable

packages/desktop/src/events.rs, packages/html/src/events.rs
fixes #566
This adds a event data type for the onscroll event, instead of using the mouse data type. The onscoll event does not contain any data about the pointer on the web platform: https://developer.mozilla.org/en-US/docs/Web/API/Element/scroll_event#event_type
=> fix scroll data

packages/native-core/src/real_dom.rs
This will clean up all the listeners of a Node when it's removed.
I noticed while using `get_listening_sorted()` it would sometimes panic because it was unable to find a removed Node that previously had a listener. With this fix, the listeners and the node list should be on sync, so whenever you try to retrieve all the node listeners it should only get Nodes that actually exist.
Note: I haven't actually tested these changes with the new changes from https://github.com/DioxusLabs/dioxus/commit/047ed1e5536d266785240fb3db475ac2fc77b785
=> fix: Remove a Node listeners when it is removed

packages/core/Cargo.toml, packages/core/src/arbitrary_value.rs, packages/core/src/template.rs, packages/rsx/src/template.rs
This works, but it requires an extra clone bound on ArbitraryAttributeValue to allow for a owned variant.
fixes #572
=> Add arbitraryAttributeValue to ownedAttributeValue

packages/core/src/lib.rs
Allow an optional comma at the end of to_owned!
```
#[test]
fn it_works() {
let a = 1;
let b = true;
to_owned![a, b,];
}
```
I would prefer it this way. Let me know what you think.
=> to_owned!: allow optional comma at the end

packages/core-macro/src/lib.rs, packages/rsx/src/lib.rs
The render macro doesn't need lazy nodes. It can use the node factory directly without the overhead of calling LazyNodes::new or LazyNodes::call
=> Make render marco bypass lazynodes

packages/core/Cargo.toml, packages/core/src/diff.rs, packages/core/src/mutations.rs, packages/core/src/scopes.rs, packages/core/src/template.rs, packages/core/src/util.rs, packages/core/src/virtual_dom.rs, packages/native-core-macro/Cargo.toml, packages/native-core-macro/src/lib.rs, packages/native-core-macro/tests/update_state.rs, packages/native-core/Cargo.toml, packages/native-core/src/real_dom.rs, packages/native-core/src/state.rs, packages/tui/Cargo.toml, packages/tui/src/hooks.rs, packages/tui/src/lib.rs, packages/web/Cargo.toml, packages/web/src/olddom.rs
The rust performance book recommends using rustc-hash instead of fxhash for maintenance reasons - https://nnethercote.github.io/perf-book/hashing.html
"[rustc-hash](https://crates.io/crates/rustc-hash) provides FxHashSet and FxHashMap types that are drop-in replacements for HashSet and HashMap. Its hashing algorithm is low-quality but very fast, especially for integer keys, and has been found to out-perform all other hash algorithms within rustc. ([fxhash](https://crates.io/crates/fxhash) is an older, less well maintained implementation of the same algorithm and types.)"
Do you see any reasons against this? Let me know what you think!
=> replace fxhash crate with rustc-hash

packages/interpreter/src/interpreter.js
Fixes inserting dynamic nodes in templates after a fragment. This resolves all dynamic paths before they are use which results in a slight performance hit on creating nodes but better performance on accessing dynamic nodes after they are created.
=> fix inserting dynamic nodes after fragments

packages/desktop/Cargo.toml, packages/desktop/src/desktop_context.rs
Updating to webbrowser 0.8.0 fixes compiling for ios, while not crashing if the webview isn't initialized yet fixes an issue encountered on sway/wayland/linux.
=> Some fixes for wayland and ios.

packages/desktop/Cargo.toml
`dioxus-desktop` currently depends on `wry` via git.
This is an issue because:
1. The specified branch (`release`) doesn't seem to exist within the [wry repository](https://github.com/tauri-apps/wry).
2. IIRC crates.io doesn't allow git dependencies.
3. The specified version is already available via crates.io
This PR fixes all of the above by changing the dependency back to crates.io.
=> fix desktop dependency `wry`

packages/core/Cargo.toml, packages/core/src/diff.rs, packages/core/src/mutations.rs, packages/core/src/scopes.rs, packages/core/src/virtual_dom.rs
It seems that https://github.com/DioxusLabs/dioxus/pull/600 has overwritten https://github.com/DioxusLabs/dioxus/pull/588 in the core package, this PR changes it again.
=> fix: replace fxhash with rustc-hash in core

packages/rsx/src/lib.rs
fixes attributes or text nodes with ```{{``` or ```}}```
=> fix fmt escape sequences in static attribute/text nodes

docs/guide/src/en/best_practices/index.md, docs/guide/src/en/getting_started/desktop.md, docs/guide/src/en/getting_started/hot_reload.md, docs/guide/src/en/getting_started/mobile.md, docs/guide/src/en/getting_started/ssr.md, docs/guide/src/en/getting_started/tui.md, docs/guide/src/en/getting_started/web.md, docs/guide/src/en/interactivity/router.md, docs/guide/src/pt-br/best_practices/index.md, docs/guide/src/pt-br/getting_started/desktop.md, docs/guide/src/pt-br/getting_started/hot_reload.md, docs/guide/src/pt-br/getting_started/mobile.md, docs/guide/src/pt-br/getting_started/ssr.md, docs/guide/src/pt-br/getting_started/tui.md, docs/guide/src/pt-br/getting_started/web.md, docs/guide/src/pt-br/interactivity/router.md
There are some places in the docs that refence renderer features on the dioxus crate that no longer exist. This PR removes those references
followup to #387
=> remove references to renderer features that do not exist

docs/guide/examples/component_children_inspect.rs, packages/core-macro/src/props/mod.rs, packages/core/Cargo.toml, packages/core/src/arena.rs, packages/core/src/create.rs, packages/core/src/diff.rs, packages/core/src/error_boundary.rs, packages/core/src/fragment.rs, packages/core/src/lib.rs, packages/core/src/nodes.rs, packages/core/src/scheduler/wait.rs, packages/core/src/scopes.rs, packages/core/src/virtual_dom.rs, packages/core/tests/bubble_error.rs, packages/router/src/components/redirect.rs, packages/router/src/components/route.rs, packages/rsx/src/component.rs, packages/rsx/src/lib.rs, packages/ssr/src/lib.rs, packages/ssr/src/renderer.rs, packages/tui/examples/tui_colorpicker.rs, packages/tui/src/widgets/mod.rs
After trying to use the error handling with anyhow, I don't really think it's worth the breaking change.
Error boundaries are best paired with exceptions. Currently, we don't protect the render tree from panics which is what error boundaries would be good for anyway.
The idea here is to pull back the Result changes are just stick with Option<Vnode>. If you want to throw an error, you can use the throw trait or panic.
The throw trait and panic will be implemented in a future PR.
=> chore: rollback to option instead of anyhow

packages/native-core/src/real_dom.rs, packages/native-core/src/utils/persistant_iterator.rs
There were a few places the stack was being split at the wrong place and we needed to reverse the split stack in a few places before inserting nodes to fix the ordering for keyed lists
closes #676
=> fix mutations in native core related to keyed lists

packages/tui/benches/update.rs, packages/tui/src/lib.rs
This allows creating an app with root level props the same as what the desktop and web renderer already have. This allows simplifying the tui benchmark.
=> add launch_cfg_with_props to tui

packages/tui/benches/update.rs
Changes the tui benchmark to consume TuiContext instead of &TuiConext because consume context now returns owned values instead of references
=> fix tui benchmark

packages/native-core/Cargo.toml, packages/native-core/src/layout_attributes.rs
This switches from a manual parsing implementation for taffy attributes in native-core to lightning-css. This PR has support for all layout attributes Taffy currently supports and should make it easier to add more attributes in the future.
=> use lightning css to parse Taffy layout attributes

packages/html/src/elements.rs
Since it compiles without the fix, I am not sure if this is intentional or a typo.
=> Fix potential typo: Strign -> String

packages/rsx/src/element.rs
The current implementation defaults to None for the namespace and false for volatile instead of using the values defined in the html crate.
This breaks the following example:
```rust
fn main() {
}
cx.render(rsx! {
h1 {
color: "{\"red\"}",
"This should be red"
}
})
}
```
This PR fixes that issue.
=> Fix the namespace and volatility of dynamic attributes

Cargo.toml, examples/signals.rs, packages/signals/Cargo.toml, packages/signals/src/lib.rs, packages/signals/src/rt.rs
Implements a new type of state API using `Copy + 'static` keys. The one downside is that the runtime that backs the signals needs to be leaked. We can reclaim the runtime safely by cycling them into linked list or slab, but can never shrink down to zero.
Currently this is not integrated with templates or diffing, but we can eventually expose hooks for both, allowing for the full signal experience.
This PR doesn't add "create_signal", only "use_signal" which taps into the regular re-render process of Dioxus.
---
Going to merge this in an experimental fashion. Will test it against some examples.
=> feat: simple signals implementation

packages/native-core-macro/src/lib.rs, packages/native-core/src/node.rs, packages/native-core/src/real_dom.rs, packages/native-core/src/state.rs, packages/native-core/src/utils/persistant_iterator.rs
Follow up to #648
This adds some extra bounds to the real dom to allow custom (FromAnyValue) types within the nodes contained in the realdom. The original code was missing these bounds which makes the unit value the only possible custom type
=> make the real dom generic over custom types

packages/native-core/Cargo.toml, packages/native-core/src/layout_attributes.rs
Lightning css published a new alpha version with some minor breaking changes making CI fail. This PR updates to the latest version
=> bump lightningcss version

packages/core/src/scheduler/task.rs, packages/core/src/scheduler/wait.rs
This fixes a panic when the future scheduler tries to remove a future that has already completed or been removed.
fixes #681
=> Handle removing a future that does not exist

packages/core/src/scopes.rs
This improves the error message when a user tries to create nested hooks from
```already borrowed: BorrowMutError```
to
```The hook list is already borrowed: This error is likely caused by trying to use a hook inside a hook which violates the rules of hooks.: BorrowMutError```
=> improve error message when a user tries to use nested hooks

packages/interpreter/src/interpreter.js
This PR removes some console.logs from the js interpreter. These can cause performance issues and clutter the console.
closes #737
=> Remove logs from interpreter

examples/fermi.rs
The Fermi example is missing a use_init_atom_root in the root component which causes it to panic
closes #734
=> Fix Fermi example

packages/html/src/web_sys_bind/events.rs, packages/web/src/dom.rs
This fixes drag* events being transmitted as MouseData instead of DragData causing drag events to never fire
=> Fix drag* events on the web renderer

packages/native-core/src/passes.rs, packages/native-core/src/real_dom.rs
This unifies dirty nodes and dirty nodes states in native-core. This improves performance by between 10-30% on the tui update benchmark depending on the size of the boxes (with smaller updates having a larger performance improvement).
=> Unify DirtyNodes and DirtyNodeStates in native core

packages/core/src/arena.rs, packages/core/src/diff.rs, packages/core/src/scopes.rs
Fixes futures being polled after a scope it is spawned in is removed.
Eg:
```rust
fn main() {
}
let count = if cx.generation() % 2 == 0 { 10 } else { 0 };
if cx.generation() < 5 {
cx.needs_update();
}
render! {
(0..count).map(|_| rsx!{
rsx!{
Comp {}
}
})
}
}
#[derive(Props)]
struct RebuildProps {}
impl PartialEq for RebuildProps {
fn eq(&self, _: &Self) -> bool {
false
}
}
fn Comp(cx: Scope<RebuildProps>) -> Element {
let id = cx.scope_id();
cx.spawn(async move {
loop {
tokio::time::sleep(std::time::Duration::from_millis(10)).await;
println!("Hello from {id:?}");
}
});
render! {
"Hello"
}
}
```
Should only print a few messages at most, instead it currently prints messages forever. This can also cause …
=> Drop futures when the scope that spawned them is dropped

packages/core/src/arena.rs, packages/core/src/diff.rs, packages/core/src/nodes.rs, packages/core/src/virtual_dom.rs
Follow up to #771 to fix some subtle bugs
1) Some rendering cases cause node id's to be reclaimed twice. Once when the scope was dropped and once when generating mutations to remove nodes (causing this failure: https://github.com/DioxusLabs/dioxus/actions/runs/3925259917/jobs/6710058694)
2) Scopes never being removed when the component that owns them is removed
=> Fix duplicated work on dropping scopes

packages/autofmt/src/expr.rs, packages/autofmt/src/lib.rs, packages/autofmt/tests/samples.rs, packages/autofmt/tests/samples/immediate_expr.rsx
The alignment for rendering short exprs was off. This fixes that.
=> fix: immediate exprs in autofmt

packages/core-macro/src/inlineprops.rs
=> Inline props should use cx token instead of `cx`

examples/window_focus.rs, packages/desktop/Cargo.toml, packages/desktop/src/cfg.rs, packages/desktop/src/desktop_context.rs, packages/desktop/src/lib.rs
Exposes a callback for the web view renderer to allow users to listen for web view and window events.
=> Create with_event_handler to expose window event on desktop

.github/workflows/docs stable.yml
Creates a manually triggered workflow to publish the docs on the stable directory instead of nightly
=> Stable Docs Workflow

packages/native-core/src/real_dom.rs
This fixes dynamic text nodes not adding their ids to the element id -> node id mapping causing replacing dynamic text nodes to fail
This fixes a bug encountered in #788
=> Fix replacing a dynamic text node in native core

packages/native-core/src/layout_attributes.rs, packages/tui/src/layout.rs
This applies the medium border width for layout when the style is set to match the behavior of browsers. It also adds a layout config that allows you to set the thin, medium, and thick border widths.
=> Apply medium width when the border style is not none to match browsers

packages/native-core/src/utils/cursor.rs, packages/tui/src/widgets/number.rs, packages/tui/src/widgets/password.rs, packages/tui/src/widgets/textbox.rs
This improves the documentation around the cursor and makes the cursor usable with anything that acts like text instead of just &mut String. This is useful for libraries like Freya that use a [rope](https://docs.rs/ropey/latest/ropey/struct.Rope.html#) instead of text for more efficient text editing.
=> Make text editing utilities in native core agnostic over the text storage

examples/README.md
An example was removed in https://github.com/DioxusLabs/dioxus/commit/c4a18bc24d8722dda6c7c432a18f11671046718a but is stuck in README still.
Additionally, all tui_* examples were removed at some point too. Synched it up with README.
=> Clean up removed examples from examples/README.md

packages/core/Cargo.toml, packages/core/src/arena.rs, packages/core/src/create.rs, packages/core/src/diff.rs, packages/core/src/scheduler/wait.rs, packages/core/src/scope_arena.rs, packages/core/src/scopes.rs, packages/core/src/virtual_dom.rs
Scope states are currently individually boxed which causes each scope state to create a new memory allocation when created and deallocation when removed. If this box is removed, the Vec backing the slab will often have memory pre-allocated that can be used instead of calling the global allocator. 
This is especially useful any time scopes are created and then destroyed. For example this benchmark is ~15% without boxing scope states:
```rust
use criterion::{criterion_group, criterion_main, Criterion};
use rand::prelude::*;
criterion_group!(mbenches, create_rows);
criterion_main!(mbenches);
fn create_rows(c: &mut Criterion) {
let num = if cx.generation() % 2 == 0 { 10_000 } else { 0 };
render!(
table {
tbody {
(0..num).map(|f| {
let …
```
=> do not box scope states

packages/interpreter/src/interpreter.js
Adds the mouse data under the mouse field instead of serializing the mouse data directly for drag events
fixes #796
=> Fix drag event serialization in JS interpreter

packages/liveview/Cargo.toml
Closes #798 
Widening support for the `tokio` crate to version `1.22.0` in the `[dependencies.tokio]` and `[dev-dependencies.tokio]`.
This change will enable compatibility with `shuttle-service` crate.
=> `chore:` change `tokio` to support `shuttle-service`

packages/hooks/src/lib.rs, packages/hooks/src/usememo.rs
Adds a use_memo hook for memorizing values. This builds off of the work done on use_effect, but unlike use effect this hook does not spawn a future.
=> Add use_memo hook

packages/native-core/src/real_dom.rs
Remove unnecessary 'static lifetime from `RealDom::get_listening_sorted`
=> Remove unnecessary 'static lifetime

packages/interpreter/src/sledgehammer_bindings.rs
Fixes a typo in the sledgehammer bindings that causes removing attributes to fail. The code uses a nodes variable elsewhere, not this.nodes.
=> fix removing attributes in web sledgehammer bindings

examples/button.rs, packages/core/src/events.rs, packages/core/src/lib.rs, packages/core/src/scopes.rs, packages/html/src/events.rs
Allows async event handlers for the HTML crate by adding support to Dioxus Core.
This is useful with crates like dioxus-signal which give a static handle to some state.
=> Async event handlers

docs/guide/src/en/getting_started/tui.md
Fixes the link to the TUI widgets example in the guide
=> Fix the tui widgets example link

.github/workflows/miri.yml
This changes the Miri workflow to only run on PRs that are ready like all the other check workflows.
=> Don't run miri workflow on draft PRs

packages/core/src/diff.rs
fixes #821
This changes the push all real nodes from counting the nodes created to summing them to get the true total
=> Fix keyed diffing with fragment node children

packages/ssr/src/renderer.rs
Fixes a typo in ssr causing placeholder elements to render incorrectly
=> Fix pre tag typo

README.md, docs/posts/release.md, docs/reference/src/README_pt-br.md, docs/reference/src/platforms/desktop.md, notes/README/ZH_CN.md, packages/autofmt/README.md, packages/core-macro/README.md, packages/desktop/README.md, packages/desktop/src/readme.md, packages/dioxus/README.md, packages/hooks/README.md, packages/html/README.md, packages/interpreter/README.md, packages/liveview/README.md, packages/mobile/README.md, packages/native-core-macro/README.md, packages/native-core/README.md, packages/router/README.md, packages/rsx-rosetta/README.md, packages/rsx/README.md, packages/web/README.md, translations/pt-br/README.md
When translate support was added it added an extra segment for the language in the url. This updates all the links to the docs to include that extra segment.
This PR is done, but it currently breaks the links: **do not merge until the docs are published as stable**
=> Update guide doc links

packages/hooks/src/usecoroutine.rs, packages/hooks/src/usestate.rs
Add `PartialEq`-implementation for `dioxus_hooks::Coroutine` and `dioxus_hooks::UseState`.
Both are good candidates to pass as a prop. `UseState` already implements `PartialEq`, but I removed the trait bound on T.
=> PartialEq for UseState/UseCoroutine

packages/hot-reload/src/lib.rs
This fixes hot reloading on [some systems](https://discord.com/channels/899851952891002890/1078309848044818503/1078393581821239306) where the @ symbol in a path is not allowed and is the method recommended by interprocess.
When this is released TUI, Liveview, Desktop, and dioxus-hot-reload must all be bumped at the same time
=> [Hot reloading] use namespaced path instead of temp directory

packages/core/src/scopes.rs
Fixes some outdated docs on provide context about not replacing values and not requiring clone
=> Fix the provide context docs

packages/core-macro/src/inlineprops.rs
Fixes trait bounds on generics in components created with inline_props.
For example this PR fixes this component:
```rust
#[inline_props]
pub fn TakesNum<N: Into<usize>>(cx: Scope, n: N) -> Element {
render! {
div{}
}
}
```
=> Fix trait bounds on generics with inline_props

docs/guide/src/en/getting_started/desktop.md, docs/reference/src/platforms/desktop.md, examples/shortcut.rs, packages/desktop/src/desktop_context.rs, packages/desktop/src/lib.rs, packages/desktop/src/readme.md, packages/desktop/src/shortcut.rs
closes #855 
The API here is similar to what was outlined in #751 for custom handlers.
There are methods to add and remove shortcuts on the desktop context and a use_global_shortcut hook that will create a shortcut that will be removed when the hook is dropped.
The same method of creating shortcuts is also used to override CTRL+R to fix ctrl+r breaking all apps as a follow up to #75
=> Create global shortcut handler for Dioxus desktop

packages/rsx/Cargo.toml, packages/rsx/src/hot_reload/hot_reloading_file_map.rs
Fixes hot reloading for child crates in workspaces with the macro and CLI
closes #848
=> Fix hot reloading in a workspace

docs/guide/examples/hooks_composed.rs, packages/hooks/Cargo.toml, packages/hooks/src/use_shared_state.rs
closes #858 
This makes it possible to use UseSharedState within futures while maintaining updates by moving the lifetime out side of UseSharedState. This also makes it more similar to the behavior of UseRef and UseState which do not have interior lifetimes.
Because UseSharedState is now clone without lifetime restrictions we no longer need ProvidedStateInner, or .inner to be public.
It also documents the remaining items in UseSharedState and adds examples.
Overview of the new API (very similar except you can now use it in a use_future block, etc):
```rust
#[derive(Clone, Copy, PartialEq)]
enum Theme {
Light,
Dark,
}
fn Parent<'a>(cx: Scope<'a>) -> Element<'a> {
use_shared_state_provider(cx, || Theme::Dark);
let theme = use_shared_state::<Theme>(cx).unwrap();
use_future(cx, (theme,), …
```
=> Make use_shared_state usable in static futures

packages/interpreter/src/interpreter.js
closes #836 
Very similar to https://github.com/DioxusLabs/dioxus/pull/835 except it respects a prevent_default on the <a> tag that the event is bubbled to
=> Fix anchor link for block-level elements

README.md
This fixes the Guide link in the README, at the cost of pinning the link to version 0.3.  I couldn't find a way to get to the guide without 0.3 being in the URL, but maybe there's another way, like a `/docs/guide/` that aliases to latest?
=> fix Guide link in README

docs/router/src/README.md, packages/router/README.md
This tripped me up while setting up my first Dioxus app for deployment in a browser. I believe this changed from 0.2 -> 0.3.
=> Update Router book to reflect crate separation and need for `web` feature.

packages/core/src/arena.rs, packages/core/src/virtual_dom.rs
The code to propagate events within a single template was checking if the listener was attached to an element that was an (indirect) child of the element of the element where the event was triggered. This PR changes it to check if it is an (indirect) parent of the element where the event was triggered.
Closes #867
=> Fix event bubbling within a single template

packages/core/src/scheduler/task.rs
Very rarely a future attempts to wake while the application is shutting down which causes a panic.
This PR ignores the error instead of panicing when a future is polled during shutdown.
For example in this application if you open a several windows and close them it sometimes panics:
```rust
#![allow(non_snake_case)]
use dioxus_desktop::use_window;
fn main() {
}
for _ in 0..100 {
cx.spawn(async move {
loop {
print!("!");
tokio::time::sleep(std::time::Duration::from_millis(1)).await;
}
});
}
let window = use_window(cx);
cx.render(rsx! {
div {
button {
onclick: move |_| {
let dom = VirtualDom::new(popup);
window.new_window(dom, Default::default());
},
"New Window"
}
button {
onclick: move |_| window.close(), …
```
=> Fix panic when waking future on shutdown

docs/guide/src/en/async/use_coroutine.md
Noted that there was no mention of the trait extension (StreamExt) in the docs when trying to send messages via a UnboundedReceiver. For me it was quite confusing where the ".next()" method came from, but figured it out by looking at the test cases. Added a short note/mention of it in the docs.
=> Added mention of StreamExt trait extension.

packages/rsx/src/ifmt.rs
Makes inline formatting slightly more flexable by allowing paths.
closes #901
=> Allow paths in format expressions

packages/ssr/src/cache.rs, packages/ssr/src/renderer.rs, packages/ssr/tests/styles.rs
Fixes rendering style attributes in SSR rendering. Currently they are rendered as normal attributes.
This adds a new marker to the pre-rendered template to mark where dynamic styles should be inserted (either after the static styles, or at the end of the attributes). It also adds tests for static, mixed, and dynamic styles. 
This does result in more dynamic allocation, which could effect performance slightly, but the objects that are allocated should be very small (Vecs of references).
=> Fix style attributes in SSR

packages/desktop/src/cfg.rs, packages/desktop/src/webview.rs
Expose a new data directory option in the config forwarded from wry. This makes it possible to install bundled applications on windows in the the Program Files directory  with https://github.com/DioxusLabs/cli/pull/118 (see [this](https://docs.rs/wry/latest/wry/webview/struct.WebContext.html#method.new) comment).
=> Expose the data directory in the desktop config

packages/core/src/mutations.rs
Fixes a few places in the mutations documentation that were unclear or unfinished.
=> Clarify mutations docs

packages/core/src/diff.rs
When diffing lists, the Virtual Dom will sometimes insert mutations that do nothing like appending no children or inserting no nodes before or after a node. This checks for those cases and only inserts mutations when needed
=> Don't add no op mutations when diffing lists

packages/fermi/README.md
Partially closes #660, the other half is in DioxusLabs/docsite#59.
The Fermi snippet on the website shows an increment/counter example that doesn't work. The reporter also mentioned the Fermi readme had the same issue, but it's been fixed with the 0.3 release I think.
However the examples in the readme only show reading, and overwriting the value, but a newcomer wouldn't be able to figure out the common scenario of updating a value based on itself (i.e. counters). I added this example:
> If needed, we can update the atom's value, based on itself:
```rust, ignore
static COUNT: Atom<i32> = |_| 0;
fn Counter(cx: Scope) -> Element {
let mut count = use_atom_state(cx, COUNT);
cx.render(rsx!{
p {
"{count}"
}
button {
onclick: move |_| count += 1,
"Increment counter"
}
})
}
```
=> doc: fermi: add counter example to readme

packages/core/src/create.rs, packages/core/src/diff.rs
When an event bubbles up the tree after a component rerenders, the bubbling code will attempt to read a node ref that has become out of date because we don't always update the node refs at the root of the element. This changes the code to always update those node refs.
To reproduce this bug, check out this PR on blitz (https://github.com/DioxusLabs/blitz/pull/22) and run the buttons example. Click the add buttons button twice and hit tab. On windows this causes a seg fault.
=> Always update root node refs

packages/web/src/rehydrate.rs
Fix hydration of listeners with events that do not bubble. The event_bubbles function checks if a event (without the on prefix) bubbles or not and defaults to true. This was always returning true because the code was passing in the on prefix and the event was never being found.
=> Fix non-bubbling listener hydration

packages/desktop/src/webview.rs
Seems to be an issue in wry where passing the data directory pointer doesn't follow proper lifetime rules.
This just comments out the webcontext code. We should find a long term solution - like leaking the webcontext.
=> Hotfix wry segfaulting by commenting out webcontext

packages/ssr/src/cache.rs, packages/ssr/src/renderer.rs, packages/ssr/tests/inner_html.rs
fixes #941 
Similar to #904 this adds a marker for where dynamic dangerous inner html attributes could be inserted when there is any dynamic attributes, or inserts static dangerous inner html them into the templates.
=> Fix dangerous_inner_html with SSR

packages/desktop/Cargo.toml, packages/desktop/src/cfg.rs, packages/desktop/src/lib.rs, packages/desktop/src/protocol.rs, packages/desktop/src/webview.rs
When wry is building an innerwebview, it will either push the custom protocols to its own struct field, or it will add it to the web context. The problem comes when web context is dropped prematurely. Then, the obj c trickery wry uses doesn't know how to handle the protocols and segfaults. 
Wry is actually *supposed* to have some logic (in the attached image) to not handle the protocol if web context is dropped, but it seems like they haven't quite handled it correctly. Maybe they should unset the ivar when a WebContext is dropped? I'm not an expert on unsafe or objc so idk lol.
This pr just stores the web context in a WebViewHandler, but there's probably a better way to do it.
Also, I went ahead and updated wry to the latest stable release to make sure nothing else fishy is going on.
=> Add web context back and ensure it isn't dropped prematurely.

packages/web/src/cfg.rs
Updates the docs for the cache option on the web config.
Most strings are currently passed through sledgehammer instead of WASM bindgen, so caching custom strings in wasm bindgen is much less useful. Sledgehammer does not cache strings in the same way as wasm-bindgen. It can lazily cache strings in a LRU cache by value or by pointer for static strings, but it does not currently accept a list of strings to pre-cache. Currently this just adds a note that the cache is only used when creating static elements and attributes. In the future I would like to support this feature in sledgehammer bindgen.
Fixes #919
=> Update docs for the web cfg cache option

.github/workflows/main.yml, docs/guide/src/en/getting_started/desktop.md, packages/desktop/src/lib.rs
When wry was updated the required version of libwebkit2gtk was updated. This bumps the version in CI and docs to hopefully fix the Linux CI
=> Fix Linux Wry dependencies

packages/native-core-macro/src/lib.rs, packages/native-core/examples/font_size.rs, packages/native-core/src/lib.rs, packages/native-core/src/passes.rs, packages/native-core/src/real_dom.rs
Fixes state that invalidate other states in a different direction than the pass direction. For example, in the new font-size example, the size depends on the font size on the current node and itself on the parent node. Previously when the font size was updated, the size did not update. This PR fixes that issue.
=> Fix native core dependencies in a different direction than the pass direction

packages/interpreter/Cargo.toml
Fixes a regression in sledgehammer-bindgen `0.2` for non-ascii string decoding on small strings.
Fixes #961
=> Fix non-ascii string decoding

examples/svg.rs
fixed the rng range so that a 6 can be rolled
=> fix rng in svg dice example

examples/generic_component.rs
Improves the generic component example to use the generic parameter which fixes the clippy CI error in the main branch
=> Fix clippy in the generic component example

packages/rink/src/lib.rs
Problem: Key events were delayed signifantly in TUI widgets.
Solution: Decrease crossterm event poll timeout from 1000ms to 10ms.
Fixes #978
=> fix: change crossterm poll timeout to 10ms from 1s

packages/native-core/Cargo.toml
Remove an unused shipyard-hierarchy dependency from native core that causes the parallels feature to be enabled in shipyard which impacts performance of Blitz, TUI, and Freya
=> Remove unused shipyard-hierarchy

packages/router/src/components/route.rs, packages/web/src/lib.rs
Switches debug logs in the router and web crates to traces. (This was done in https://github.com/DioxusLabs/dioxus/pull/334, but reverted at some point)
=> Switch debug logs to trace in the router and web crates

packages/autofmt/src/element.rs, packages/rsx-rosetta/Cargo.toml, packages/rsx-rosetta/tests/simple.rs
The autoformat package assumes that the source is non-empty, but `write_block_out` does not supply a source. This fixes the code to allow an empty source string. It also adds some tests to check the behavior of rsx-rosetta
fixes #943
=> Fix HTML to RSX conversions example

packages/liveview/Cargo.toml
If you try to run cargo check in the LiveView package, it fails because it uses a macro that is not active in the tokio features. This was succeeding in CI because other packages were using the full Tokio features which results in all packages being compiled with all tokio features.
=> Fix LiveView Tokio features

packages/html/src/events/form.rs, packages/interpreter/src/interpreter.js, packages/web/src/dom.rs
This uses the [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData/FormData) API to extract form data instead of our manual implementation. This works with more inputs. This is a breaking change because the type of values in form data changes from String to Vec<String> to support select inputs with the multiple attribute.
fixes #625
=> Fix form events with select multiple

packages/html/src/events/form.rs
Fixes form events on desktop broken in #965. (I only noticed this issue when updating other PRs with the changes)
Form events on desktop never contain the file field which causes crashes when deserializing input events. This PR makes the field optional when deserializing which fixes the issue
=> make files optional when deserializing form data

docs/guide/examples/event_prevent_default.rs, docs/guide/src/en/interactivity/event_handlers.md, packages/interpreter/src/interpreter.js, packages/web/src/dom.rs
At the moment, the DOM interpreter expects only one event to prevent the default behavior. This pr allows defining multiple events separated by spaces and prevent all of them.
This is the most straightforward way to do it, but maybe the code should be reviewed to be simplified.
Fixes  #535
=> Allow multiple prevent default for Web, Desktop and LiveView

docs/guide/src/en/custom_renderer/index.md, docs/guide/src/en/getting_started/tui.md
Fixes 'widgets example' link in 1.5 of the guide
=> Fix the link to tui widgets in the guide

packages/html/src/elements.rs
The [`<hgroup>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hgroup) HTML element represents a heading and related content. It groups a single `<h1>–<h6>` element with one or more `<p>`.
Closes #1013
=> Add `hgroup` html tag

packages/hooks/src/usecoroutine.rs
Adds a mention to ``futures-util`` in order to use ``rx.next().await``.
=> Mention futures-util in use_coroutine hook

docs/guide/src/en/interactivity/router.md, docs/guide/src/pt-br/interactivity/router.md
Currently the link to the [router book](https://dioxuslabs.com/docs/0.3/router/) is broken on the [routing](https://dioxuslabs.com/docs/0.3/guide/en/interactivity/router.html#more-reading) section in the docs. The same link can be accessed from the top navigation, but it's better if this one works too.
=> fix router book link

packages/dioxus-tui/Cargo.toml, packages/native-core/Cargo.toml, packages/native-core/src/layout_attributes.rs, packages/rink/Cargo.toml, packages/rink/src/layout.rs, packages/rink/src/lib.rs
Add CSS Grid support to dioxus's native renderers
- Upgrade to Taffy to 0.3.x (in `native-core` and `rink`)
- Add support for parsing CSS Grid styles into Taffy's `Style` struct
=> Support CSS Grid (+upgrade Taffy to 0.3.x)

packages/web/src/dom.rs
Fixes #1003 
The current web bubbling code assumes events are only triggered on element nodes but it appears some browsers can trigger events with a target on a text node. This PR changes the bubbling on the web renderer to handle the case when the event target is not an element. It should not effect browsers that do not have this behavior
=> Fix web events starting on a text node

docs/guide/Cargo.toml, docs/guide/examples/hooks_anti_patterns.rs, docs/guide/examples/hooks_composed.rs, docs/guide/examples/hooks_custom_logic.rs, docs/guide/src/en/interactivity/custom_hooks.md
Extends the Custom Hooks chapter in the guide with:
- Examples
- Web Storage synchronized hook example
- Simplified implementations of use_state, use_context, use_context_provider
- Custom hook antipatterns
=> Improve the custom hooks chapter in the guide

packages/hot-reload/src/lib.rs
If you try to hot reload multiple changes per second, the hot reloading code trys to deduplicate those events and only accepts the first edit. This happens because the timestamps of the events happen in the same second. This increases the accuracy of the timestamp to milliseconds to fix the issue.
=> Use more precise timestamp in hot reloading

packages/desktop/Cargo.toml, packages/desktop/src/protocol.rs
Fixes #1034 
Wry gives precent encoded urls for requests. This PR decodes those urls into real paths for characters like ` `
=> Fix URL encoded desktop assets

Cargo.toml, notes/CONTRIBUTING.md, packages/dioxus/Cargo.toml, packages/hot-reload/Cargo.toml, packages/liveview/Cargo.toml
Closes #1048 (the red part, at least).
* This removes the `time` (red) advisory.
* env_logger is updated from `0.9.0` to `0.10.0`.
I also added some `CONTRIBUTING.md` notes, but only enough to get tests running.
Partially addressed in this PR:
* `atty`, I've updated a few packages, but `simple_logger` and `colored` still depend on it, so we'd have to fix https://github.com/borntyping/rust-simple_logger/issues/74 first.
* `criterion` can be bumped to `0.5.1`, but I haven't had time to do that -- tests fail with an obscure message: ``"for `dioxus-desktop::check_rendering`, line 'html: <div .. </div>' did not end with the string ': test' or ': benchmark'"``.
* `kuchiki` needs https://github.com/tauri-apps/wry/issues/898 fixed.
=> Adjust `chrono` features to address security advisory.

examples/web_component.rs, packages/rsx-rosetta/src/lib.rs, packages/rsx/src/element.rs, packages/rsx/src/lib.rs, packages/rsx/src/node.rs
closes #893 
A different idea for quicker custom elements. Allows inline custom elements. This does not allow the typesafety of normal elements. It is very similar to raw attribute names surrounded by quotes. This is useful for one use components, for libraries and components that are used many times #539 would be a better solution
```rust
fn main() {
}
cx.render(rsx! {
web-component {
"my-prop": "5%",
}
})
}
```
Why not use quotes like custom attributes use:
```rust
fn main() {
}
cx.render(rsx! {
"web-component" {
"my-prop": "5%",
}
})
}
```
Currently commas are optional between custom elements and raw expression, so this …
=> Allow raw elements if they include a dash

packages/core/src/diff.rs
Fixes #846 
Because we expose the handle_event on the virtual method which dereferences an arbitrary element id pointer, we always need to update the references for element ids, even if we never use the reference internally.
=> Update All Element Ids

packages/liveview/src/lib.rs
Previous PR #1063 changed how the javascript interpreter code is handled. Liveview didn't have the necessary changes to accommodate the new JS organization. (Hopefully this is the last thing that #1063 broke 👀)
=> Fix liveview interpreter JS

packages/core/src/virtual_dom.rs
Hello! I was just trying out the TUI examples and noticed this `dbg!` was causing problems on the screen
After removing the dbg everything seems to be working fine! :)
=> fix: Remove dbg that was causing TUI rendering problems

packages/desktop/src/query.rs
Increase the number of tokio channels for the query engine from 8 to 1000. This fixes issues where making many calls to `eval` or `unmounted` would cause said calls to fail with error `Error receiving query result: channel lagged by 8`.
Solves https://github.com/DioxusLabs/dioxus/issues/1092
=> Increase the size of the queue for the query engine

.github/workflows/macos.yml, .github/workflows/main.yml
Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/DioxusLabs/dioxus/actions/runs/5212800825:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1, actions-rs/cargo@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of those warnings the occurrences of `actions-rs/toolchain` are replaced by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain), and the occurrences of `actions-rs/cargo` are replaced by direct invocations of …
=> replace unmaintained actions-rs/* actions in CI workflows

Cargo.toml, packages/autofmt/Cargo.toml, packages/core-macro/Cargo.toml, packages/core/Cargo.toml, packages/desktop/Cargo.toml, packages/dioxus-tui/Cargo.toml, packages/dioxus/Cargo.toml, packages/fermi/Cargo.toml, packages/fullstack/Cargo.toml, packages/fullstack/examples/axum-desktop/Cargo.toml, packages/fullstack/examples/axum-hello-world/Cargo.toml, packages/fullstack/examples/axum-router/Cargo.toml, packages/fullstack/examples/salvo-hello-world/Cargo.toml, packages/fullstack/examples/warp-hello-world/Cargo.toml, packages/hooks/Cargo.toml, packages/hot-reload/Cargo.toml, packages/html/Cargo.toml, packages/interpreter/Cargo.toml, packages/liveview/Cargo.toml, packages/mobile/Cargo.toml, packages/native-core-macro/Cargo.toml, packages/native-core/Cargo.toml, packages/rink/Cargo.toml, packages/router/Cargo.toml, packages/rsx-rosetta/Cargo.toml, packages/rsx/Cargo.toml, packages/signals/Cargo.toml, packages/ssr/Cargo.toml, packages/web/Cargo.toml
Updates the dependencies that are used commonly across Dioxus crates to use [workspace dependencies](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table). This should be helpful keeping the versions of crates across the workspace synced and make it easier to move packages.
=> Workspace Dependancies

packages/hot-reload/src/lib.rs
Closes https://github.com/DioxusLabs/dioxus/issues/1037
When desktop programs with hot reloading enabled on Mac are stopped, it can result in the file channel being left open. This PR closes any left over open file channels before starting hot reloading on macos.
=> Fix restarting MacOs hot reloading after a forced exit

packages/hot-reload/Cargo.toml, packages/hot-reload/src/lib.rs
I had to publish a new version of interprocess that fixes the docs issue, but now we can get interprocess properly creating docs, and thusly, our published versions can create docs.
=> Fix `cargo doc` by using a fixed variant of interprocess

packages/router/tests/web_router.rs, packages/rsx/src/component.rs
fixes #876 
It appears that commas are already optional for non-string attribute values in components. This PR makes it optional for all component attributes
=> Don't accept raw attributes in components without trailing commas

packages/interpreter/src/common.js, packages/interpreter/src/sledgehammer_bindings.rs
Checks if boolean attributes are equal to either the value `true` or the string `"true"` before choosing to either add or remove the attribute
fixes https://github.com/DioxusLabs/dioxus/issues/1086
=> Fix boolean attributes with raw boolean values

packages/core-macro/Cargo.toml, packages/core-macro/tests/rsx.rs, packages/core-macro/tests/rsx/trailing-comma-0.rs, packages/core-macro/tests/rsx/trailing-comma-0.stderr, packages/rsx/src/element.rs
First time contributing, let me know if something should be different e.g. where I place the test and so on (or if you disagree with the PR altogether).
I noticed if I forget a trailing comma, the span info pointed to the span _before_ the one I expected.
```rust
// user code
rsx!{
p { class: "foo bar" 
"hi"
}
}
// stderr before
error: missing trailing comma
--> tests/rsx/trailing-comma-0.rs:9:20
|
9 |             class: "foo bar"
|             ^^^^^
// stderr after
error: missing trailing comma
--> tests/rsx/trailing-comma-0.rs:9:20
|
9 |             class: "foo bar"
|                    ^^^^^^^^^
```
So I changed the span to the one after, and added a test to verify the new stderr.
=> Change missing trailing comma span to be more helpful

examples/window_focus.rs, packages/desktop/Cargo.toml, packages/desktop/src/cfg.rs, packages/desktop/src/lib.rs
This implements the functionality outlined in the following issue:
https://github.com/DioxusLabs/dioxus/issues/1122
For macOS, it adds the `objc` dependency as that is required to call the correct selector, `[NSApplication hide:]`. This will hide the window in a way that it appears again when the user switches back to the app.
On Linux or Windows clicking the icon in the tab bar should make it visible again.
=> Window Close Behaviour

Cargo.toml, packages/cli/Cargo.toml, packages/cli/src/cli/build/mod.rs, packages/cli/src/cli/mod.rs, packages/cli/src/cli/plugin/mod.rs, packages/cli/src/lib.rs, packages/cli/src/main.rs, packages/cli/src/server/mod.rs
We want to alias dioxus to dx now, so the easiest way is to install both so people aren't confused.
`dx` = `dioxus` on the CLI.
Kinda like vc = vercel.
Also, this pulls out the plugin system into a feature to help reduce build times. They're still quite long :/
=> Feat: add `dx` as a package and move plugin to feature

packages/autofmt/Cargo.toml, packages/cli/Cargo.toml, packages/core-macro/Cargo.toml, packages/core/Cargo.toml, packages/desktop/Cargo.toml, packages/dioxus-tui/Cargo.toml, packages/dioxus/Cargo.toml, packages/fermi/Cargo.toml, packages/fullstack/Cargo.toml, packages/hooks/Cargo.toml, packages/hot-reload/Cargo.toml, packages/html/Cargo.toml, packages/interpreter/Cargo.toml, packages/liveview/Cargo.toml, packages/mobile/Cargo.toml, packages/native-core-macro/Cargo.toml, packages/native-core/Cargo.toml, packages/rink/Cargo.toml, packages/router/Cargo.toml, packages/ssr/Cargo.toml, packages/web/Cargo.toml
- Updated some descriptions to make them more clear
- Removed `documentation` links so they get filled with the generated link from `docs.rs`
- Updated some `homepage` links with platform-specific guides (e.g desktop, tui, ssr, etc)
Feel free to edit anything you think didn't have to be modified 👍
=> fix: Remove duplicated doc links and improved some descriptions

examples/signals.rs, packages/core-macro/tests/ifmt.rs, packages/core/src/scopes.rs, packages/hooks/src/lib.rs, packages/hooks/src/userootcontext.rs, packages/signals/src/lib.rs
This PR re-adds provide_root_context so crates like signals, routers, etc can lazily initialize their singletons from anywhere in the app.
This could be considered "magic" but I'm leaning more towards the idea that these are singleton objects that are *meant* to be at the top of your app. It would not make sense to have multiple signal runtimes or multiple routers in a single app. These libraries should provide their own mechanisms for "subtrees" that can be built around this behavior.
```
Provide a context to the root and then consume it
This is intended for "global" state management solutions that would rather be implicit for the entire app. Things like signal runtimes and routers are examples of "singletons" that would benefit from lazy initialization.
Note that you should be checking …
```
=> Re-add provide_root_context for lazy singleton initialization

packages/cli/src/config.rs, packages/cli/src/main.rs
Previously an invalid `Dioxus.toml` file would yield this error when running e.g. `dx serve`:
```
Error: Failed to load `Dioxus.toml` because: Dioxus.toml parse failed
```
This doesn't give any indication why it failed to parse. This commit updates it to include why the parsing failed, e.g.:
```
Error: Failed to load Dioxus config because: Dioxus.toml missing field `name` for key `application` at line 38 column 1
```
I initially had it format the message to include `Dioxus.toml:38:1` to be clickable in some terminals, but the location specified didn't always seem particularly relevant to the actual problem so I left it as-is.
This also fixes what I believe would be an issue on case-sensitive file systems where if `dioxus.toml` existed it would try to read `Dioxus.toml`.
I'm still fairly …
=> fix(cli): improve error message for invalid config

docs/router/src/guide/getting-started.md
PR is largely self-explanatory.
The [Getting Started page for the Dioxus Router](https://dioxuslabs.com/docs/0.3/router/guide/getting-started.html) says we should use:
`rustup target add wasm32-unkown-unknown`, however the correct target is
`rustup target add wasm32-unknown-unknown`.
This PR adds the missing `n` to the first `unknown`.
=> Fixed typo in Router guide getting-started.md

examples/dog_app.rs, packages/core/Cargo.toml, packages/core/src/any_props.rs, packages/core/src/create.rs, packages/core/src/diff.rs, packages/core/src/lib.rs, packages/core/src/nodes.rs, packages/core/src/properties.rs, packages/core/src/scheduler/mod.rs, packages/core/src/scheduler/suspense.rs, packages/core/src/scheduler/wait.rs, packages/core/src/scope_arena.rs, packages/core/src/scopes.rs, packages/core/src/virtual_dom.rs, packages/core/tests/safety.rs, packages/core/tests/suspense.rs, packages/hooks/src/usefuture.rs
This PR rips out async components, once again enabling us to use anything that implements `IntoIterator<T: IntoTemplate>`. It makes our suspense system simpler, with the limitation that it's really only useful for SSR.
Loading states are not implemented, so components will be blank until their data is ready.
This is being done in a forward-compatible way, so we can add loading states and tree-based suspense later into the 0.4 release.
=> Rip out async components in favor of a simpler suspense

packages/core/src/scopes.rs, packages/liveview/src/adapters/axum_adapter.rs, packages/liveview/src/adapters/salvo_adapter.rs, packages/liveview/src/adapters/warp_adapter.rs, packages/liveview/src/pool.rs, packages/signals/src/lib.rs
This makes changes to the liveview renderer to prepare for #695. This is the only breaking change that moving to sledgehammer will require for liveview. Sledgehammer bindgen will require a stream of bytes instead of a stream of strings. Integrating with sledgehammer will be done after 0.4, but after this PR it should be a non-breaking change.
=> Prepare for Sledgehammer Bindgen in Liveview

.github/workflows/docs stable.yml, .github/workflows/docs.yml, .github/workflows/macos.yml, .github/workflows/main.yml, .github/workflows/miri.yml, .github/workflows/playwright.yml, .github/workflows/windows.yml
Uses concurrency features of github actions to prevent us from draining CI for hours.
=> Kill previous CI jobs when new pushed

packages/core/src/create.rs, packages/core/src/diff.rs, packages/core/src/nodes.rs, packages/core/src/scope_arena.rs, packages/core/src/virtual_dom.rs, packages/core/tests/task.rs, packages/dioxus-tui/examples/colorpicker.rs, packages/web/src/rehydrate.rs
Removes 9 instances of unsafe by using a Refcell<vec> instead of UnsafeCell<Box>.
Should also be less to compile.
There's a small overhead but the hinting to the branch predictor should be basically negligible.
=> Don't use boxed cell slice, use a refcell instead

packages/autofmt/Cargo.toml, packages/autofmt/src/collect_macros.rs, packages/autofmt/src/component.rs, packages/autofmt/src/element.rs, packages/autofmt/src/expr.rs, packages/autofmt/src/lib.rs, packages/cli/src/cli/autoformat.rs
Fixes a few issues I ran into while trying to get autofmt to work for the docsite. Mainly handlers with multiple lines and multi-line raw attributes were not formatted correctly
=> Improve auto formatting multiline raw attributes/event handlers

.github/workflows/miri.yml, packages/core/Cargo.toml, packages/core/src/arena.rs, packages/core/src/diff.rs, packages/core/src/scheduler/wait.rs, packages/core/src/scope_arena.rs, packages/core/src/scopes.rs, packages/core/src/virtual_dom.rs, packages/core/tests/fuzzing.rs, packages/core/tests/suspense.rs, packages/core/tests/task.rs
While working on #1225 I noticed that miri isn't passing in one of our tests. I think it's a new regression.
This change expands our CI to run miri on every core test and removes the bumpslab in favor of simply boxing each scope state.
We take a slight performance hit but I don't think it matters too much. And now, we know that scopestates properly drop their contents.
=> Fix: dont use bumpslab anymore, just box scopestates

packages/hooks/src/usefuture.rs
We have a lot of vestigial code from when use_future was meant to work with async components.
This cleans all that up and relies on use_state directly, since use_future is basically a glorified use_state.
=> Fix race condition in use_future by using use_state directly.

packages/hooks/src/usefuture.rs
Fixes a regression on use future that makes it always respawn the task and always return a stale unresolved value
=> Fix use_future always spawning a new task and never updating

packages/core/src/any_props.rs
When a component fails to render on desktop/ssr, dioxus will catch the error and render a placeholder. This PR adds a log::error to let the developer know what component failed to render and what the error was
=> Log errors when a component fails to render

packages/router/src/incremental.rs
The router incremental rendering feature currently does not rebuild the router before waiting for suspense. This breaks the static-hydrated example in fullstack. This PR adds rebuilding to fix that.
=> Fix route prerendering

packages/hot-reload/src/file_watcher.rs, packages/hot-reload/src/lib.rs
- Made `Config` public again
- Fix import in file_watcher.rs
- Use correct cfg syntax for `file_watcher` feature
=> fix: Use correct cfg for file_watcher feature in dioxus-hot-reload

playwright-tests/fullstack.spec.js, playwright-tests/web.spec.js
`page.locator` is a synchronous method.
=> fix(playwright): remove unnecessary `await`s

docs/router/examples/dynamic_route.rs, docs/router/examples/external_link.rs, docs/router/examples/full_example.rs, docs/router/examples/links.rs, examples/crm.rs, examples/flat_router.rs, examples/link.rs, examples/router.rs, examples/simple_desktop.rs, packages/fullstack/examples/axum-router/src/main.rs, packages/fullstack/examples/static-hydrated/src/main.rs, packages/router/README.md, packages/router/examples/simple_routes.rs, packages/router/src/components/link.rs, packages/router/src/navigation.rs, packages/router/tests/via_ssr/link.rs
Makes two small changes to the enum router to make it slightly less breaking:
1. `target` is renamed back to `to` to align with the old Link component.
2. `to` now accepts `&str`. This should not be used much outside of migrating things because it is not type checked at compile time, but it does make migrating much less painful
```rust
#![allow(non_snake_case)]
use dioxus_router::prelude::*;
use std::str::FromStr;
fn main() {
#[cfg(not(target_arch = "wasm32"))]
dioxus_desktop::launch(root);
#[cfg(target_arch = "wasm32")]
dioxus_web::launch(root);
}
fn root(cx: Scope) -> Element {
render! {
Router {}
}
}
#[inline_props]
fn UserFrame(cx: Scope, user_id: usize) -> Element {
render! {
pre {
"UserFrame{{\n\tuser_id:{user_id}\n}}"
}
div {
background_color: …
```
=> Make new enum router less breaking

packages/router/src/routable.rs
Adds the `is_child_of`, and `parent` functions to the routable trait.
```rust
use dioxus_router::prelude::*;
#[inline_props]
fn Home(cx: Scope) -> Element { todo!() }
#[inline_props]
fn About(cx: Scope) -> Element { todo!() }
#[derive(Routable, Clone, PartialEq, Debug)]
enum Route {
#[route("/")]
Home {},
#[route("/about")]
About {},
}
let route = Route::About {};
let parent = Route::Home {};
assert!(route.is_child_of(&parent));
assert_eq!(route.parent().unwrap(), &parent);
```
Closes #1241
=> Add is_child_of function to Routable

packages/core/src/nodes.rs, packages/core/tests/fuzzing.rs, packages/html/src/events.rs, packages/native-core/tests/fuzzing.rs, packages/ssr/src/renderer.rs, packages/web/src/rehydrate.rs
There are a few places in core where we expose more of the API of the nodes than we need to for the renderers. This PR makes a few more things private to reduce breaking changes in the future
=> Make more of core private

examples/router.rs, packages/router-macro/src/layout.rs, packages/router-macro/src/lib.rs, packages/router-macro/src/route.rs, packages/router/src/components/default_errors.rs, packages/router/src/components/link.rs, packages/router/src/contexts/navigator.rs, packages/router/src/contexts/router.rs, packages/router/src/history/mod.rs, packages/router/src/hooks/use_router.rs, packages/router/src/lib.rs, packages/router/src/router_cfg.rs
Creates a deprecated use_router hook to make transitioning to the new router easier
=> Make deprecated use router

packages/fullstack/Cargo.toml, packages/fullstack/src/adapters/mod.rs
This reuses a pool of futures instead of spawning a new tokio runtime on every request which should make server function performance better.
For a server function returning static text, this seems to be about twice as fast
=> Don't spawn a new tokio runtime every fullstack request

packages/fullstack/Cargo.toml, packages/fullstack/examples/axum-auth/src/main.rs, packages/fullstack/examples/axum-desktop/src/server.rs, packages/fullstack/examples/axum-hello-world/Cargo.toml, packages/fullstack/examples/axum-hello-world/src/main.rs, packages/fullstack/examples/axum-router/Cargo.toml, packages/fullstack/examples/axum-router/src/main.rs, packages/fullstack/examples/salvo-hello-world/src/main.rs, packages/fullstack/examples/warp-hello-world/src/main.rs, packages/fullstack/src/adapters/axum_adapter.rs, packages/fullstack/src/adapters/salvo_adapter.rs, packages/fullstack/src/launch.rs, packages/fullstack/src/lib.rs
Turns the launch macro in the fullstack crate into a builder.
Old:
```rust
launch_router!(@([127, 0, 0, 1], 8080), Route, {
incremental: IncrementalRendererConfig::default().invalidate_after(std::time::Duration::from_secs(120)),
});
```
New:
```rust
let config = LaunchBuilder::<FullstackRouterConfig<Route>>::router();
#[cfg(feature = "ssr")]
config
.incremental(
IncrementalRendererConfig::default()
.invalidate_after(std::time::Duration::from_secs(120)),
)
.launch();
#[cfg(not(feature = "ssr"))]
config.launch();
```
=> Switch to launch builder instead of macro for fullstack

packages/html/Cargo.toml, packages/html/src/web_sys_bind/events.rs, packages/web/Cargo.toml, packages/web/src/dom.rs, packages/web/src/hot_reload.rs, packages/web/src/lib.rs
Some of the web events are quite large and rairly used. For example, the onmounted event will not be used in most applications. This PR pulls those events out into features that are enabled by default so that users can use the crate with no default features for smaller binary sizes
=> Create default enabled features for large web events

packages/ssr/src/incremental.rs
The ssr crate has a map_path field that maps a route to a local path. It uses that function correctly when generating files, but not when searching files. This PR applies the function when searching files as well.
=> Fix finding files with a custom map_path

packages/fullstack/src/render.rs
Makes the fullstack renderer struct (SsrState)'s constructor public. This allows external libraries to create adapters for different frameworks using SsrState
=> Make SsrState public

packages/hooks/Cargo.toml, packages/hooks/src/computed.rs, packages/hooks/src/lib.rs
Adds a new computed hook that allows you to efficiently diff data before marking any scopes that read from the data as dirty. This is similar to a selector
=> Add computed hook

packages/router-macro/src/lib.rs, packages/router-macro/src/route_tree.rs
Reject any routes that don't start with `/` when parsing a route in the enum router macro
=> Reject all external routes when parsing a route

packages/router/src/contexts/router.rs
When the navigator pushed or replaced a route it was wrapping it in an extra Rc which broke the Any downcast
=> Fix navigator push/replace route

packages/router/src/history/memory.rs, packages/router/src/history/web.rs
Don't push a new route when the old and new routes are the same on web or desktop.
=> Deduplicate route history

packages/fullstack/src/server_fn.rs
The fullstack docs previously [failed to build](https://docs.rs/crate/dioxus-fullstack/latest). This fixes the broken imports that caused that issue
=> Fix Fullstack docs building

packages/cli/src/cli/create.rs
=> docs(cli): fix typo

packages/web/Cargo.toml
`cargo build` would print this warning:
```
warning: dioxus/packages/web/Cargo.toml: `default-features` is ignored for dioxus-html, since `default-features` was not specified for `workspace.dependencies.dioxus-html`, this could become a hard error in the future
```
Since it's being ignored anyway and that doesn't seem to be causing problems, I figured I'd remove it and get rid of the warning.
=> build(web): fix `default-features` warning

packages/cli/docs/src/configure.md, packages/cli/src/error.rs, packages/cli/src/server/web/proxy.rs
Updates a mistake in the docs and provides a better error message for a pathless proxy URL. Without this, `dx serve` panics with this message:
```
Paths must start with a `/`. Use "/" for
root routes
```
That's not very clear. Instead, we can detect this situation and provide a better error message:
```
Error: 🚫 Serving project failed: Failed to establish proxy: Proxy backend URL must have a non-empty path, e.g. http://localhost:8080/api instead of http://localhost:8080
```
=> Minor Proxy Improvements

packages/hooks/src/computed.rs
I'm not totally sure how the sentence was supposed to read, but removing "state" from "It state" seemed to work. Also, "it's" is "it is" and not possessive, so I fixed that.
=> docs(hooks): fix typos

packages/cli/docs/src/cmd/README.md, packages/cli/src/cli/autoformat.rs, packages/cli/src/cli/bundle.rs, packages/cli/src/cli/config.rs, packages/cli/src/cli/mod.rs, packages/cli/src/cli/plugin.rs, packages/cli/src/cli/translate.rs, packages/cli/src/cli/version.rs
A bunch of these were copy-pasted from `build`. This commit updates them to be the same as what their `dx help` string is.
=> docs(cli): update subcommand comments

packages/hot-reload/src/file_watcher.rs
futher -> further according to https://word.tips/spelling/further-vs-futher/
=> incorrect word spelling

packages/cli/src/cli/cfg.rs
I believe that technically this function is part of the public API via `dioxus_cli::cli::cfg::parse_public_url`. However, I don't see any evidence that this function is actually used inside or outside this crate. The last use within the crate was removed in January 2022 (9bb10c65a3cbabef127f6af5c0d1eadab1d01531).
=> chore(cli): remove unused function

packages/cli/src/builder.rs
Plus, one of these was incorrectly subtracting the end time from the start time.
=> refactor(cli): use more semantic `Instant::elapsed`

packages/fullstack/src/launch.rs
I am currently working on a project where I need to run server-side code concurrently with Dioxus Fullstack. However, I noticed that there is no way to reuse the Tokio runtime created in the launch function. As a result, the only option available to me right now is to spawn a new thread and runtime, which seems inefficient.
I propose making the launch functions public. This would allow developers like me to copy the launch function's code into our codebases and manipulate the Tokio runtime as needed, such as spawning new functions onto it. This change would provide more flexibility and efficiency in running concurrent server-side code.
=> Make launch functions pub

examples/tailwind/Dioxus.toml, examples/tailwind/README.md
Switches to using absolute paths to refer to `tailwind.css`
closes #1292
=> Update tailwind examples to work with multi-page apps

packages/cli/src/builder.rs
Currently, `dx build` for web will only pull artifacts from `wasm32-unknown-unknown/release` or `wasm32-unknown-unknown/debug`.
This change updates the dx cli to use the `--profile` argument if present to pull the correct build: `wasm32-unknown-unknown/{profile}`.
closes #1338
=> Use `--profile` to identify cargo build artifact if present for dx cli web builds

packages/hooks/src/use_shared_state.rs
I was wanting to use the `with` and `with_mut` functions in `use_shared_state` in the same way you can with `use_ref`. Is it OK to add these?
=> Add 'with' and 'with_mut' to 'use_shared_state'

.github/workflows/cli_release.yml, packages/cli/Cargo.toml
This PR adds a workflow that will run on every new release to generate binaries of the CLI for Windows, Linux, and macOS. It will then upload these binaries to the release, along with a SHA. This also adds new metadata to the dioxus-cli crate so that [cargo-binstall](https://github.com/cargo-bins/cargo-binstall/tree/main) can find the published artifacts.
The goal of this PR is to publish binaries that can be used in downstream partners' GitHub Actions workflows. By using the [install-action](https://github.com/marketplace/actions/install-development-tools), which uses cargo-binstall under the hood, developers can quickly install the latest CLI binary.
Here's a shorthand for installing the CLI using that action:
```yml
- uses: taiki-e/install-action@dioxus-cli
```
Note that I have not …
=> Publish CLI binaries for cargo-binstall

packages/core/src/diff.rs
The scope stack was not being set correctly when diffing a scope which causes the parent of a scope to be incorrect. This PR pushes and pops the scope id into the scope_stack when diffing a scope
Fixes #1350, https://github.com/DioxusLabs/dioxus/issues/1356
=> Fix the context API in lists

docs/guide/examples/readme_expanded.rs, packages/core/src/create.rs, packages/core/src/diff.rs, packages/core/src/nodes.rs, packages/core/tests/fuzzing.rs, packages/native-core/tests/fuzzing.rs, packages/rsx/src/lib.rs
We were bump allocating a Vec. That Vec will never run it's drop handler which results in leaked memory
Fixes #1361
=> Fix leak in core because of bump allocated Vec

docs/guide/src/en/interactivity/event_handlers.md, docs/guide/src/pt-br/interactivity/event_handlers.md
Starting on version 0.4 (PR #926), the `prevent_default` behavior inverted for forms in `dioxus-web`. This just adds a note to the documentation to document this.
=> DOC: Add note about form prevent_default behavior.

packages/html/src/events/form.rs, packages/html/src/native_bind/native_file_engine.rs, packages/web/src/file_engine.rs, packages/web/src/lib.rs
Impl `get_native_file` to return the native file type on different platforms: `web_sys::File` on wasm and `tokio::fs::File` on desktop.
Fixes https://github.com/DioxusLabs/dioxus/issues/1081
=> FileEngine: expose native file types on different platforms

packages/html/Cargo.toml, packages/native-core/Cargo.toml
This brings a use of bitflags 2 and a couple of minor features.
=> deps: Update keyboard-types to 0.7.

.github/workflows/main.yml, .github/workflows/playwright.yml, packages/cli/.github/workflows/main.yml
This commit addresses #1360 by removing references to [actions-rs/toolchain](https://github.com/actions-rs/toolchain/issues/216) and [actions-rs/cargo](https://github.com/actions-rs/cargo/issues/216#issuecomment-1329850830), both of which are unmaintained. 
Some parts of the workflows already use [dtolnay/rust-toolchain](https://github.com/dtolnay/rust-toolchain) and this is the one most of the community has moved to, so I've changed remaining references to actions-rs/toolchain to dtolnay/rust-toolchain. There's no good replacement for actions-rs/cargo so I've instead moved to just running the commands directly. In cases where Cross is required instead of Cargo to run CI tests, I've added a new action [taiki-e/install-action](https://github.com/taiki-e/install-action) to install Cross and …
=> Update all uncommented commands to remove actions-rs

examples/mobile_demo/src/lib.rs, packages/core/src/arena.rs, packages/core/src/events.rs, packages/core/src/scope_context.rs, packages/core/src/scopes.rs, packages/core/src/virtual_dom.rs, packages/core/tests/attr_cleanup.rs, packages/core/tests/bubble_error.rs, packages/core/tests/context_api.rs, packages/core/tests/cycle.rs, packages/core/tests/diff_component.rs, packages/core/tests/diff_element.rs, packages/core/tests/diff_keyed_list.rs, packages/core/tests/diff_unkeyed_list.rs, packages/core/tests/lifecycle.rs, packages/core/tests/miri_simple.rs, packages/core/tests/miri_stress.rs, packages/native-core/src/utils/persistant_iterator.rs, packages/signals/tests/create.rs, packages/signals/tests/selector.rs, packages/signals/tests/subscribe.rs, packages/ssr/src/renderer.rs
Currently `ScopeId(0)` is the only way to directly refer to the root scope (useful for signals). This isn't documented anywhere afaict and it's somewhat surprising as usually ids shouldn't be constructed by the user.
This PR adds a constant that provides the root ScopeId.
=> Add ScopeId::ROOT

packages/signals/src/signal.rs
Exposes the new_in_scope function for signals which makes it possible for users to make a signal last longer than the current scope.
For example:
```rust
let signals = use_signal(cx, || vec![Signal::new(0)]);
// ...In a Child component...
// Because we use the origin scope of the array, even if the child scope is dropped, the signal will still exist as long as the array does
signals.push(Signal::new_in_scope(123, signals.origin_scope()));
```
=> Expose new_in_scope for signals

packages/ssr/Cargo.toml, packages/ssr/src/lib.rs
=> Make incremental a cfg feature.

packages/cli/src/config.rs
New fields for debian settings:
- desktop_template
For NSIS settings:
- custom_language_files
- template
=> Fix cli compile error due to tauri bundler adding fields

Cargo.toml, examples/query_segments_demo/Cargo.toml, examples/query_segments_demo/src/main.rs, packages/router/src/routable.rs, packages/ssr/Cargo.toml, packages/ssr/src/lib.rs
Adds a multiple query segments example and updates the documentation.
The example won't work until #1406 is merged.
=> Add query segment example and documentation

packages/cli/Cargo.toml, packages/cli/src/builder.rs, packages/cli/src/cli/build.rs, packages/cli/src/server/web/mod.rs
This PR fixed `prettier_build` function. we covered default `cargo build` console and make it more concise.
=> fix: prettier_build unavailabe

packages/core/src/nodes.rs
Currently the `ScopeState` will only drop elements that are `render!`ed, not any nodes that are created through the `IntoDynNode` or `IntoTemplate` trait. This PR fixes the two trait impls to drop any attributes and components that were rendered by the `VirtualDom`
Fixes #1365 ? At least the no-native-core version
=> Find attributes and components to drop when rendering any lazy nodes

packages/web/src/dom.rs
I think this log statement wasn't caught in code review :shipit:
=> Remove stray log statement in `onmounted`

packages/hooks/src/use_shared_state.rs
So I had tried using a `UseSharedState` as a dependency for `use_future`, and it wasn't re-running when it changed. I think this was because it was comparing the `.inner` values which still were pointing to the same data. 
I implemented a special `UseFutureDep` so it would compare a `gen` value, sort of following the example of `UseRef`. I did have to remove the `PartialEq` here to avoid conflicting with this: `impl<A: Dep> UseFutureDep for &A`, but this might not be the right thing to do.
=> Use a `gen` in `PartialEq` for `UseSharedState`

packages/hooks/src/usefuture.rs
Use future will cancel the previous future now instead of letting it continue. This PR updates the documentation to match that behavior.
=> Fix use_future docs

packages/cli/src/server/desktop/mod.rs, packages/cli/src/server/mod.rs, packages/cli/src/server/web/hot_reload.rs, packages/cli/src/server/web/mod.rs, packages/core/src/diff.rs
Combines some code in the CLI that serves the hot reload and non-hot reload version of the cli.
This fixes some issues that were applied to only the non-hot-reloading version of the code. Fixes https://github.com/DioxusLabs/dioxus/issues/1041.
This will also fix hot rsx reloading after any changes that require a full rebuild happens. For example after this change:
```rust
p { "{10 * 10}" }
->
p { "{10 * 20}" }
```
The page reloads but this change currently fails to hot reload:
```rust
p { "{10 * 20}" }
->
p { "{10 * 20}" }
"This should be hot reloadable"
```
This PR makes the second change hot reloadable.
=> Deduplicate serve code with hot reloading in the CLI crate

packages/router/src/contexts/router.rs, packages/router/src/history/web.rs, packages/web/src/dom.rs
Fixes decoding the query segment on the web router. We currently parse the route from only the `pathname` which does not include the query. This PR adds the query segment before parsing the route which should fix query parameters always being empty on the web router.
=> Fix web query segments

packages/interpreter/src/interpreter.js
Adds some logic to handle select elements with the oninput event with multiple options selected
Closes #1314
=> Handle oninput for select elements

packages/html/Cargo.toml, packages/native-core/Cargo.toml, packages/signals/src/effect.rs, packages/signals/src/rt.rs, packages/signals/src/selector.rs
Currently any signals created in an effect use the root scope as the owner. This essentially leaks the signal for the duration of the application. Instead this sets the owner of signals created in effects to the owner of the effect
=> Fix leaked signals created in effects

packages/router-macro/src/route.rs
It looks like enum route segments were not being parsed correctly outside of nests. This fixes that issue.
Fixes [#1020](https://github.com/DioxusLabs/dioxus/issues/1293)
=> Fix parsing spread routes

packages/core/src/lib.rs, packages/core/src/runtime.rs, packages/core/src/virtual_dom.rs
Exposes a few new functions to manipulate the global runtime of Dioxus. This fixes dynamic linking of components as a dynlib. When a dynlib is linked, the global scope list in the dynlib is different from the main application you are running the VirtualDom in which breaks the context API. With this PR, you can pass the runtime from the main application to the dynlib and run `override_runtime` to set the dynlib runtime to be the same as the main application.
=> Expose public methods for manipulating the global runtime

packages/desktop/Cargo.toml
Remove duplicate `dox` feature that resulted in build fail
=> Update Cargo.toml (desktop package)

packages/hooks/src/usestate.rs
I have implemented PartialOrd for UseState to allow for some better readability. It may be a small change, but I found `.get()` quite annoying. It just makes more sense to have PartialOrd implemented.
Essentially instead of,
```rs
fn main() {
}
let mut count = use_state(cx, || 0);
let other_count = use_state(cx, || 10);
cx.render(rsx! (
h1 { "Counter: {count}" }
button { onclick: move |_| if count.get() < other_count.get() { count += 1 }, "Tick up"}
button { onclick: move |_| if *count.get() > 0 { count -= 1}, "Tick down"}
))
}
```
now we have,
```rs 
fn main() {
}
let mut count = use_state(cx, || 0);
let other_count = …
```
=> PartialOrd for UseState

packages/core/src/lib.rs, packages/core/src/runtime.rs, packages/fullstack/src/adapters/warp_adapter.rs
This is a different approach to https://github.com/DioxusLabs/dioxus/pull/1441 that just makes the runtime guard public. This API is slightly more complex because it uses drop handlers, but can be more flexible
Closes https://github.com/DioxusLabs/dioxus/issues/1465
=> Make RuntimeGuard public

packages/desktop/Cargo.toml
https://github.com/DioxusLabs/dioxus/pull/1412 removed the tray feature. wry `0.30` doesn't include a tray feature. Originally that PR also upgraded wry which is why the tray feature was removed.
=> Restore the tray feature in the desktop crate

playwright-tests/playwright.config.js
Playwright tests on windows were failing because playwright does not execute the second command  because it is on a newline. This PR fixes that issue by combining the two commands into one line separated by `&&`
=> Fix playwright tests on windows

packages/liveview/examples/axum.rs, packages/liveview/src/lib.rs
By utilizing `window.location.host` in the client-side JavaScript, we can easily derive the WebSocket URI from a relative path URI. This approach obviates the need for host address retrieval on the server side, unlike the method of serving glue code in liveview using `interpreter_glue`.
=> liveview: Add `interpreter_glue_relative_uri

packages/html/src/elements.rs, packages/interpreter/src/common.js, packages/interpreter/src/sledgehammer_bindings.rs
Adds the `initial_selected` attribute to set an option element's defaultSelected property as described [here](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement).
Implemented similarly to https://github.com/DioxusLabs/dioxus/pull/1063
=> feat: initial_selected attribute for options

packages/core-macro/README.md
This updates the README with the new changes from #1448. Specifically:
- Adds a description for the `component` attribute macro.
- Removes the description of the deprecated `inline_props` attribute macro.
- Adds dots after each bullet point description.
A bit late to the party, I know. Maybe I searched for `#[inline_props]` (instead of just `inline_props`) when replacing all occurrences of it? I'll see if I find any other occurrences of this tomorrow.
=> Update `dioxus-core-macro` README as per #1448

packages/cli/src/server/output.rs
See https://github.com/DioxusLabs/dioxus/issues/1514. This just appends `'Run cargo check' to see them.` to `There were X warning messages during the build.`. No `--verbose` changes since it's too small of a change to mark it as "verbose".
=> CLI: Clarify where serve warnings come from

packages/cli/src/cli/autoformat.rs
This change adds the ability for autofmt to read from stdin by using `-f -` or `--file -`
=> cli: Add ability for autofmt to read stdin

packages/generational-box/src/lib.rs, packages/signals/src/rt.rs, packages/signals/src/signal.rs, packages/signals/tests/create.rs
(Thanks to @matthunz for letting me know about [dtolnay](https://github.com/dtolnay)'s amazing article about derefing to closures on stable!)
This restores the previously unsound implementation of `Deref<Target = dyn Fn() -> Ref<'static, T>>` on signals which lets you call the signal like a function instead of reading the signal:
```rust
fn App(cx: Scope) -> Element {
let signal = Signal::new("hello world".to_string());
// You can call signals like functions to get a Ref of their value.
assert_eq!(&*signal(), "hello world");
render! {
"hello world"
}
}
```
=> Make signal callable on stable

examples/signals.rs, packages/core/src/lib.rs, packages/rsx/src/node.rs, packages/signals/src/signal.rs
This commit adjusts how exprs and for loops are handled within rsx. This is a breaking change in terms of codegen, but has slight semantic changes as well.
Now, when exprs/for loops are allocated, they are given a temporary. The temporary is elided to the <'a> lifetime of the bump, to satisfy the borrow checker. This fixes issues with signals where exprs/for loops mapping vecs out of RefCells would be caught up without a temporary lifetime.
Specifically, before, this component could not compile:
```rust
let todos = use_signal(cx, || vec!["hi"]);
render! {
ul {
for todo in todos.read().iter() {
li { "{todo}" }
}
todos.read().iter().map(|todo| rsx! {
li { "{todo}" }
})
}
}
}
```
The error we were getting is:
```
error[E0597]: `todos` does not live long enough …
```
=> Change the semantics of exprs/for loops allocations strategy

examples/todomvc.rs
More context in the issue: https://github.com/DioxusLabs/dioxus/issues/1502
Note: I'm learning rust/dioxus, so any/all feedback welcome. I tried to make a component for each of the main UI components. i.e. the header, the list footer, the page footer.
I didn't make a component to wrap the `TodoEntry { }` block, as it seemed unnecessary.
=> refactor todo mvc example

packages/hot-reload/Cargo.toml, packages/hot-reload/src/file_watcher.rs, packages/hot-reload/src/lib.rs
- Enable `dioxus-html` by default but make it optional
- New `custom_file_watcher` feature, it's like the old `file_watcher` but doesn't depend on `dioxus-html`, I will use this one for Freya with `default-features = false` so web is disabled
- `file_watcher` feature now just enables `custom_file_watcher` and `dioxus-html`
No breaking changes and I will be able to not pull `dioxus-html` in freya
=> feat: Optional web support for hot-reload crate

packages/core-macro/src/component_body_deserializers/inline_props.rs
From this source code:
```rs
/// Renders a button.
///
/// 
/// 
/// Bunch of lines.
///
/// 
/// # Example
/// ```rs
/// rsx! {
///     Button {
///         label: "Label",
///         action: "Print",
///     }
/// }
/// ```
#[component]
fn Button(
cx: Scope,
/// Shows the given label.
///
/// Just two new lines.
#[deprecated]
label: Option<&'static str>,
/// Does this thing when clicked.
///
///
///
///
///
///
///
/// Lot of lines
action: &'static str
) -> Element {
let label = label.unwrap_or("defaul");
render! {
"Button with label {label} that should do {action} when clicked"
}
}
```
This documentation is generated:
[image](https://github.com/DioxusLabs/dioxus/assets/76173380/6a698127-6f3a-45db-bd6e-672630aa90be)
*The argument links point to the struct fields.*
There's still some …
=> Append prop documentation to function when using `#[inline_props]` or `#[component]`

packages/core-macro/Cargo.toml, packages/core-macro/src/component_body_deserializers/inline_props.rs, packages/core-macro/src/lib.rs, packages/core-macro/src/utils.rs
*See also https://github.com/DioxusLabs/dioxus/pull/1563.*
I wasn't quite happy with the state that the prop docs were in, so I made this PR, which:
- Removes attributes from the prop docs. My reasoning is that they are not shown on the struct fields either, and they clutter up the props quite a bit.
- Better `#[deprecated]` parsing, just like the official Rustdoc. In the reason/note, all consecutive newlines and tabs are reduced to just one newline/tab and replace with a space. It is possible to make it multi-line, but it was not working very well in the IDEs.
- Adds formatting for the types (`Option < & 'static str >` turns into `Option<&'static str>`).
- More input sanitizing (removes unnecessary whitespace).
- Fixes a bug where the `<hr>` separator was always shown.
Example source …
=> Improve prop docs

packages/desktop/src/protocol.rs, packages/signals/src/effect.rs, packages/signals/src/selector.rs, packages/signals/src/signal.rs
Currently signals can only be used inside of the Dioxus runtime. When they are used outside of the Dioxus runtime, they fail silently. This can be confusing when you try to integrate Dioxus with external futures like tokio futures, or external event handlers like web-sys closures.
This PR changes signals so that the runtime is only needed for signal creation instead of requiring a runtime any time you read or write to a signal
=> Fix using signals outside of a scope

packages/fullstack/src/launch.rs, packages/fullstack/src/lib.rs
Adds an error message to make it more clear that a fullstack application with `ssr` and `web` or `ssr` and `desktop` enabled will not work.
=> Add error message when overlapping fullstack features are enabled

packages/core-macro/src/props/mod.rs
Adds a more legible error to fix #1557
=> Add an readable error when you name a prop key

packages/router/src/components/link.rs
since url::Url is commonly used for many crates, impl IntoRoutable for a rust-url newtype can make it more ergonomic to work with some crates.
=> Add Newtype so that Rust-url can be IntoRoutable

packages/core-macro/src/component_body_deserializers/inline_props.rs, packages/desktop/src/protocol.rs
I'm sorry for creating a third PR for this, but I just noticed that there's one too many line breaks in the generated docs for props (see https://github.com/DioxusLabs/dioxus/pull/1563 and https://github.com/DioxusLabs/dioxus/pull/1565). I changed it to use the Rustdoc approach, which puts text separated by two lines into separate `<p>` elements. Previously, it just replaced `\n` with `<br/>`
Right now, this documentation:
```
/// Doc.
/// Next line.
```
Would generate:
```
Doc.
Next line.
```
But it's actually supposed to be:
```
Doc. Next line.
```
And when you used two new lines, the gap between them would be too big. Example image with the bug:
Fixed:
Regular Rustdoc:
=> Fix prop docs line breaks

packages/cli/src/builder.rs
Silence additional disturbing output from cargo in desktop builds
=> Silence desktop build outputs from cargo

packages/core-macro/src/component_body_deserializers/component.rs
Adds a `#[allow(clippy::inline_always)]` attribute to the generated `__dx_inner_comp` function.
=> Fix `#[component]` expansion Clippy warning

packages/web/src/dom.rs
Fixes a type mismatch that broke the scroll event on the web renderer
=> Fix the scroll event on the web renderer

packages/fermi/src/hooks/state.rs
Fixes https://github.com/DioxusLabs/dioxus/issues/1608
This will make `AtomState::current()` read from the Root value instead of the AtomState inner value, this makes it work properly on async contexts / event handlers
=> fix: Read value from root when calling `AtomState::current()`

packages/core-macro/src/props/mod.rs
https://github.com/syrflover/derive-props-with-const-generics
To trigger an error, change the version of dioxus to 0.4 in `Cargo.toml`
https://github.com/DioxusLabs/dioxus/blob/a3e6d0adcaee49495db5c324dbf9f20d5ec529ed/packages/core-macro/src/props/mod.rs#L554-L566
https://github.com/DioxusLabs/dioxus/blob/a3e6d0adcaee49495db5c324dbf9f20d5ec529ed/packages/core-macro/src/props/mod.rs#L645-L651
When it is `GenericParam::Const`, it doesn't return anything. However, if that item is included in an iterator, a syntax error occurs because it generates commas as many times as the length of the iterator when creating tokens.
https://github.com/syrflover/dioxus/blob/4f8b60834af43fef879c7eb0ff46b74d23a6eabe/packages/core-macro/src/props/mod.rs#L554-L564
Changed to returns `None`, when it is …
=> fix syntax error at `#[derive(Props)]` using const generics

packages/fermi/src/hooks/atom_root.rs
Updates the error message shown when no atom root is found in context
_Another +1-1 PR:skull:_
=> fix: Update error message when no atom root is found in context

examples/calculator.rs
Adds tabindex for the calc example, enabling keyboard input
=> fix keyboard input on calc example

packages/cli/Cargo.toml, packages/cli/src/error.rs, packages/cli/src/main.rs
(Related to #1547)
Although the `dx` CLI allows to specify a package name to chose from workspace members, it does not support workspace members specified as glob-wildcards. Neither it respects the effective package name, specified in the crate's `Cargo.toml`.
This PR addresses that issue:
- upon `dx build ...`, if the `--bin` CLI-argument is provided, treat the current dir as a workspace;
- search through the workspace's `members`: resolve each of them with `glob`;
- assume that any workspace member has a `Cargo.toml` in it (cargo does it, so it's okay);
- read said manifest, and check the package name in it;
- if found — there we have our sought package.
=> Related to #1547: use `dioxus-cli` within a workspace (wildcard-members, real package names)

packages/cli/src/builder.rs
```
[application]
default_platform = "web"
[application.tools]
tailwindcss = { input = "input.css", config = "tailwind.config.js" }
```
when enable tailwindcss, CLI will auto insert `<link rel="stylesheet" href="tailwind.css">` into `index.html`.
this will cause 404 when route enabled.
this PR change the path to absolute path to fix this.
=> Fix tailwind.css 404 in Cli web platform build

packages/core/src/lazynodes.rs
Fix error in Lazynode documentation that uses `ScopeState::element` which doesn't exist. Change to `ScopeState::render`
Fixes #1647
=> Fix outdated lazynode documentation

packages/hooks/src/lib.rs, packages/hooks/src/use_const.rs
Adds `use_const` hook for [571](https://github.com/DioxusLabs/dioxus/issues/571) so data that doesn't need to be mutated can be easily memoized and used across components
=> Add use_const hook

Makefile.toml
Adds `cargo make tidy` and `cargo +nightly make miri` and changes `cargo make tests` to include `tidy`
Closes [1472](https://github.com/DioxusLabs/dioxus/issues/1472)
=> Add cargo make tidy/miri

packages/rink/Cargo.toml, packages/rink/src/lib.rs, packages/rink/src/query.rs, packages/rink/src/render.rs, packages/rink/src/style.rs, packages/rink/src/style_attributes.rs, packages/rink/src/widget.rs
It would probably be pretty simple to take it one step lower and use [`termwiz`](https://docs.rs/termwiz/latest/termwiz/index.html) directly, but for now `ratatui` is a drop in replacement for an outdated crate.
Fixes [1311](https://github.com/DioxusLabs/dioxus/issues/1311)
=> Switch outdated tui crate for ratatui

packages/desktop/src/lib.rs
The docs for `dioxus_desktop::launch_cfg` uses code from a long time ago, and that is now unavailable, which can cause problems for developer.
=> docs(desktop): fix wrong example code

packages/cli/src/builder.rs
When running `dx serve --verbose` an error appears on console stating: "cannot set both --verbose and --quiet"
I noted that in the file "packages/cli/src/builder.rs", the "quiet" flag appeared to be set in default command, and the "verbose" flag was being appended, which caused both flags to be put into the command, so I made them mutually exclusive instead.
=> Fixed conflict of  "--verbose" and "--quiet" flags

packages/fullstack/src/adapters/axum_adapter.rs
When using server functions, the current pattern to access state such as database connections is to use `register_server_fns_with_handler` on an Axum router and 'inject' the state into the context provided to the server function. However, this only affects function calls which go via the Axum router; SSR renders bypass this, and therefore don't have access to any state.
This commit adds an alternative `render_handler` which accepts some additional state. That state is injected into the context in a similar manner to `register_server_fns_with_handler`. SSR renders can then proceed to run in the same way as HTTP calls.
=> feat(fullstack): add `render_handler_with_state`

packages/core/src/nodes.rs
This makes it possible to pass string directly into an attribute. String is a very common type and this is something I have seen people hit several times when they first use dioxus.
=> Add into attribute value impl for String

packages/core/src/nodes.rs
Fixes a memory leak caused by allocating a string in the bump allocator. The string needs to have it's drop handler called to be dropped to drop the memory but bump allocators do not drop objects allocated in them. Instead this PR changes the bump allocator to copy the &str out of the string
=> Fix string memory leak

packages/fullstack/examples/axum-hello-world/src/main.rs, packages/fullstack/src/render.rs, packages/ssr/Cargo.toml, packages/ssr/src/eval.rs, packages/ssr/src/incremental.rs, packages/ssr/src/lib.rs
Adds a noop evaluator to the SSR renderer that ignores any incoming evals. This makes it easier to use Eval with the fullstack crate without adding `#[cfg(feature = "web")]` for every eval
=> Add a noop evaluator to the ssr renderer

packages/fullstack/src/layer.rs, packages/fullstack/src/lib.rs
Makes the layer module with the layer trait in the fullstack crate public. This makes it possible to implement Fullstack layers in other crates and makes implementing a custom server function handler easier
=> Make the layer module public in fullstack

examples/optional_props.rs, packages/core-macro/src/props/mod.rs
This changes optional props to accept either nothing, the inner type or an option of the inner type:
```rust
render! {
Button {
optional: Some("asd".to_string()),
}
Button {
optional: "asd".to_string(),
}
Button {}
}
}
#[derive(Props, PartialEq)]
struct ButtonProps {
optional: Option<String>,
}
fn Button(cx: Scope<ButtonProps>) -> Element {
render! {
"{cx.props.optional:?}"
}
}
```
If you are new to dioxus, don't know about the auto optional feature and you want Option<T>, this should make the first thing you try work
=> Make optional props accept Nothing, T or Option<T>

packages/cli/src/logging.rs, packages/cli/src/server/desktop/mod.rs, packages/cli/src/server/output.rs, packages/rsx/Cargo.toml, packages/rsx/src/hot_reload/hot_reload_diff.rs, packages/rsx/src/hot_reload/hot_reloading_file_map.rs
This fixes the liveview part of #1286. When syn was updated some items were not added which causes some more complex code like the liveview hello world example to always preform a full reload instead of hot reloading only the rsx
=> Fix missing items in hot reloading diffing

packages/hooks/src/use_shared_state.rs
Fixes the unused lint that the `locations_display` function in `use_shared_state` produces in release mode:
```
warning: function `locations_display` is never used
--> packages/hooks/src/use_shared_state.rs:29:8
|
29 |     fn locations_display(locations: &[...
|        ^^^^^^^^^^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default
```
=> Fix use shared state lint in release mode

packages/cli/src/server/desktop/mod.rs, packages/hot-reload/src/file_watcher.rs, packages/hot-reload/src/lib.rs
This hides the hot reloading file by placing it in the temp directory.
This reverses #842. If the issue is just with `@` in a path, this shouldn't revert that fix.
Closes https://github.com/DioxusLabs/dioxus/issues/1616
=> Use a temp directory for the hot reloading pipe

packages/desktop/Cargo.toml, packages/desktop/build.rs, packages/desktop/src/lib.rs
Dioxus desktop uses wry internally. There are some [limitations](https://github.com/wravery/webview2-rs#cross-compilation) that make compiling to GNU more difficult. This PR adds a warning about the limitations and suggests that most users switch to the MSVC, but it also provides information for the users that choose not to switch.
(This is an issue that has come up several times in the discord especially when cross compiling to windows)
=> Add a warning about wry gnu support to Dioxus desktop

packages/fullstack/src/adapters/mod.rs
When a server function is called, but then the client disconnect, the oneshot channel send panics. This PR fixes that issue by joining the task instead
=> Fix disconnects that happen while a server function is being resolved

packages/cli/README.md
The README for cli gets included in lib.rs via `include_str!`. The code snippets then get assumed to be Rust, which fails if running `cargo test --doc`. This is not a huge problem, but was brought to my attention because Nix's `buildRustPackage` runs `cargo test` including doc tests (unlike what get run for this project on CI). This means I can't update the Nix package to 0.4.3 without changing the test flags (which I think I'll see about doing anyways, as that's how Dioxus runs CI).
=> Fix doc tests by adding formatting to CLI README

packages/cli/src/main.rs
Because the `get_bin` function will use `cargo_metadata`, but for some command we don't have it.
=> fix: dx create not work

packages/cli/src/server/desktop/mod.rs
Dedupes this message from filling up the terminal multiple times every second when hot-reloading with desktop:
```
Error connecting to hot reloading: Waiting for a process to open the other end of the pipe. (os error 536) (Hot reloading is a feature of the dioxus-cli. If you are not using the CLI, this error can be ignored)
Error connecting to hot reloading: Waiting for a process to open the other end of the pipe. (os error 536) (Hot reloading is a feature of the dioxus-cli. If you are not using the CLI, this error can be ignored)
Error connecting to hot reloading: Waiting for a process to open the other end of the pipe. (os error 536) (Hot reloading is a feature of the dioxus-cli. If you are not using the CLI, this error can be ignored)
Error connecting to hot reloading: Waiting for a …
```
=> Make hot reload error only show once

packages/web/src/dom.rs, packages/web/src/rehydrate.rs
=> Send mount event when hydrating

packages/signals/src/signal.rs
I noticed I couldn't convert a Signal into a ReadOnlySignal with .into()
This implements the trait that enables that.
=> Implemented From<Signal<T>> for ReadOnlySignal<T>

packages/core-macro/src/component_body_deserializers/component.rs
Adds a doc comment to the derived properties struct generated from the inline arguments of the component.
This prevents the `missing_docs` lint to trigger if that is setup for a project (for instance, a CI might prevent progress by denying all lint warnings). This could probably be extended to provide custom doc comments to the struct, or use the doc comment of the component function, but I didn't see the need for that, as this PR will include a link to the original component function in the docs for further info.
=> Add doc comment on generated inline properties struct

packages/cli/src/builder.rs, packages/cli/src/cli/build.rs, packages/cli/src/cli/bundle.rs, packages/cli/src/cli/cfg.rs, packages/cli/src/cli/serve.rs, packages/cli/src/config.rs
Changes apply for the CLI actions `build`, `bundle`, and `serve`. Adds `-- [CARGO_FLAGS]` and `--platform-triple`.
Cargo arguments can now be passed through after `--` (e.g. `dx build -- --timings`)  via escaped conditionals. This does lock out that space for any later usage without a breaking change to the CLI, but I can't think of any other necessary use for post-argument parsing on this tool.
Since the `--target` flag is currently taken, a `--platform-triple` flag allows alternative values for `cargo build --target`. This can't be done directly in passthrough, since dioxus-cli needs to know the output folder. If reasonable, the existing `--target` flag should probably be renamed so we can be 1:1 with cargo naming.
If the codebase has any other instances where bundled anyhow errors are …
=> Add Cargo Arguments and Cross-Architecture Support

packages/generational-box/src/lib.rs
This PR fixes in issue in the generational box crate where invalid values were never being recycled (and dropped). This caused a memory leak and caused Drop implementations to never be called
Fixes #1745
=> Fix invalid locations never being dropped

packages/ssr/src/incremental_cfg.rs
This changes the incremental renderer to clear the cache when you first build the renderer. This fixes an issue where the old HTML was cached after some changes to the code that makes it seem like hot reload is broken
=> Clear the cache on rebuild in the incremental renderer

packages/core/src/scope_context.rs
Spawn forever currently removes the future that was spanned when the component is dropped. This changes spawn forever to not add the future to the list of futures that are removed when the component is removed.
Fixes this issue reported on discord:
```
I made a repo with a minimum reproducible example (https://github.com/lukasturcani/dioxus-future-issue) -- the long and short of it is that if I spawn a future with onclick my future reaches an await point but then never gets completed. 
I tried using both spawn and spawn_forever, as well as just returning the future from the onclick handler -- all lead to the same results. the interesting thing is -- this only happens if my onclick is nested inside a custom component. (the repo has both the working and non working code)
```
=> Fix spawn forever

packages/cli/src/server/web/mod.rs
This PR disables caching for static files in the Dioxus CLI to prevent the browser from caching files for too long during development
Fixes https://github.com/DioxusLabs/dioxus/issues/1740
=> Don't cache assets in the CLI

packages/fullstack/src/hooks/server_cached.rs, packages/html/Cargo.toml, packages/html/src/elements.rs, packages/html/src/events/mouse.rs, packages/html/src/global_attributes.rs, packages/html/src/lib.rs, packages/rsx-rosetta/Cargo.toml, packages/rsx-rosetta/src/lib.rs, packages/rsx-rosetta/tests/h-tags.rs, packages/rsx-rosetta/tests/raw.rs, packages/rsx-rosetta/tests/simple.rs, packages/rsx-rosetta/tests/web-component.rs
This PR changes rsx-rosetta to use the mapping of html->rsx names for elements and attributes defined in dioxus-html instead of converting the case of the attributes and elements.
This fixes the following cases:
- translating h1-h6
old:
```
h_1 {}
```
new:
```
h1 {}
```
- translating web components
old:
```
my_component {}
```
new:
```
my-component {}
```
- translating unsupported attributes
old:
```
div { unrecognizedattribute: "asd", "hello world" }
```
new:
```
div { "unrecognizedattribute": "asd", "hello world" }
```
=> Fix rsx rosetta element and attribute mapping

packages/rink/src/layout.rs
The current rink code only applies layout attributes when they are a string, not a literal `bool`, `f32`, or `i23`. This PR fixes that bug
Fixes #1780
=> Fix non string layout attributes in rink

packages/fullstack/Cargo.toml, packages/fullstack/examples/salvo-hello-world/Cargo.toml, packages/liveview/Cargo.toml
The old version of Salvo we depend on broke which is causing CI failures in https://github.com/DioxusLabs/dioxus/pull/1727, https://github.com/DioxusLabs/dioxus/pull/1369, and https://github.com/DioxusLabs/dioxus/actions/runs/7277746350/job/19830455478?pr=1736. This PR bumps the version of Salvo to the most recent release to fix the issue
=> Bump the version of Salvo

packages/core/src/nodes.rs, packages/core/src/scopes.rs, packages/rsx/src/node.rs
From
```rust
pub trait IntoDynNode<'a, A = ()> {
fn into_vnode(self, cx: &'a ScopeState) -> DynamicNode<'a>;
}
pub trait IntoTemplate<'a> {
fn into_template(self, _cx: &'a ScopeState) -> VNode<'a>;
}
```
to
```rust
pub trait IntoDynNode<'a, A = ()> {
fn into_dyn_node(self, cx: &'a ScopeState) -> DynamicNode<'a>;
}
pub trait IntoVNode<'a> {
fn into_vnode(self, _cx: &'a ScopeState) -> VNode<'a>;
}
```
Tested by compiling and serving my Dioxus project
=> rename IntoDynNode and IntoTemplate traits

examples/tailwind/README.md, packages/cli/src/assets/autoreload.js, packages/hot-reload/README.md
Fixes #1785 
I also found one more place that looked like it was using the old path:
```
packages/extension/package.json
12:        "url": "https://github.com/DioxusLabs/cli"
```
But as this was a documentation fix I didn't want to touch it in this PR.
=> Updated packages and comments referencing old CLI location

packages/interpreter/Cargo.toml
There is a typo in the sledgehammer import.
Fixed the typo see commit.
=> Fix typo which resolves #1789

examples/query_segments_demo/src/main.rs, packages/router-macro/src/lib.rs, packages/router-macro/src/query.rs, packages/router-macro/src/route.rs, packages/router-macro/src/segment.rs, packages/router/src/routable.rs
This changes the router macro to derive the query segment parsing information for segments like this: `?:myqueryarg&:myotherqueryarg` (in the browser this would look like `?myqueryarg=value&myotherqueryarg=value`), and change fields that capture the full query argument to `?:..myfullquery`.
Closes #1631
=> Automatically derive standard query parsing in the router macro

packages/html/src/events.rs, packages/html/src/events/mouse.rs
Some merge issues between the new event system and the ondouble click fix caused the event to break again. This PR fixes it and includes an option to rename the event in the event macro
=> Fix the ondouble click event

flake.lock, flake.nix
[Feel free to reject this PR if you do not wish to have Nix support upstream]
This PR adds a simple `flake.nix` providing a [development shell](https://zero-to-nix.com/concepts/dev-env) for people that use the [Nix](https://zero-to-nix.com/) package manager. It provides the benefit of having everything setup automatically for Dioxus development -- all I have to do is open VSCode in the dev shell.
The flake provides only dev shell, and not the full Nix packages, because that will require a `Cargo.lock`. I originally wanted to write this flake to create the `dioxus-cli` package, but figured the dev shell would be useful to others.
=> Add a simple nix dev shell

packages/core/src/arena.rs, packages/core/src/fragment.rs, packages/core/src/lazynodes.rs, packages/core/src/nodes.rs, packages/core/src/scopes.rs, packages/core/tests/fuzzing.rs, packages/dioxus-tui/examples/many_small_edit_stress.rs, packages/native-core/tests/fuzzing.rs, packages/rsx/src/lib.rs
This fixes an issue where the render macro does not drop any listeners that are added to elements within the macro. It also change the VNode to be non exhaustive and adds a constructor that adds any dynamically allocated parts of the VNode to a drop list to prevent similar leaking issues in the future.
=> Fix leak in the render macro

packages/cli/README.md
The CLI tool `dx` doesn't have an argument `project-name`
```sh
$ dx create --help
Init a new project for Dioxus
Usage: dx create [OPTIONS]
Options:
--template <TEMPLATE>  Template path [default: gh:dioxuslabs/dioxus-template]
--bin <BIN>            Specify bin target
-h, --help                 Print help
```
```sh
$ dx create my-project
error: unexpected argument 'my-project' found
Usage: dx create [OPTIONS]
For more information, try '--help'.
```
=> fix: no project-name in argument of `dx create`

packages/cli/build.rs, packages/cli/src/cli/version.rs
- Replaced `CFG_RELEASE` with `CARGO_PKG_VERSION`
- No rerun on `CFG_RELEASE`
=> using cargo.toml version

packages/html/Cargo.toml
This fixes the dioxus tui renderer. The HTML crate uses serde if the `serialize` feature is enabled but it only enables the serde dependency if the `eval` feature is enabled. This PR changes the features so that serde is enabled if either `eval` or `serialize` is enabled
=> Enable serde dependency in the html crate even if eval is disabled

packages/autofmt/tests/samples/attributes.rsx, packages/autofmt/tests/samples/complex.rsx, packages/core/src/virtual_dom.rs, packages/rsx/src/element.rs
Our current way of deduplicating event listeners at runtime is flawed. We stop once we reach the first dynamic attribute at the event path instead waiting for the first event listeners. This PR fixes that issue by moving duplicate event listener detection to compile time in the rsx macro
fixes https://github.com/DioxusLabs/dioxus/issues/1811
=> check for duplicate event listeners in the rsx macro

packages/cli/src/builder.rs
When using the dev profile in dioxus-cli (i.e. `dx build --profile dev --platform web`) it will panic saying that path `target/wasm32-unknown-unknown/dev/..` does not exist. This is because the build target for the dev profile is `debug` and not `dev`. This PR fixes that by mapping the build profile to the correct build target.
I tried building dioxus-cli to test that this works, but I am met with the following build error:
```
The following warnings were emitted during compilation:
warning: rav1e@0.7.1: Unable to run nasm: No such file or directory (os error 2)
error: failed to run custom build command for `rav1e v0.7.1`
Caused by:
process didn't exit successfully: `/Users/lidin/Documents/Projekt/dioxus/target/release/build/rav1e-7f05fd8e16f8cdbd/build-script-build` (exit status: 101) …
```
=> dioxus-cli: Fix panic when using dev profile

packages/cli/src/builder.rs
This PR fixes a minor wording issue within the CLI when building.
=> fix wording in CLI message

packages/html/src/elements.rs
This PR adds a [MathML Core](https://w3c.github.io/mathml-core/#mathml-elements-and-attributes) support to the rsx as discussed in issue https://github.com/DioxusLabs/dioxus/issues/1778.
Deprecated tags and attributes are not included in the code base.
annotation-xml is aliased to annotationXml due to the naming restrictions of rsx macro.
@stefnotch @Jah-On
=> Adding MathML Core support to rsx

packages/web/src/cfg.rs, packages/web/src/dom.rs
This PR affects dioxus-web and allows to specify a direct element as dom-root. Before, it was necessary to specify the element by ID. This is annoying, for example if the element was created dynamically.
It is now possible to directly specify the element:
```rust
let doc = web_sys::window().unwrap().document().unwrap();
let elem = doc.get_element_by_id("main").unwrap();
use dioxus_web::Config;
dioxus_web::launch_cfg(App, Config::new().rootelement(elem));
```
This is equivalent to
```rust
use dioxus_web::Config;
dioxus_web::launch_cfg(App, Config::new().rootname("main"));
```
The old approaches still work. This PR just adds the new method `Config::rootelement`. It is necessary for dynamically created elements, for example in shadow roots.
Unfortunately, it still does not work with iframes …
=> dioxus-web: Add `Config::rootelement`

packages/cli/src/cli/cfg.rs
- added a new group to `ConfigOptsServe` that conflicts with `release`
- added `hot_reload` to the group
- changed help comment of `hot_reload`
Using `--hot-reload` option with `--release` now shows:
```
error: the argument '--release' cannot be used with '--hot-reload'
Usage: dx.exe serve --release [-- <CARGO_ARGS>...]
For more information, try '--help'.
```
Also reflected on help:
```
--hot-reload
Build with hot reloading rsx. Will not work with release builds. [default: false]
```
Instead of my approach, the `"release-incompatible"` group could also be refactored into a struct using the '#[group]' macro, moving the incompatible arguments inside and flattening them to the `ConfigOptsServe` struct.
closes #1757
=> Mark hot-reload flag incompatible with release

packages/desktop/headless_tests/events.rs, packages/html/src/events/keyboard.rs, packages/html/src/web_sys_bind/events.rs, packages/interpreter/src/interpreter.js, packages/rink/src/hooks.rs
Added isComposing to the js interpreter and updated necessary implementations of keyboard logic.
Since crossterm doesn't seem to have a similar feature to isComposing from the KeyboardEvent web API, I've set the value to be false when translating a crossterm key event.
Also, looks like the code snippet in the docs [here](https://dioxuslabs.com/learn/0.4/cookbook/custom_renderer#event-loop) will need to reflect the changes. I can create a pr for that once this pr is resolved 👍 
closes #1857
=> Add `isComposing` support

packages/desktop/src/webview.rs
In the wry 0.32 examples the linux webviews are initialized in a different way to render properly using
tao::platform::unix::WindowExtUnix. Tested with Gnome 45.3 and Wayland.
The changes was taken from the wry example files like https://github.com/tauri-apps/wry/blob/7234b2b99a8efc59484c96b767f3be8b52127816/examples/simple.rs#L16
=> fix: initialize linux wry webview

Cargo.lock, packages/cli/Cargo.toml
When building the `dx` CLI there is 1 less dependency (from 710 to 709). I thought this is pretty nice, because it's a double win.
=> Removed 1 CLI dependency by updating `cargo-generate`

packages/cli/src/main.rs
Before the top-level error message would print the dependent error message. Now multiple nested errors can be shown (with anyhow context).
Example (for demonstrative purposes only):
Before:
```
Error: 🚫 Serving project failed: Couldn't copy the server binary from "/tmp/fullstack/.dioxus/ssr/debug/fullstack" to "/tmp/fullstack/dist/fullstack". Maybe the server process (fullstack) wasn't killed and is still running.
```
After:
```
Error: 🚫 Serving project failed:
Caused by:
0: Couldn't copy the server binary from "/tmp/fullstack/.dioxus/ssr/debug/fullstack" to "/tmp/fullstack/dist/fullstack". Maybe the server process (fullstack) wasn't killed and is still running.
1: Text file busy (os error 26)
```
=> refactor(cli): added multiple nested errors support

packages/cli-config/src/config.rs, packages/cli/src/assets.rs, packages/cli/src/builder.rs, packages/cli/src/cli/bundle.rs, packages/cli/src/plugin/mod.rs, packages/cli/src/server/desktop/mod.rs, packages/cli/src/server/web/mod.rs
`out_dir` and `asset_dir` are now methods, because they derive from `crate_dir` and `dioxus_config`. As a result a few other files had to be updated as well.
=> Converted `out_dir` and `asset_dir` fields to methods in `CrateConfig` (cli-config refactor)

packages/cli/src/cli/cfg.rs
Same as `cargo build` has `-r` now `dx build` and `dx bundle` also have it. Since user probably wants to use these commands for production-ready artifacts, the `--release` option is probably used often, same as with `cargo build`. This allow users to use the same `build -r` "pattern".
=> feat(cli): added short `release` build option

Cargo.lock, Cargo.toml, packages/generational-box/src/lib.rs, packages/generational-box/src/sync.rs, packages/generational-box/src/unsync.rs, packages/signals/Cargo.toml, packages/signals/examples/map_signal.rs, packages/signals/src/copy_value.rs, packages/signals/src/global/memo.rs, packages/signals/src/global/signal.rs, packages/signals/src/impls.rs, packages/signals/src/map.rs, packages/signals/src/read.rs, packages/signals/src/read_only_signal.rs, packages/signals/src/signal.rs, packages/signals/src/write.rs
This PR makes mapped signals implement readable. It also restructures the readable and writable traits to make the target and storage types associated types which lets us remove generics and boilerplate in a few places.
The new version of Mapped signals also now works with any readable type including user types
=> Implement Readable for mapped signal

packages/core/src/virtual_dom.rs, packages/web/src/lib.rs
This PR fixes an infinite loop that happens when suspense starts on the client. Currently suspense causes tasks to stop being polled which makes suspense never resolve and causes an infinite loop. Stacked on #1925.
This example does not work on the git version of dioxus but does work in this PR:
```rust
use serde::{Deserialize, Serialize};
let mut count = use_signal(|| 1);
rsx! {
button { onclick: move |_| count += 1, "Up high!" }
for i in 0..count() {
Child {}
}
}
}
fn Child() -> Element {
let server_future = use_server_future(get_server_data)?;
rsx! {
h1 { "Hello, World!" }
"{server_future.state():?}"
}
}
#[server]
async fn get_server_data() -> Result<String, ServerFnError> {
Ok(reqwest::get("https://httpbin.org/ip").await?.text().await?)
} …
```
=> Fix client side suspense

packages/web/src/lib.rs
The web renderer will currently freeze if the hot-reload web socket does not connect because one side of the channel is dropped which causes the future to resolve immediately. That future is awaited in a loop which causes the page to freeze. This PR fixes that issue by not resolving the future when the other side of the channel is dropped
Fixes #1924
=> Fix the web renderer freezing when the hot reload connection fails

packages/dioxus/Cargo.toml, packages/dioxus/build.rs, packages/dioxus/src/launch.rs, packages/signals/Cargo.toml
I have seen a few people try to launch a app without any features and running into a blank screen with no errors. This PR adds a compile time warning and panics if you try to call launch builder without any renderers enabled
=> Warn the user if they try to launch without a renderer selected

packages/router-macro/src/lib.rs, packages/router-macro/src/segment.rs
`Routable` creates types which derive `PartialEq`, but can also derive `Eq`. Clippy complains about this. This PR makes them derive `Eq` as well. If deriving only `PartialEq` is intentional let me know and I'll add an `#[allow]` instead.
=> Fix Clippy warning in `Routable` macro

Cargo.lock, packages/desktop/src/protocol.rs, packages/interpreter/Cargo.toml, packages/interpreter/src/common_exported.js, packages/interpreter/src/interpreter.js, packages/interpreter/src/lib.rs, packages/interpreter/src/sledgehammer_bindings.rs, packages/liveview/src/main.js, packages/web/src/dom.rs, packages/web/src/mutations.rs, packages/web/src/rehydrate.rs
The new version of sledgehammer bindgen uses a class instead of globals to work towards fixing https://github.com/DioxusLabs/dioxus/issues/1907
=> Bump the sledgehammer bindgen version

packages/signals/README.md, packages/signals/src/copy_value.rs, packages/signals/src/signal.rs, packages/signals/tests/create.rs
Signals should be owned by the scope they were created in. They use an owner which lives in the context API. Dioxus signals had a bug that caused child scopes to use the parent scope's owner and only drop when that parent is dropped. This PR fixes the leak by only looking for the signal owner in the current scope instead of looking through all parent scopes (including the root scope). 
Closes #1999
=> Fix signals leaking memory

packages/fullstack/src/render.rs, packages/fullstack/src/server_context.rs, packages/router/src/router_cfg.rs
The fullstack renderer renders on a dedicated thread which should be fine to block in. This PR wraps rebuilding the virtual dom in a wrapper that tells tokio it is ok to block. Rebuilding the virtual dom runs user code which may use blocking tokio operations (like reading the fullstack history)
=> Fix fullstack history

Cargo.lock, Cargo.toml, packages/interpreter/src/sledgehammer_bindings.rs
We were missing a `let` for `els` in the JS bindings.
It's weird that this wasn't getting caught by the fullstack tests. Not sure what happened - maybe we bypassed merge or something?
=> fix sledgehammer bindings on web

packages/interpreter/src/write_native_mutations.rs
fix #1970 
Not actually an issue in diffing! Just an issue with a single pushroot command.
=> Fix: pushroot should actually push the right root on native mutations

Cargo.lock, examples/memo_chain.rs, packages/core/src/dirty_scope.rs, packages/core/src/global_context.rs, packages/core/src/runtime.rs, packages/core/src/scope_arena.rs, packages/core/src/scope_context.rs, packages/core/src/tasks.rs, packages/core/src/virtual_dom.rs, packages/core/tests/suspense.rs, packages/core/tests/task.rs, packages/fullstack/examples/static-hydrated/src/main.rs, packages/fullstack/src/hooks/server_future.rs, packages/hooks/src/use_effect.rs, packages/hooks/src/use_memo.rs, packages/hooks/src/use_resource.rs, packages/signals/Cargo.toml, packages/signals/src/copy_value.rs, packages/signals/src/global/memo.rs, packages/signals/src/global/signal.rs, packages/signals/src/impls.rs, packages/signals/src/lib.rs, packages/signals/src/memo.rs, packages/signals/src/reactive_context.rs, packages/signals/src/signal.rs, packages/signals/src/write.rs
This PR fixes suspense polling futures that are unrelated to suspense. This will fix some hydration errors including https://github.com/DioxusLabs/dioxus/issues/1804.
Currently during suspense, all futures that have been spawned will be polled until suspense is finished. This causes hydration issues if a future finishes on the server but not the client and renders different content.
Fixes #2003
Fixes #1935
=> Only poll suspended futures, lazy memos

examples/dog_app.rs, examples/suspense.rs, packages/desktop/headless_tests/rendering.rs, packages/generational-box/src/lib.rs, packages/generational-box/src/sync.rs, packages/generational-box/src/unsync.rs, packages/router/examples/simple_routes.rs, packages/router/src/contexts/router.rs, packages/signals/examples/errors.rs, packages/signals/src/copy_value.rs, packages/signals/src/global/memo.rs, packages/signals/src/global/signal.rs, packages/signals/src/map.rs, packages/signals/src/memo.rs, packages/signals/src/reactive_context.rs, packages/signals/src/read.rs, packages/signals/src/read_only_signal.rs, packages/signals/src/signal.rs, packages/signals/src/write.rs
This PR renames the `take` method on signals to `manually_drop` to make it easier to find and restore local lifetime tracking for signals.
Note while local lifetime tracking can help prevent some bugs at compile time, it can make some common situations less ergonomic including [matching the value of a resource](https://github.com/ealmloff/dioxus/blob/5f9e5f607b94aa92cd90584a97bb1c1b28198963/examples/dog_app.rs#L83):
```rust
// fut.read() now causes an error
match fut.read_unchecked().as_ref() {
Some(Ok(resp)) => rsx! {
button { onclick: move |_| fut.restart(), "Click to fetch another doggo" }
div { img { max_width: "500px", max_height: "500px", src: "{resp.message}" } }
},
Some(Err(_)) => rsx! { div { "loading dogs failed" } },
None => rsx! { div { "loading dogs..." } },
}
```
Closes …
=> Restore signal lifetimes; rename take to manually drop

examples/openid_connect_demo/Dioxus.toml, packages/cli-config/src/config.rs, packages/cli/src/assets/dioxus.toml, packages/cli/src/cli/serve.rs
Closes https://github.com/DioxusLabs/dioxus/issues/1808
=> added hot-reload as config option with default to true

packages/core-macro/src/lib.rs, packages/core/tests/diff_element.rs, packages/rsx/src/lib.rs
Return None when rendering empty templates.
=> Fix 2020: return None if the root nodes are empty in rsx

packages/core-macro/src/props/mod.rs, packages/signals/examples/read_only_degrade.rs
This commit fixes the owned impl to use the original generics rather than the build generics.
I've also added a little compile test in the form of an example in the signals repo.
=> fix #1979: generated Owned impl for the props builder was using the wrong generics

packages/core-macro/src/props/mod.rs
This PR fixes the visibility of the struct the core macro generates to make Into<ReadOnlySignal> work.
Fixes #2053
=> Fix the visibility of the read only signal helper struct

packages/native-core/src/real_dom.rs, packages/router-macro/src/route_tree.rs, packages/router-macro/src/segment.rs, packages/rsx/src/hot_reload/hot_reload_diff.rs
this PR fixes typo `varient` -> `variant`
=> fix typo varient -> variant

Cargo.lock, Cargo.toml, packages/cli-config/src/config.rs, packages/cli/src/assets.rs, packages/cli/src/builder.rs, packages/cli/src/server/desktop/mod.rs, packages/cli/src/server/mod.rs, packages/desktop/src/protocol.rs
This PR bumps Manganis which fixes assets built for one example carrying over to other examples. It also cleans up some of the logic to find the path to output binary for cargo builds.
=> Fix Manganis assets overlapping between examples

packages/hooks/src/use_resource.rs, packages/rsx/src/lib.rs
Implements copy for the resource type and fixes temporary reads in rsx by introducing a block
Fixes #2036
=> Implement copy for Resource

packages/signals/src/signal.rs
A few people have run into issues updating from use_ref to use_signal because of write_silent.
This PR adds a write_silent method to signals to make updating from use_ref slightly easier. The method is depreciated in favor of peek
=> Restore write_silent as a deprecated function with updated recommendations

packages/interpreter/Cargo.toml
This moves from the git version of sledgehammer bindgen to the crates.io `0.5.0` version before we publish dioxus `0.5.0-alpha.1`
=> Bump sledgehammer bindgen to a stable release

Cargo.lock, packages/dioxus/Cargo.toml
Mobile relies on dioxus-desktop and without it, cargo complains about undeclared crates or modules named ``dioxus-desktop``
=> Fix: Add dioxus-desktop To Mobile Feature

Cargo.lock, examples/spread.rs, packages/core-macro/src/component.rs, packages/core/Cargo.toml
Allows users to specify `props: SomeProps` and skip the generation of the props struct.
=> Fix #1938, allow explicit props
