DioxusLabs/dioxus

packages/core/src/mutations.rs
packages/desktop/src/index.js
packages/ssr/src/lib.rs
packages/web/Cargo.toml
packages/web/examples/hydrate.rs
packages/web/src/dom.rs
packages/web/src/lib.rs
packages/web/src/rehydrate.rs
packages/web/tests/hydrate.rs

This PR substantially improves hydration, making it more robust.
Most importantly, it respects using comments as spacer elements in pre-generated HTML.

Feat: Improve rehydration by using the VDom directly.

---

packages/core-macro/src/rsx/component.rs

This PR fixes the detection of formatting in component fields, so we can accept any sort of formatting.

Fix: string formatting detection in component fields

---

packages/desktop/src/index.js

Reminiscent of:
https://github.com/facebook/react/issues/955
This has been fixed in the web renderer since the beginning, but never made it into the desktop renderer, unfortunately.

fix: cursor jumping in desktop inputs

---

README.md
notes/README/ZH_CN.md

In this PR I add a `Chinese` Readme

Add `Chinese` Language `Readme` and add some info into README.md

---

packages/web/src/dom.rs
packages/web/src/rehydrate.rs

Actually increment the event delegation counter during hydration.

fix: ssr + hydration event listeners

---

packages/core/src/scopes.rs

This PR makes it possible to provide a shared context for any component given its ScopeId - making it possible to provide default context providers at the root scope if they don't already exist.

feat: allow context providers to provide for any scope

---

examples/nested_listeners.rs
packages/desktop/src/index.html
packages/desktop/src/lib.rs
packages/jsinterpreter/interpreter.js
packages/jsinterpreter/interpreter.ts
packages/jsinterpreter/tsconfig.json
packages/web/src/dom.rs

This PR adds "dom climbing" in JS so we don't need to generate a dioxus ID for every element. This speeds up dom patching significantly (+15%) and is overall cleaner.

feat: remove dioxus id on non-event elements

---

README.md

docs: add azul compairson

---

examples/borrowed.rs
examples/calculator.rs
examples/crm.rs
examples/dog_app.rs
examples/file_explorer.rs
examples/filedragdrop.rs
examples/framework_benchmark.rs
examples/inputs.rs
examples/pattern_model.rs
examples/router.rs
examples/suspense.rs
examples/tailwind.rs
examples/tasks.rs
examples/todomvc.rs

Our CI generates a bunch of warnings because of clippy on the examples. This PR fixes that.

Make clippy happier on the examples.

---

packages/desktop/src/lib.rs
packages/web/src/cfg.rs
packages/web/src/lib.rs

Correct dioxus web docs to include the third paramter

---

CHANGELOG.md
Cargo.toml
packages/core-macro/CHANGELOG.md
packages/core-macro/Cargo.toml
packages/core/CHANGELOG.md
packages/core/Cargo.toml
packages/core/src/nodes.rs
packages/desktop/CHANGELOG.md
packages/desktop/Cargo.toml
packages/desktop/src/interpreter.js
packages/desktop/src/lib.rs
packages/hooks/CHANGELOG.md
packages/hooks/Cargo.toml
packages/html/CHANGELOG.md
packages/html/Cargo.toml
packages/mobile/CHANGELOG.md
packages/mobile/Cargo.toml
packages/router/CHANGELOG.md
packages/router/Cargo.toml
packages/ssr/CHANGELOG.md
packages/ssr/Cargo.toml
packages/web/CHANGELOG.md
packages/web/Cargo.toml
packages/web/src/bindings.rs
packages/web/src/interpreter.js

Not everything is done for 0.1.8, but there's so many changes that the next major release is 0.2.0. This release is mostly for bug fixes

release: 0.1.8

---

.github/workflows/main.yml

There is some issue with running tests from CI Workflow.

fix ci test workflow

---

docs/guide/src/README.md
docs/guide/src/elements/conditional_rendering.md
docs/guide/src/elements/index.md
docs/guide/src/elements/lists.md
docs/guide/src/elements/special_attributes.md
docs/guide/src/elements/vnodes.md

Mostly edited for readability, but I also corrected a few outdated statements & typos.
I'm fairly confident my changes are correct, but I should mention I am new to Dioxus (though familiar with Rust and React).

Minor docs improvements, chapters 1-5

---

docs/reference/src/platforms/ssr.md

Closes: #259 
Includes some extra changes from auto-formatting.

docs(reference/platforms/ssr): fixing example and commands

---

packages/core/src/scopes.rs
packages/fermi/src/root.rs
packages/hooks/src/use_shared_state.rs
packages/hooks/src/usefuture.rs
packages/hooks/src/useref.rs
packages/hooks/src/usestate.rs
packages/router/src/service.rs

Context: https://discord.com/channels/899851952891002890/943190901159768136/946104733301633084

Improve scheduler methods in ScopeState

---

Cargo.toml
docs/guide/src/hello_world.md
docs/guide/src/setup.md

Add options for compilation on systems that lack libappindicator3

---

README.md
docs/router/src/README.md
docs/router/src/SUMMARY.md
docs/router/src/chapter_1.md
docs/router/src/guide/building-a-nest.md
docs/router/src/guide/first-route.md
docs/router/src/guide/getting-started.md
docs/router/src/guide/index.md
docs/router/src/guide/redirection-perfection.md
docs/router/src/reference/index.md

Router Book

---

packages/hooks/src/useref.rs

This PR allows userefs to be memoized by comparing their shared slots and internal mutation tracker.
This means use_ref can be passed into child components and be memoized if the write histories match up.

feat: memoize useref by tracking mutations

---

.vscode/spellright.dict
docs/posts/allocators.md
docs/posts/release-0-2-0.md
docs/posts/release.md
docs/posts/release_0_1_7.md
docs/posts/release_draft.md

Add the website post for publishing dioxus v0.2

Release post for Dioxus v0.2

---

packages/core/Cargo.toml
packages/hooks/Cargo.toml
packages/web/Cargo.toml

https://github.com/DioxusLabs/dioxus/issues/312

Remove release_max_level features from several Cargo.toml log dependencies

---

examples/README.md
examples/inlineprops.rs
packages/core-macro/src/inlineprops.rs

See `examples/inlineprops.rs` for my whole 4 test cases

`#[inline_props]` generics

---

docs/guide/src/components/component_children.md
docs/guide/src/components/propsmacro.md
docs/guide/src/elements/conditional_rendering.md
docs/guide/src/elements/special_attributes.md
docs/guide/src/elements/vnodes.md
docs/guide/src/hello_world.md
docs/guide/src/interactivity/event_handlers.md
docs/guide/src/interactivity/index.md
docs/guide/src/interactivity/user_input.md
docs/guide/src/interactivity/usestate.md
docs/guide/src/state/index.md
docs/guide/src/state/router.md

Everything relates to the text rather than the code, unless there were some trivial formatting changes like removing whitespace. 
If you want, I can squash all these commits into one.

Minor improvements to the guide

---

notes/README/ZH_CN.md

Fixed example

---

examples/custom_html.rs
examples/tailwind.rs
packages/desktop/src/cfg.rs
packages/desktop/src/desktop_context.rs
packages/desktop/src/index.html
packages/desktop/src/lib.rs
packages/desktop/src/protocol.rs

This PR allows customizing the index.html and HEAD of the desktop document. It's very useful for working with 3rd party JS libraries.

feat: allow customizing the index and head

---

packages/fermi/src/hooks/state.rs
packages/fermi/src/lib.rs
packages/fermi/src/root.rs

This PR adds a new hook to Fermi that is functionally equivalent to 
I have not yet adjusted documentation or made make_mut work properly.

feat: Add a use_state equivalent for Fermi

---

packages/tui/src/hooks.rs

add offset mouse data to tui

---

packages/tui/src/hooks.rs

onmousemove was not checking if the mouse has moved. onmousepress and onmousereleased were switched

only trigger onmousemove if the position has changed (tui)

---

packages/tui/src/hooks.rs
packages/tui/src/lib.rs

- only iterate though elements and check collisions if the mouse state is correct.
- only re-render if some render state has changed.

Tui performance improvements

---

packages/hooks/src/useref.rs

Hi, I was going through the hooks files and spot this small typo.
Thanks again for such an amazing framework. 💯

Update useref.rs defualt -> default

---

examples/window_zoom.rs
packages/desktop/src/desktop_context.rs

- Print: open print modal
- SetZoomLevel: change webview zoom level

Add some new window api for desktop

---

packages/web/Cargo.toml

Fix: enable `dioxus-core` `serialize` feature in `dioxuse-web`

---

packages/core-macro/src/rsx/component.rs
packages/core/src/diff.rs
packages/core/src/events.rs
packages/core/src/nodes.rs
packages/core/src/util.rs
packages/html/src/events.rs
packages/native-core/src/real_dom.rs
packages/native-core/src/state.rs
packages/web/src/lib.rs

Some doc links are broken or outdated. This fixes them.

fix broken doc links

---

packages/core/src/scopes.rs
packages/core/src/virtual_dom.rs
packages/fermi/src/root.rs

c97f051bbd198d3177de6bef362b8ba16a00ae72 usablity improvement
7576426c936c7184eab073f0cc669cd4852f5597 code cleanup & an outdated comment
7576426c936c7184eab073f0cc669cd4852f5597 doc update
3cbf8ed6fafca4cacb03790a5ac366dedbe5118c fix edge case bug?
Please review commit by commit, Thanks!

small updates

---

packages/tui/src/hooks.rs

crossterm outputs a backtab character when both shift and tab are pressed.

handle backtab for tui

---

packages/tui/Cargo.toml
packages/tui/src/lib.rs
packages/tui/tests/events.rs

Test that all tui keyboard and mouse events are received and if applicable, have the right event data.

test tui events

---

Cargo.toml
docs/reference/src/guide/hot_reloading.md
packages/core-macro/Cargo.toml
packages/core-macro/src/lib.rs
packages/desktop/Cargo.toml
packages/desktop/src/controller.rs
packages/web/Cargo.toml
packages/web/src/lib.rs
src/lib.rs

I think use `hot-reload` is better

change the hot_reload feature to hot-reload

---

packages/interpreter/src/interpreter.js

When a text node is removed the interpreter trys to get the id attribute to remove any listeners, but that only works on elements, so it panics.
fixes #465

check that an node is an element before removing listeners

---

packages/hooks/src/use_shared_state.rs
packages/hooks/src/useref.rs
packages/hooks/src/usestate.rs

This makes clippy (and me) happy

Remove unneeded lifetimes

---

docs/guide/src/en/custom_renderer/index.md

Hey!
Just a quick PR fixing some typos and and code samples.

Fix typos and update code on custom renderer docs

---

packages/desktop/src/cfg.rs
packages/desktop/src/lib.rs

fixes #511 and #512
It also comments out with_event_handler because it is currently not implemented.

expose DesktopConfig in public interface

---

packages/fermi/README.md

Just a quick fix for Fermi's usage instructions

docs: Fix Fermi's usage instructions

---

packages/native-core-macro/src/lib.rs
packages/native-core-macro/src/sorted_slice.rs
packages/native-core/src/node_ref.rs
packages/native-core/src/real_dom.rs
packages/native-core/src/state.rs
packages/native-core/src/traversable.rs
packages/native-core/src/utils.rs

Adds more internal comments and documentation to the native core and native core macro crates. It also renames some private functions/types to improve readability.

Improve documentation for the native core and native core macro crates

---

packages/router/src/cfg.rs
packages/router/src/components/router.rs
packages/router/src/service.rs
packages/router/usage.md

It seems that there was no way, nor workaround to set an active url when doing ssr, so I added a new prop to the router component.

Added initial_url to the router component

---

.vscode/settings.json
docs/guide/examples/component_props_options.rs
docs/guide/examples/hooks_bad.rs
docs/guide/examples/hooks_composed.rs
docs/guide/examples/hooks_use_ref.rs
docs/guide/examples/meme_editor_dark_mode.rs
docs/guide/examples/rendering_lists.rs
examples/calculator.rs
examples/custom_html.rs
examples/file_explorer.rs
examples/filedragdrop.rs
examples/flat_router.rs
examples/hydration.rs
examples/pattern_model.rs
examples/rsx_usage.rs
examples/suspense.rs
examples/tailwind.rs
examples/todomvc.rs
examples/window_event.rs
packages/desktop/src/cfg.rs
packages/desktop/src/lib.rs
packages/router/src/service.rs
packages/tui/src/style_attributes.rs
packages/web/examples/hydrate.rs
packages/web/src/cfg.rs
packages/web/src/dom.rs
packages/web/src/lib.rs
packages/web/src/olddom.rs
packages/web/tests/hydrate.rs

In the spirit of breaking changes to reduce some sharp edges, this PR introduces a more straightforward pattern for configuration of desktop and web apps. This brings these platforms in line with the TUI crate which has always expected an explicit configuration object.

Less clumsy configuration for desktop and mobile

---

packages/core-macro/src/props/mod.rs
packages/core/src/diff.rs
packages/core/src/dynamic_template_context.rs
packages/core/src/nodes.rs
packages/core/src/scopes.rs
packages/core/src/template.rs
packages/core/src/virtual_dom.rs
packages/desktop/src/desktop_context.rs
packages/desktop/src/protocol.rs
packages/native-core-macro/tests/update_state.rs
packages/native-core/src/node_ref.rs
packages/native-core/src/real_dom.rs
packages/rsx/src/component.rs
packages/rsx/src/elements.rs
packages/rsx/src/error.rs
packages/rsx/src/template.rs
packages/ssr/src/lib.rs
packages/tui/src/focus.rs
packages/tui/src/layout.rs
packages/web/src/dom.rs

Fixes the clippy errors introduced by #488

pass clippy

---

packages/autofmt/src/buffer.rs
packages/autofmt/src/expr.rs
packages/core/src/arbitrary_value.rs

Unsure of how these slipped in - might've been pending work when switching between branches.

fix: master containing random commit that's failing master build

---

packages/desktop/Cargo.toml
packages/desktop/src/cfg.rs
packages/desktop/src/protocol.rs

The 0.22.0 release should be imminent.
- [0] https://github.com/tauri-apps/wry/pull/698

Update wry to 0.22.0

---

docs/guide/src/en/getting_started/mobile.md

Fix the Android support disagreement in the docs

---

packages/desktop/Cargo.toml
packages/desktop/src/controller.rs
packages/desktop/src/desktop_context.rs

So this would allow drawing an ios screen ontop of the webview that could be exited later. Is this a feature we can add to dioxus?

Implement push view for ios.

---

packages/interpreter/Cargo.toml

Bumps sledgehammer version to fix non-ascii characters in text

fix non-ascii characters on web renderer

---

examples/crm.rs
packages/core/src/arena.rs
packages/core/src/create.rs
packages/core/src/diff.rs
packages/core/src/lazynodes.rs
packages/core/src/scope_arena.rs
packages/core/src/scopes.rs
packages/core/src/virtual_dom.rs
packages/core/tests/miri_simple.rs

I had fixed this long ago but accidentally reintroduced it in #600 . This fixes it completely (hopefully!).

Make borrowed props attached to the scope that created them

---

packages/core/Cargo.toml
packages/core/src/arena.rs
packages/core/src/diff.rs
packages/core/tests/attr_cleanup.rs
packages/core/tests/diff_unkeyed_list.rs

Fixes tests for core so master builds again. Transforms a remove into replace for more efficient mutation streams.

fix: core tests and use stack optimization for replace + remove

---

.github/workflows/main.yml
Cargo.toml
packages/native-core/src/utils/cursor.rs
packages/tui/src/widgets/number.rs
packages/tui/src/widgets/password.rs
packages/tui/src/widgets/slider.rs
packages/tui/src/widgets/textbox.rs
packages/web/src/dom.rs
packages/web/src/lib.rs

Clippy isn't really doing anything right now since it's not checking the whole workspace. This forces clippy to check everything

chore: add clippy workspace flag to check all crates

---

packages/liveview/src/main.js

fix: dont send initialize until WS is connected 

---

Cargo.toml
examples/multiwindow.rs
examples/overlay.rs
packages/desktop/src/desktop_context.rs
packages/desktop/src/lib.rs
packages/desktop/src/waker.rs
packages/desktop/src/webview.rs

Super simple multiwindow support.
If you want to communicate between windows, it'll require some channels or some shared context.
In theory you can get fermi to bridge the gap between two windows, but that isn't supported here.
https://user-images.githubusercontent.com/10237910/210123113-3d43d4ba-21be-4e84-972c-a3a21e7df07a.mov

Simple desktop multiwindow support

---

examples/custom_assets.rs
packages/desktop/src/protocol.rs
packages/desktop/src/webview.rs

fix: properly canonicalize assets

---

examples/multiwindow.rs

Not sure if my assumption is correct but it seemed this was the intention of the popup fn.

fix(Examples/Multi-Window): launch the popup content instead of app.

---

docs/guide/examples/event_nested.rs
examples/nested_listeners.rs
examples/window_event.rs
packages/core/src/events.rs
packages/core/src/scopes.rs
packages/core/src/virtual_dom.rs
packages/hooks/src/useref.rs

https://en.wiktionary.org/wiki/propogation

Fix typo: propogate -> propagate

---

packages/core/src/nodes.rs
packages/interpreter/src/interpreter.js
packages/native-core/src/node.rs
packages/native-core/src/real_dom.rs

This PR adds support for optionally adding attributes with Option<AttributeValue>. This makes code to toggle attributes much simpler and more efficient.
closes #530

Support optional attributes

---

packages/native-core/src/real_dom.rs

This removes nodes from the real dom listener list when the node is removed from the dom to ensure the ids in the list are always valid

remove nodes from listener list when the node is removed

---

packages/core/src/create.rs

In #651 templates were changed to be stored by there path first and then the byte index.
This PR updates the code that checks if the template was already registered to check for templates in the same way they are inserted. This fixes the issue where templates were being rebuilt many times causing poor performance

fix templates being registered in mutations many times

---

packages/dioxus/Cargo.toml

Fix issue #733 by bumping the msrv version

Update minimum supported rust version to 1.65

---

packages/html/src/elements.rs
packages/html/src/global_attributes.rs

Fix global attribute translation and convert some attributes to snake case

---

packages/core/tests/fuzzing.rs

This PR adds a fuzzing test to dioxus-core that creates and then diffs random nodes and templates. It is notably missing code to fuzzes keyed diffing. Because this generates random nodes it will hit code paths that are more uncommon. The manual tests we already have can better test diffing nodes that are more similar.

Add fuzzing test to dioxus-core

---

packages/interpreter/src/sledgehammer_bindings.rs

Fix boolean attributes with the web renderer

---

packages/liveview/Cargo.toml

I noticed, that there were some dependencies and dependency features that were not necessary. This PR fixes that.

Remove unnecessary dependencies and dependency features in `Cargo.toml` of `dioxus-liveview`

---

packages/autofmt/src/element.rs
packages/autofmt/src/expr.rs
packages/autofmt/src/writer.rs
packages/autofmt/tests/samples.rs
packages/autofmt/tests/samples/ifchain_forloop.rsx
packages/rsx/src/node.rs

Should round out all the autoformatting.

feat: allow ifchains and for loops in autofmt

---

packages/native-core/tests/fuzzing.rs

This is a follow up to #721 that uses the same fuzzing test to test native-core.

Add fuzzing test to native core

---

docs/guide/src/en/custom_renderer/index.md

This finishes updating the custom renderer section in the guide for the 0.3 release

Update custom renderer docs

---

packages/hot-reload/src/lib.rs

Compiling dioxus app doesn't work in release mode

Fix release build

---

packages/core/src/scopes.rs

Only add non-static components to the borrowed_props list

---

packages/core/src/lib.rs
packages/core/src/mutations.rs
packages/web/Cargo.toml
packages/web/src/cfg.rs
packages/web/src/dom.rs
packages/web/src/lib.rs
packages/web/src/rehydrate.rs

Hydration functionality was removed when templates were added. This re-implements hydration.
closes #809

Implement Hydration

---

packages/desktop/src/desktop_context.rs
packages/desktop/src/lib.rs
packages/liveview/src/pool.rs
packages/tui/src/lib.rs

Fixes some areas where conditional compilation was failing when the hot reloading features in different packages were disabled

Fix conditional compilation for hot reloading

---

packages/core/src/create.rs

Fixes some warnings in dioxus-core that appear in release builds

Fix release build warnings

---

packages/interpreter/src/interpreter.js

Fix text dynamic node not assigning id

---

packages/hot-reload/src/lib.rs
packages/rsx/src/hot_reload/hot_reloading_file_map.rs

Makes the initial read of files for the hot reloading macro respect .gitignore and excluded files. This improves the initial load time performance of the hot reload macro

Hot reloading: filter initial read of files by excluded files

---

packages/ssr/Cargo.toml
packages/ssr/src/cache.rs
packages/ssr/src/renderer.rs
packages/ssr/tests/simple.rs

Escapes dynamic and static text in the ssr renderer to allow displaying all characters

Escape text in SSR

---

packages/autofmt/README.md
packages/core-macro/README.md
packages/desktop/README.md
packages/desktop/src/readme.md
packages/dioxus/README.md
packages/hooks/README.md
packages/hot-reload/README.md
packages/html/README.md
packages/interpreter/README.md
packages/liveview/README.md
packages/mobile/README.md
packages/native-core-macro/README.md
packages/native-core/README.md
packages/router/README.md
packages/rsx-rosetta/README.md
packages/rsx/README.md
packages/ssr/README.md
packages/web/README.md

Follow up to https://github.com/DioxusLabs/docsite/commit/a89205a05a79a7a5c68fcdfdb4fc2beff474d3c9 to update the guide links in the readmes with the 0.3 version

Add version to docs links in readmes

---

packages/hot-reload/src/lib.rs
packages/rsx/src/hot_reload/hot_reloading_file_map.rs

Collects any io errors in the hot reloading file map instead of panicking. This prevents panics when the file path is incorrect. Any errors that do not prevent the program from continuing are just collected instead of returning early.

[Hot reloading] Collect non-fatal errors when searching for files

---

packages/fermi/src/root.rs
packages/hooks/src/usefuture.rs

Here're some changes which is required for us to upgrade. 
And I'm glad to help if you have any better idea (API change, method deprecated or even removed).

0.2 -> 0.3 migration changes

---

packages/tui/src/config.rs
packages/tui/src/focus.rs
packages/tui/src/node.rs

Fixes clippy failing on the master branch because of the new lints added in the latest rust release

Fix new Clippy lints

---

docs/guide/src/en/interactivity/custom_hooks.md

Updated links in docs for custom use_hook.

---

packages/router/Cargo.toml

Remove unused simple-logger

---

packages/rsx/src/hot_reload/hot_reloading_file_map.rs

Fix hot reloading in workspace structures that do not have the parent workspace as the direct parent folder

Fix more complex workspaces with hot reloading

---

examples/todomvc.rs

- toggle-all button
- double click modify todo item
- filter state show mouse pointer
- individual todo item remove button
- correct active item count

Add more features to todomvc

---

packages/interpreter/Cargo.toml
packages/interpreter/src/sledgehammer_bindings.rs

Bump sledgehammer-bindgen version

---

packages/desktop/src/file_upload.rs
packages/desktop/src/protocol.rs
packages/interpreter/src/interpreter.js

Fix click and input events on desktop

---

.mailmap

Please feel free to close this PR if the appearance of "Jon Kelley" and "Jonathan Kelley" is intentional.
I simply like mailmaps and their unification powers in a world with immutable history.

Add mailmap to unify name of Jonathan Kelley

---

packages/html/src/elements.rs

Add use element to html

---

packages/fermi/src/hooks/atom_ref.rs

I suggest this PR to be more flexible with Fermi.

Added `.unsubscribe()` and `.force_update()` fn's to Fermi

---

docs/guide/src/en/interactivity/hooks.md

Let me know if you think this should be reworded in any way, or perhaps the additional text could be mentioned below the list of rules if you think that would look better. Or if you don't think this clarification is needed, feel free to close this PR without merging it.

Clarify hooks rules to mention early returns

---

packages/core/src/nodes.rs

Fixes the deserialization of namespaces in templates for hot reloading
Fixes #1046

Fix hot reloading with namespaces

---

packages/interpreter/src/common.js
packages/interpreter/src/interpreter.js

Didn't realize ``bools_attrs`` object was referenced by ``setAttributeInner()``.

Move bool_attrs to common.js

---

packages/autofmt/src/buffer.rs
packages/autofmt/src/component.rs
packages/autofmt/src/element.rs
packages/autofmt/src/lib.rs
packages/autofmt/src/writer.rs
packages/autofmt/tests/samples.rs
packages/autofmt/tests/samples/complex.rsx
packages/autofmt/tests/samples/raw_strings.rsx
packages/autofmt/tests/wrong.rs

Fixes https://github.com/DioxusLabs/dioxus/issues/680

Fix autoformatting raw strings

---

packages/core/src/virtual_dom.rs

Fixes CI on #1064 
When events are fired on placeholder elements, Dioxus panics (you run into this issue if you run the fuzzing test in #1064 long enough)

Fix panic when events trigger on placeholders

---

packages/liveview/Cargo.toml
packages/liveview/examples/salvo.rs

bump liveview salvo version to 0.44.1

Fix: bump liveview salvo version to 0.44.1. (#1124)

---

packages/cli/rustfmt.toml
packages/cli/src/config.rs

Looks like the CLI was using some nightly rustfmt options.

fix: Remove conflicting rustfmt config for cli

---

packages/web/src/util.rs

Makes the web and desktop versions of use_eval both only accept Strings and return a Rc<dyn Fn(String) -> EvalReturn>. Currently the web version of use_eval only returns a borrowed version of the closure which makes it difficult/impossible to use in futures

Make web and desktop use_eval compatible

---

.github/workflows/playwright.yml
.gitignore
Cargo.toml
docs/guide/src/en/contributing/index.md
package-lock.json
package.json
playwright.config.js
playwrite-tests/fullstack.spec.js
playwrite-tests/fullstack/.gitignore
playwrite-tests/fullstack/Cargo.toml
playwrite-tests/fullstack/src/main.rs
playwrite-tests/liveview.spec.js
playwrite-tests/liveview/Cargo.toml
playwrite-tests/liveview/src/main.rs
playwrite-tests/web.spec.js
playwrite-tests/web/Cargo.toml
playwrite-tests/web/src/main.rs

Adds new end to end tests running in a browser for:
- Web: Rendering + Interaction
- Liveview: Rending + Interaction
- Fullstack: Rending + Interaction + Server Communication

create end to end tests using playwright

---

packages/core/src/events.rs

I feel bad opening this PR because it's a really small fix

fix: Fix stop_propagation example

---

playwrite-tests/fullstack/Cargo.toml
playwrite-tests/fullstack/src/main.rs

Makes the playwrite tests compile with the latest version of fullstack

Fix playwrite tests

---

packages/desktop/Cargo.toml
packages/desktop/src/desktop_context.rs
packages/desktop/src/file_upload.rs
packages/desktop/src/lib.rs
packages/desktop/src/mobile_shortcut.rs
packages/desktop/src/shortcut.rs
packages/html/Cargo.toml

Stub out File input and RFD on iOS

---

.github/workflows/main.yml
docs/guide/src/en/contributing/project_structure.md
packages/desktop/headless_tests/events.rs
playwrite-tests/fullstack/src/main.rs

(It is used, just behind feature flags)

Fix playwright fullstack clippy

---

packages/hooks/src/lib.rs

The to_owned macro is helpful to handle hooks with async components, but when using properties it can be problematic because `cx` will be moved in the async block, and will result in a compilation error. This adds a new helper that allows to make either hooks or properties owned.
Note that the macro could be merged with `to_owned`, but having two macros may be better for discoverability (and the to_owned_props may be more expensive at compile time).

Add a helper macro for properties & async

---

packages/core/src/scopes.rs

We noticed that hash takes up quite a bit of binary size in the final wasm. Also, linear scans are faster for small amounts of items, and most people have between 0-10 contexts in a single component at any moment in time.

Use linear scans when searching for contexts

---

packages/web/src/rehydrate.rs

Adds trace level logs for each node during hydration. This should make it more clear where hydration failed.

Add nicer debug messaging in trace level for hydration

---

packages/router/src/history/web.rs

Changes the scroll history to only update when you leave a page instead of setting it every time the user scrolls

Update scroll history lazily when you leave a page

---

Cargo.toml

Router:
- #1275 
- #1273 
- #1274 
- #1272

Release new versions (0.4.1)

---

packages/fullstack/Cargo.toml
packages/server-macro/Cargo.toml

Makes the server macro compile different things based on the currently active features on the server macro (forwarded from the server function crate)

Make server function features flexible

---

notes/README/ZH_CN.md

change
- fix ZH_CN.md  document link

fix: readme awesome link

---

README.md
notes/README/ZH_CN.md
translations/ja-jp/README.md
translations/pt-br/README.md

I created Japanese translated README.

docs: add Japanese README

---

examples/login_form.rs

Fixes the login form example with the new behavior of onsubmit.
Fixes https://github.com/DioxusLabs/dioxus/issues/1297

Fix the login form example

---

notes/README/ZH_CN.md

change
- fix ZH_CN.md  document link

Update ZH_CN.md to use 0.4 version of guide

---

packages/hooks/src/use_on_unmount.rs

fix: Typo on use_on_unmount

---

docs/guide/src/en/getting_started/web.md
examples/PWA-example/README.md
packages/cli/README.md
packages/cli/docs/src/installation.md

This can prevent confusions from the users from now

fix: Add the --locked param to every cli installation command

---

packages/html/src/elements.rs

Add initial_value to textarea

---

packages/desktop/src/protocol.rs
packages/html/src/eval.rs
packages/native-core/src/real_dom.rs
packages/router/src/history/mod.rs
packages/router/src/hooks/use_route.rs
packages/router/src/routable.rs
packages/rsx/src/lib.rs
packages/ssr/src/cache.rs
packages/ssr/src/renderer.rs
packages/ssr/tests/bool_attr.rs

Fix boolean attribute rendering in SSR

---

packages/server-macro/src/lib.rs

fix: Update server function docs link

---

packages/desktop/src/lib.rs
packages/desktop/src/webview.rs

Make window invisible until the first render

---

packages/core/src/arena.rs
packages/core/src/bump_frame.rs
packages/core/src/scope_arena.rs
packages/core/src/scopes.rs

Changes any attributes to drop after renderer to make sure they exist during diffing. Fixes https://github.com/DioxusLabs/dioxus/issues/1561

Drop any attribute after rendering

---

packages/fullstack/Cargo.toml
packages/fullstack/src/server_fn.rs
packages/server-macro/Cargo.toml

Updated server_fn to 0.5.2

---

packages/html/src/global_attributes.rs

Fixes https://github.com/DioxusLabs/dioxus/issues/1659

Add `backdrop-filter` attribute

---

packages/hooks/src/use_future.rs

Fixes [1562](https://github.com/DioxusLabs/dioxus/issues/1562)

Make UseFuture Clone, factor out dependencies field

---

packages/cli/src/server/desktop/mod.rs

Set local_socket_stream to blocking (default)

---

packages/cli/src/server/mod.rs

try to fix #1566 
this PR is more like a workaround, and it might not be perfect. Any comment is welcome.

fix false notification/rebuild for dx hot-reload

---

packages/hot-reload/src/file_watcher.rs
packages/html/src/elements.rs

Fix hot reloading svg elements

---

packages/cli/src/builder.rs
packages/cli/src/cli/build.rs
packages/core/src/diff.rs
packages/dioxus-tui/examples/colorpicker.rs
packages/fermi/src/lib.rs
packages/router-macro/src/redirect.rs
packages/rsx/src/lib.rs
packages/signals/examples/split_subscriptions.rs
packages/web/src/hot_reload.rs

Fixes [1638](https://github.com/DioxusLabs/dioxus/issues/1638)

Wasm target check before build

---

packages/cli/src/builder.rs

error msg: cannot set both --verbose and --quiet

Fix: command error with dx build --verbose

---

packages/cli/Cargo.toml
packages/cli/src/cli/autoformat.rs

Fixes [1520](https://github.com/DioxusLabs/dioxus/issues/1520)

Autoformat ignores files in `.gitignore`

---

packages/web/Cargo.toml
packages/web/src/dom.rs

add error log when root element isn't found

---

examples/all_events.rs
examples/todomvc.rs
packages/desktop/headless_tests/events.rs
packages/dioxus-tui/examples/all_terminal_events.rs
packages/fullstack/src/hooks/server_cached.rs
packages/html/src/events/mouse.rs
packages/web/src/cache.rs

This PR fixes the on double click event and depreciate the old, less readable ondblclick event
Closes #1705

Fix the on double click event and depreciate ondblclick

---

packages/server-macro/src/lib.rs

Closes https://github.com/DioxusLabs/dioxus/issues/1746

Make the type name optional in the server function docs

---

Cargo.lock
packages/desktop/src/config.rs
packages/desktop/src/menubar.rs
packages/desktop/src/webview.rs

Fixes the issue that https://github.com/DioxusLabs/dioxus/pull/1816 papers over.
We still technically need a way of allowing menubars to be modified, etc.

Fix muda segfault

---

packages/desktop/headless_tests/events.rs
packages/liveview/src/pool.rs
packages/web/src/dom.rs
playwright-tests/liveview/src/main.rs
playwright-tests/web/src/main.rs

Fixes https://github.com/DioxusLabs/dioxus/issues/1821

Fix mount event

---

packages/web/src/event.rs

There were some merged conflicts with the new event system that broke form events. This PR fixes that issue.
Closes https://github.com/DioxusLabs/dioxus/issues/1822#issuecomment-1890994140

Fix the web form event

---

packages/cli/src/cli/serve.rs
packages/cli/src/logging.rs
packages/cli/src/main.rs

- restructured match block to not load bin when not required (at `main.rs`)
- removed an unnecessary line? although it might have been there readability (at `logging.rs`)
- there was difference in pattern of if block at same kind of code, so changed it all to `if let` pattern (at `serve.rs`)
If these are ok changes, then I may make more in this same PR?

Minor fixes in cli

---

README.md
translations/zh-cn/README.md

* move Chinese translation file to right directory
* add some missing translate words
* fix some translate issues

docs: move Chinese README to translate directory and update translate

---

packages/core/src/diff.rs
packages/core/tests/diff_element.rs

- attribute diff check now consumes both iterators when both exist
- added a test for attribute diffing
fixes  #1843

Fix attribute diff infinite loop

---

packages/router-macro/src/lib.rs

chore(docs): fixed typo in router-macro

---

packages/liveview/src/adapters/axum_adapter.rs
packages/liveview/src/adapters/rocket_adapter.rs
packages/liveview/src/adapters/salvo_adapter.rs
packages/liveview/src/adapters/warp_adapter.rs

Fixed some typos; added some word capitalization, periods, and ``.

docs(liveview): fixed adapter comments

---

Cargo.toml
examples/README.md
examples/image_generator_openai.rs
examples/weather_app.rs

This PR addresses https://github.com/DioxusLabs/example-projects/issues/25. I also removed all dead links from the [README.md](https://github.com/DioxusLabs/dioxus/blob/b7cc7438eb599db380676e369480a0fc0dbafeba/examples/README.md)
| Example Application       | Repo                                   |
|---------------------------|----------------------------------------|
| dog-app                   | examples/dog_app.rs                    |
| ecommerce-site            | not ported                             |
| file-explorer             | examples/file_explorer.rs              |
| image_generator_open_ai   | examples/image_generator_openai.rs     |
| ios_demo                  | examples/mobile_demo                   |
| jsframework-benchmark     | removed                                |
| …

Address discrepancies between examples repo and examples

---

packages/html/src/global_attributes.rs

Fix https://github.com/DioxusLabs/dioxus/issues/1957

Fix name for SVG attribute "type"

---

packages/html/src/elements.rs

Fix https://github.com/DioxusLabs/dioxus/issues/1981

Restore image element under svg element

---

Cargo.lock
packages/cli-config/Cargo.toml
packages/cli/src/cli/serve.rs

Should close https://github.com/DioxusLabs/dioxus/issues/1973

added automatic platform detection to cli if none is passed

---

packages/config-macro/src/lib.rs

Closes https://github.com/DioxusLabs/dioxus/issues/2025

fixed clippy failing in non-server environment

---

packages/fullstack/src/hooks/server_future.rs

Fix: #1950
This kicks the future until its pending, fixing the use cases where you use a future like:
```rust
use_sever_future(|| async move { sf(reactive_argument()).await });
```
We still need a better way of sending reactive dependencies to the client, but this should fix that particular issue.

Kick server futures on the client to track reactivity

---

packages/cli/src/server/mod.rs

(cherry picked from commit 8565bca11b72b09d598bbbc9bb2ba77bab262db5)

enhance: avoid failed hot-reload if backup file like .rs~ generate

---

packages/extension/package-lock.json
packages/extension/src/lib.rs
packages/extension/src/main.ts

Closes https://github.com/DioxusLabs/dioxus/issues/1978

Fixed VSCode extension

---

packages/hooks/src/use_resource.rs

Add `Resource::clear()` and also updated `Resource` docs

feat: Add `Resource::clear()` and also updated `Resource` docs

---

packages/liveview/Cargo.toml
packages/liveview/src/launch.rs

Fixes #https://github.com/DioxusLabs/dioxus/issues/2031

Fix the liveview launch function

---

Cargo.lock
examples/mobile_demo/Cargo.lock
examples/mobile_demo/Cargo.toml
examples/mobile_demo/src/lib.rs
packages/desktop/Cargo.toml
packages/desktop/src/app.rs
packages/desktop/src/ipc.rs
packages/desktop/src/launch.rs
packages/desktop/src/webview.rs
packages/dioxus/src/launch.rs

Fix mobile issues

---

packages/core-macro/src/props/mod.rs

Fix bounds on owner props

---

packages/dioxus/src/lib.rs

Closes https://github.com/DioxusLabs/dioxus/issues/2162

fix: Hide launch mod when disabled

---

packages/core/src/diff/node.rs

Fix: Move dioxus_core::diff::node logs from info to trace

---

Cargo.lock
packages/desktop/Cargo.toml
packages/html/Cargo.toml

Fixes https://github.com/DioxusLabs/dioxus/issues/2149

Bump rfd to version 0.14 fixing 2149

---

packages/cli/src/main.rs

My previous fix in #2157 wasn't set up properly. This one is correct and cleaner.

Fix: CLI Logging

---

packages/core/src/global_context.rs
packages/core/src/scope_context.rs

Let me know if I made some mistake or if there is anything to be improved!

fix: Update `use_hook` docs

---

packages/cli/src/cli/mod.rs

Revision: CLI Help Docs

---

Cargo.lock
packages/autofmt/tests/samples/many_exprs.rsx
packages/autofmt/tests/wrong/multiexpr-many.rsx
packages/autofmt/tests/wrong/oneline-expand.rsx

Dtolnay fixed a bug in prettyplease that needs correcting in our autofmt tests.
https://github.com/dtolnay/prettyplease/issues/68

Fix: flaky CI by correcting autofmt to match proper spacing

---

packages/cli-config/src/config.rs
packages/cli/src/cli/cfg.rs

cli: disable opening the tab by default, add some trace logging for config resolution

cli: small fixes and logging 

---

Cargo.lock
packages/cli/Cargo.toml
packages/cli/src/cli/create.rs

This PR is being made with the help from @ealmloff in the https://discord.com/channels/899851952891002890/1200469217884000288.
Closes #1871.

Added `dx create` options to skip user interaction

---

packages/cli/src/builder.rs

Originally #2435 but a better solution was proposed. 
This introduces a mechanism that detects if the CLI is running within a terminal. If it is, the builder will use a fancy progress bar and animation, otherwise, it will output every message through println.

Feat: Progress Bar vs Println Mechanism

---

packages/html/src/eval.rs

Currently when you try to run eval on the server, we give an error about the eval value being dropped. This PR adds a tracing error with a more clear error message

Improve server eval error message

---

.github/ISSUE_TEMPLATE/bug_report.md

- Coordinated descriptions as comments are present throughout
- Commented out version-specific details

Improve bug_report

---

packages/core/src/properties.rs

Convert closures into Option<Callback> automatcially

---

.github/workflows/main.yml
Cargo.lock
Cargo.toml
packages/cli/src/assets.rs
packages/cli/src/builder.rs
packages/cli/src/cli/check.rs
packages/cli/src/cli/link.rs
packages/cli/src/cli/mod.rs
packages/cli/src/cli/plugin.rs
packages/cli/src/cli/serve.rs
packages/cli/src/lib.rs
packages/cli/src/main.rs
packages/cli/src/server/desktop/mod.rs
packages/cli/src/server/fullstack/mod.rs
packages/cli/src/server/web/mod.rs

Adds and updates logic to work with the up-and-coming Manganis linker asset propagation.
Todo:
Builds off of https://github.com/DioxusLabs/collect-assets/pull/30

Use Manganis Linker System

---

packages/rsx/src/component.rs

Expand component definition before errors to fix component autocomplete from other modules

---

packages/cli/src/server/watcher.rs

Resolves building on Windows with https://github.com/DioxusLabs/dioxus/pull/2258/commits

Use RecommendedWatcher.

---

packages/desktop/src/config.rs

fixes https://github.com/DioxusLabs/dioxus/issues/2595
thanks to @ealmloff for his direction on fixing the issue

fix (desktop): hide menu when window decorations are disabled

---

packages/fullstack/src/launch.rs
packages/static-generation/src/launch.rs

Closes https://github.com/DioxusLabs/dioxus/issues/2587

Fix context type in static generation crate

---

Cargo.lock
Cargo.toml
packages/cli-config/src/config.rs
packages/playwright-tests/playwright.config.js
packages/playwright-tests/static-generation.spec.js
packages/playwright-tests/static-generation/.gitignore
packages/playwright-tests/static-generation/Cargo.toml
packages/playwright-tests/static-generation/src/main.rs

This should help prevent regressions like #2607

Add a playwright test that checks static generation

---

Cargo.lock
packages/desktop/Cargo.toml
packages/desktop/src/app.rs
packages/desktop/src/desktop_context.rs
packages/desktop/src/file_upload.rs
packages/desktop/src/webview.rs

In my playing around with dioxus to resolve an issue with wry, I toyed with upgrading to the latest version: `v0.41.0`
I'm not sure if it changed anything for me yet, but I figured it might be useful for the project so I've made a PR for it.
Hopefully its helpful somehow :)

feat (desktop): upgrade from wry 37 to 41

---

Cargo.lock
packages/html/Cargo.toml
packages/html/src/transit.rs

This addresses the panics shared in #2385 and #2615. It does not attempt to fix the deserialization issues.
Rather than panicking we return the error and log it

Handle deserialize errors without panic

---

packages/desktop/src/webview.rs

Disable browser shortcut keys on windows 

---

.github/workflows/main.yml

Attempt to fix CI for the release check action by clearing disk space earlier.

CI: re-reorder free disk space action to clear free up space earlier

---

packages/core-macro/src/props/mod.rs
packages/core-macro/tests/values_memoize_in_place.rs

Fix spread props diffing

---

packages/cli-config/src/config.rs

Make the web config optional in dioxus.toml

---

examples/rsx_usage.rs
packages/html/src/attribute_groups.rs

Fix #1188: enable dangerous_inner_html for svgs

---

packages/core/src/hotreload_utils.rs
packages/core/src/nodes.rs

fix issue [1586](https://github.com/DioxusLabs/dioxus/issues/1586)

fix issue 1586

---

packages/html/src/events/wheel.rs
packages/html/src/web_sys_bind/events.rs

Implements `HasMouseData` for `WheelData`
fixes [this issue](https://github.com/DioxusLabs/dioxus/issues/2597)

implement HasMouseData for WheelEvent

---

packages/cli/src/serve/mod.rs

Fix: Enable/Disable Hot Reload

---

packages/core/src/diff/mod.rs
packages/core/src/diff/node.rs
packages/core/tests/diff_dynamic_node.rs

Fix diffing Option<String>

---

packages/core/src/diff/node.rs
packages/core/tests/diff_unkeyed_list.rs

Our logic for grabbing the first or last node from a VNode with root dynamic nodes was incorrect. We only assign root_ids for otherwise static root nodes. If the root node is dynamic, we should be grabbing the id from the id for that dynamic node instead. This PR implements that fix
Fixes #2393

Fix list diffing with root dynamic nodes

---

Cargo.lock
Cargo.toml
packages/dioxus/Cargo.toml
packages/fullstack/Cargo.toml

todo(me) don't forget to tag this when it's merged!

release: 0.6.0-alpha.1 (improve docs.rs for fullstack, dioxus)

---

Cargo.lock
packages/core/Cargo.toml
packages/core/src/nodes.rs
packages/dioxus/Cargo.toml

Fixes https://github.com/DioxusLabs/manganis/issues/54

Move manganis image into attribute value implementation into core

---

Cargo.lock
Cargo.toml

- bump manganis
- add features to manganis
- fix lockfile
- Release 0.6.0-alpha.2

bump dioxus released to alpha-0.2

---

.github/workflows/publish.yml

- Fix github CLI publish CI msrv
- fix: use mac-13 for x86 builds

Fix mac CLI publish by using mac13 for runner

---

Cargo.lock

Updates wasm-bindgen to `0.2.93`

Update: wasm-bindgen

---

packages/rsx/src/attribute.rs

Fixes https://github.com/DioxusLabs/dioxus/issues/2863

Fix hot reload custom element

---

README.md

Update README.md to highlight both licenses

---

packages/hooks/src/use_coroutine.rs

Reverts DioxusLabs/dioxus#2895

Revert "feat: Manual impl of PartialEq for `Coroutine`"

---

packages/html/src/document/head.rs

Fix script component src attribute

---

packages/fullstack/src/launch.rs

[This whole block ](https://github.com/DioxusLabs/dioxus/blob/main/packages/fullstack/src/launch.rs#L140-L143) is obslete
Ref: https://discord.com/channels/899851952891002890/943190605067079712/1275245208703078432

remove unused logic in fullstack launch

---

packages/extension/Cargo.toml
packages/generational-box/Cargo.toml
packages/html-internal-macro/Cargo.toml

Chore: format some cargo tomls

---

packages/dioxus-lib/README.md
packages/dioxus/README.md
packages/ssr/README.md

docs: update `Examples` url `https://github.com/DioxusLabs/example-projects` To `https://github.com/DioxusLabs/dioxus/tree/main/examples`

docs: Modify Examples 'website

---

packages/desktop/src/assets.rs
packages/desktop/src/desktop_context.rs
packages/desktop/src/hooks.rs
packages/desktop/src/webview.rs

This pulls out the asset handler changes from https://github.com/DioxusLabs/dioxus/pull/2972

Use callback in desktop asset handler

---

packages/html/src/document/mod.rs

Fix special characters in head elements

---

packages/cli/src/serve/output.rs

Fixes the TUI YT link under the `more` section.

Fix: TUI YT Link

---

packages/cli/src/serve/watcher.rs

Fix: Windows Hot Reload

---

packages/core/tests/conditional_formatted_attributes.rs
packages/rsx/src/attribute.rs

Fixes https://github.com/DioxusLabs/dioxus/issues/3146

Fix if chain attributes with mixed expressions and strings

---

packages/core/src/global_context.rs
packages/core/src/scope_context.rs

Closes https://github.com/DioxusLabs/dioxus/issues/3135

Add a warning about using use_hook(RefCell) in the docs

---

Cargo.lock
packages/fullstack/src/serve_config.rs
packages/fullstack/src/server/launch.rs
packages/fullstack/src/server/mod.rs
packages/fullstack/src/server_context.rs
packages/playwright-tests/fullstack/src/main.rs

The context was not being forwarded from the launch builder to server functions correctly. This PR fixes that issue and adds tests

Fix providing context to server functions

---

.cargo/config.toml
Cargo.lock
Cargo.toml
packages/cli/Cargo.toml
packages/cli/src/build/bundle.rs
packages/cli/src/build/request.rs
packages/cli/src/build/web.rs
packages/cli/src/cli/build.rs
packages/cli/src/cli/bundle.rs
packages/cli/src/cli/target.rs
packages/cli/src/dioxus_crate.rs
packages/cli/src/logging.rs

- set java_home from assumed installations
- fix tracing redirection bug
Fixes: https://github.com/DioxusLabs/dioxus/issues/3218

fix: java_home and cli swallowing logs

---

packages/web/Cargo.toml

chore(web): bump web-sys & js-sys to 0.3.70

---

packages/generational-box/src/references.rs
packages/signals/src/signal.rs

Closes https://github.com/DioxusLabs/dioxus/issues/3205

document Write, GenerationalRef, and GenerationalRefMut

---

README.md

Pulls out the leptos-specific changes in the readme work from #3225

simplify leptos comparison

---

packages/cli/src/serve/ansi_buffer.rs
packages/cli/src/serve/output.rs
packages/const-serialize/src/lib.rs

fix: line clipping and overlapping

---

examples/fullstack-auth/src/auth.rs
examples/fullstack-auth/src/main.rs
packages/fullstack/src/server_context.rs

This PR simplifies the auth example and loosens the bounds on the fullstack `extract` method. It fixes some of the issues in https://github.com/DioxusLabs/dioxus/issues/3529

Simplify fullstack auth example

---

packages/playwright-tests/web/src/main.rs
packages/web/src/document.rs

Fixes #3655 
Fixes https://github.com/DioxusLabs/docsite/issues/398

Fix web eval return

---

Cargo.lock
Cargo.toml
packages/cli/src/bundle_utils.rs
packages/cli/src/config/bundle.rs

Updates tauri-bundler and adds their new debian `recommends` option.

Update: tauri-bundler, tauri-utils

---

Cargo.toml
packages/desktop/Cargo.toml
packages/desktop/src/config.rs
packages/desktop/src/webview.rs
packages/mobile/Cargo.toml

fix: Fix the issue where TAB cannot cycle through focus elements. #2900

Update wry version to 0.50.1

---

packages/html/src/events/mouse.rs

trivial fix for documentation example for onclick handler of buttons

---

packages/cli/assets/android/gen/app/src/main/AndroidManifest.xml.hbs

Modified the AndroidManifest.xml file according to [https://developer.android.com/guide/topics/manifest/activity-element#config](https://developer.android.com/guide/topics/manifest/activity-element#config) so Android apps created with Dioxus handle orientation changes properly.
Fixes [https://github.com/DioxusLabs/dioxus/issues/3470](https://github.com/DioxusLabs/dioxus/issues/3470)

Fixed android app crashing when changing phone orientation

---

packages/desktop/src/event_handlers.rs

Small comment fix related to https://github.com/DioxusLabs/dioxus/pull/3908

fix comment

---

packages/core-macro/src/component.rs
packages/core-macro/tests/generics.rs

Fixes #3914 and adds a regression test

Fix component macro with where clause

---

.devcontainer/Dockerfile
.devcontainer/README.md
.devcontainer/devcontainer.json

Since the Playwright installation process only works well on systems with `apt` rather than `yum`/`dnf`, I decided to improve the Dev Container:
- **General Changes**
Simplifies the `Dockerfile` by removing redundancies and installs Dioxus dependencies as specified in the documentation.
- **Replace Deprecated Extension**
Replaces the deprecated `crates` extension with the new `dependi` extension.
- **Playwright Integration**
Adds the Playwright extension and pre-installs its dependencies.
- **README Adjustments**
Updates the `README.md` to reflect the new changes.

Update and Improve Dev Container

---

packages/rsx/src/attribute.rs
packages/rsx/tests/parsing.rs

call_with_explicit_closure support closure in block

---

packages/core/src/error_boundary.rs
packages/core/tests/error_boundary.rs

This PR fixes two issues with clearing error boundaries:
1) We hold the lock while running user code in the error boundary closure
2) We don't rerun the error boundary when the error boundary is cleared
It also adds more documentation about how you are expected to clear error boundaries and a regression test to prevent future issues
Fixes #4016
Closes #4039

Fix clearing error boundaries

---

.github/actions/free-disk-space/action.yml
.github/workflows/main.yml

Hello Dioxus team, this PR should fix this issue :
https://github.com/DioxusLabs/dioxus/actions/runs/14895782359/job/41837923526
I've created a reusable workflow so that it can easily be called up in other jobs if needed.

fix(ci): out of disk space

---

.github/workflows/main.yml
Cargo.lock
packages/cli/src/build/request.rs
packages/cli/src/config/dioxus_config.rs
packages/cli/src/serve/server.rs
packages/cli/src/wasm_opt.rs

Playwright passes locally for me - but has random spurious failures. This tries to fix that. I think there might be a race condition somewhere when we run the devservers in parallel
looks like it might be
https://github.com/rustwasm/wasm-pack/issues/1441

attempt to fix playwright

---

translations/zh-cn/README.md

Hello, I've noticed that the Chinese README was AI-translated without manually proofread. This has resulted in some errors.
A clear example is an interruption at this location:
https://github.com/DioxusLabs/dioxus/blob/693f5c61b9408251938eb86227138bd53ceec80a/translations/zh-cn/README.md?plain=1#L224-L225
so I re-translated it

update and improve chinese README.md

---

packages/cli/src/serve/output.rs

Fixes https://github.com/DioxusLabs/dioxus/issues/4004

tell user about basepath

---

packages/fullstack-hooks/src/hooks/server_cached.rs

Improve `use_server_cached` docs

Improve use_server_cached docs

---

Cargo.lock
packages/cli/Cargo.toml
packages/cli/src/build/builder.rs
packages/cli/src/build/context.rs
packages/cli/src/build/request.rs
packages/cli/src/cli/create.rs
packages/cli/src/cli/run.rs
packages/cli/src/cli/target.rs
packages/cli/src/serve/output.rs
packages/cli/src/workspace.rs
packages/dx-wire-format/src/lib.rs

Fixes https://github.com/DioxusLabs/dioxus/issues/4577 by letting you specify the name of the device you want to upload your app to.
Works for both iOS and Android

fix: select best match from --device

---

packages/config-macro/src/lib.rs

Added mobile feature target to config macro

Fixed client config macro

---

packages/desktop/src/launch.rs

Closes https://github.com/DioxusLabs/dioxus/issues/4087

Don't try launching a tokio runtime if we are already within one

---

packages/cli/src/settings.rs
packages/cli/src/workspace.rs

fix: save cli config as a toml file
